// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=banking  Provider=7_suts_llm_provider  Mode=?  Stories=7
// Source: artifacts/hls_det/7_suts_llm_provider/banking/hls_gold.json
// ============================================================================
bthread("CRUD_account", function() {
});

bthread("CRUD_card", function() {
});

bthread("CRUD_customer", function() {
});

bthread("CRUD_loan", function() {
});

bthread("CRUD_reset", function() {
});

bthread("CRUD_transaction", function() {
});

bthread("CRUD_transfer", function() {
});
