//@provengo summon rest

// === Auto-generated interfaces.readable.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

var host = (typeof host !== 'undefined') ? host : 'localhost';
var port = (typeof port !== 'undefined') ? port : 8080;

const svc = new RESTSession("http://" + host + ":" + port, "provengo-client", {
  headers: { "Content-Type": "application/json" },
});

function matchesDescriptionRegex(re) {
  return bp.EventSet("Match description", function (e) {
    return e && e.data && e.data.parameters && typeof e.data.parameters.description === "string"
           && re.test(e.data.parameters.description);
  });
}

// ---- Entity: Customer ----

function addCustomer(id, name) {
  var url = "/customers";
  var description = "Add a customer with id " + id + " and name " + name + "";
  var body = {
    "id": id,
    "name": name
  };
  return svc.request({
    method: "POST",
    url: url,
    parameters: { description: description },
    body: body
  });
}

function deleteCustomer(id, name) {
  var url = "/customers/" + id + "";
  var description = "Delete a customer with id " + id + " and name " + name + "";
  var body = undefined;
  return svc.request({
    method: "DELETE",
    url: url,
    parameters: { description: description },
    body: body
  });
}

function verifyCustomerExists(id, name) {
  // TODO: implement verification or guard logic if needed.
}

function waitForAnyCustomerAdded() {
  var ev = bp.sync({waitFor: matchesDescriptionRegex(/Add a customer with id (.+) and name (.+)/)});
  var m = ev.data.parameters.description.match(/Add a customer with id (.+) and name (.+)/);
  var captures = m.slice(1);
  var names = ["id", "name"];
  var obj = {};
  for (var i = 0; i < names.length; i++) {
    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;
  }
  return obj;
}

function waitForAnyCustomerDeleted() {
  var ev = bp.sync({waitFor: matchesDescriptionRegex(/Delete a customer with id (.+) and name (.+)/)});
  var m = ev.data.parameters.description.match(/Delete a customer with id (.+) and name (.+)/);
  var captures = m.slice(1);
  var names = ["id", "name"];
  var obj = {};
  for (var i = 0; i < names.length; i++) {
    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;
  }
  return obj;
}

// ---- Entity: Account ----

function addAccount(accountId) {
  var url = "/accounts";
  var description = "Add an account with accountId " + accountId + "";
  var body = {
    "accountId": accountId
  };
  return svc.request({
    method: "POST",
    url: url,
    parameters: { description: description },
    body: body
  });
}

function deleteAccount(accountId) {
  var url = "/accounts/" + accountId + "";
  var description = "Delete an account with accountId " + accountId + "";
  var body = undefined;
  return svc.request({
    method: "DELETE",
    url: url,
    parameters: { description: description },
    body: body
  });
}

function verifyAccountExists(accountId) {
  // TODO: implement verification or guard logic if needed.
}

function waitForAnyAccountAdded() {
  var ev = bp.sync({waitFor: matchesDescriptionRegex(/Add an account with accountId (.+)/)});
  var m = ev.data.parameters.description.match(/Add an account with accountId (.+)/);
  var captures = m.slice(1);
  var names = ["accountId"];
  var obj = {};
  for (var i = 0; i < names.length; i++) {
    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;
  }
  return obj;
}

function waitForAnyAccountDeleted() {
  var ev = bp.sync({waitFor: matchesDescriptionRegex(/Delete an account with accountId (.+)/)});
  var m = ev.data.parameters.description.match(/Delete an account with accountId (.+)/);
  var captures = m.slice(1);
  var names = ["accountId"];
  var obj = {};
  for (var i = 0; i < names.length; i++) {
    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;
  }
  return obj;
}

// ---- Entity: Loan ----

function addLoan(loanId) {
  var url = "/loans";
  var description = "Add a loan with loanId " + loanId + "";
  var body = {
    "loanId": loanId
  };
  return svc.request({
    method: "POST",
    url: url,
    parameters: { description: description },
    body: body
  });
}

function deleteLoan(loanId) {
  var url = "/loans/" + loanId + "";
  var description = "Delete a loan with loanId " + loanId + "";
  var body = undefined;
  return svc.request({
    method: "DELETE",
    url: url,
    parameters: { description: description },
    body: body
  });
}

function verifyLoanExists(loanId) {
  // TODO: implement verification or guard logic if needed.
}

function waitForAnyLoanAdded() {
  var ev = bp.sync({waitFor: matchesDescriptionRegex(/Add a loan with loanId (.+)/)});
  var m = ev.data.parameters.description.match(/Add a loan with loanId (.+)/);
  var captures = m.slice(1);
  var names = ["loanId"];
  var obj = {};
  for (var i = 0; i < names.length; i++) {
    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;
  }
  return obj;
}

function waitForAnyLoanDeleted() {
  var ev = bp.sync({waitFor: matchesDescriptionRegex(/Delete a loan with loanId (.+)/)});
  var m = ev.data.parameters.description.match(/Delete a loan with loanId (.+)/);
  var captures = m.slice(1);
  var names = ["loanId"];
  var obj = {};
  for (var i = 0; i < names.length; i++) {
    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;
  }
  return obj;
}

// ---- Entity: Card ----

function addCard(cardId) {
  var url = "/cards";
  var description = "Add a card with cardId " + cardId + "";
  var body = {
    "cardId": cardId
  };
  return svc.request({
    method: "POST",
    url: url,
    parameters: { description: description },
    body: body
  });
}

function deleteCard(cardId) {
  var url = "/cards/" + cardId + "";
  var description = "Delete a card with cardId " + cardId + "";
  var body = undefined;
  return svc.request({
    method: "DELETE",
    url: url,
    parameters: { description: description },
    body: body
  });
}

function verifyCardExists(cardId) {
  // TODO: implement verification or guard logic if needed.
}

function waitForAnyCardAdded() {
  var ev = bp.sync({waitFor: matchesDescriptionRegex(/Add a card with cardId (.+)/)});
  var m = ev.data.parameters.description.match(/Add a card with cardId (.+)/);
  var captures = m.slice(1);
  var names = ["cardId"];
  var obj = {};
  for (var i = 0; i < names.length; i++) {
    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;
  }
  return obj;
}

function waitForAnyCardDeleted() {
  var ev = bp.sync({waitFor: matchesDescriptionRegex(/Delete a card with cardId (.+)/)});
  var m = ev.data.parameters.description.match(/Delete a card with cardId (.+)/);
  var captures = m.slice(1);
  var names = ["cardId"];
  var obj = {};
  for (var i = 0; i < names.length; i++) {
    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;
  }
  return obj;
}

