// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

bp.registerBThread("Index_basicCrud", function() {
  // Basic CRUD story for Index
  addIndex(undefined, undefined);
  verifyIndexExists(undefined, undefined);
  deleteIndex(undefined, undefined);
});

bp.registerBThread("Document_basicCrud", function() {
  // Basic CRUD story for Document
  addDocument(201, undefined, undefined, undefined, undefined);
  verifyDocumentExists(201, undefined, undefined, undefined, undefined);
  deleteDocument(201, undefined, undefined, undefined, undefined);
});

bp.registerBThread("Document_duplicateAdd", function() {
  // Duplicate-add scenario for Document
  addDocument(202, undefined, undefined, undefined, undefined);
  verifyDocumentExists(202, undefined, undefined, undefined, undefined);
  addDocument(202, undefined, undefined, undefined, undefined);  // expected to fail or be blocked
});

