// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=jira_cloud  Provider=real_world_llm_provider  Mode=?  Stories=213
// Source: artifacts/hls_det/real_world_llm_provider/jira_cloud/hls_gold.json
// ============================================================================
bthread("CRUD_1", function() {
});

bthread("CRUD_3", function() {
});

bthread("CRUD_accessible", function() {
});

bthread("CRUD_actor", function() {
});

bthread("CRUD_addon", function() {
});

bthread("CRUD_addtodefault", function() {
});

bthread("CRUD_advanced_setting", function() {
});

bthread("CRUD_alternative", function() {
});

bthread("CRUD_analyse", function() {
});

bthread("CRUD_announcementbanner", function() {
});

bthread("CRUD_api", function() {
});

bthread("CRUD_app", function() {
});

bthread("CRUD_application_property", function() {
});

bthread("CRUD_applicationrole", function() {
});

bthread("CRUD_approximate_count", function() {
});

bthread("CRUD_approximatelicensecount", function() {
});

bthread("CRUD_archive", function() {
});

bthread("CRUD_assignable", function() {
});

bthread("CRUD_assignee", function() {
});

bthread("CRUD_association", function() {
});

bthread("CRUD_atlassian", function() {
});

bthread("CRUD_atlassian_connect", function() {
});

bthread("CRUD_attachment", function() {
});

bthread("CRUD_auditing", function() {
});

bthread("CRUD_autocompletedata", function() {
});

bthread("CRUD_available", function() {
});

bthread("CRUD_availablefield", function() {
});

bthread("CRUD_avatar", function() {
});

bthread("CRUD_avatar2", function() {
});

bthread("CRUD_bulk", function() {
});

bthread("CRUD_bulkfetch", function() {
});

bthread("CRUD_byname", function() {
});

bthread("CRUD_cancel", function() {
});

bthread("CRUD_capability", function() {
});

bthread("CRUD_changelog", function() {
});

bthread("CRUD_check", function() {
});

bthread("CRUD_classification_level", function() {
});

bthread("CRUD_column", function() {
});

bthread("CRUD_comment", function() {
});

bthread("CRUD_component", function() {
});

bthread("CRUD_computation", function() {
});

bthread("CRUD_config", function() {
});

bthread("CRUD_configuration", function() {
});

bthread("CRUD_content", function() {
});

bthread("CRUD_context", function() {
});

bthread("CRUD_copy", function() {
});

bthread("CRUD_create", function() {
});

bthread("CRUD_createdraft", function() {
});

bthread("CRUD_createmeta", function() {
});

bthread("CRUD_customfieldoption", function() {
});

bthread("CRUD_dashboard", function() {
});

bthread("CRUD_data_policy", function() {
});

bthread("CRUD_default", function() {
});

bthread("CRUD_defaulteditor", function() {
});

bthread("CRUD_defaultsharescope", function() {
});

bthread("CRUD_defaultvalue", function() {
});

bthread("CRUD_delete", function() {
});

bthread("CRUD_deleted", function() {
});

bthread("CRUD_draft", function() {
});

bthread("CRUD_duplicate", function() {
});

bthread("CRUD_dynamic", function() {
});

bthread("CRUD_edit", function() {
});

bthread("CRUD_edit_template", function() {
});

bthread("CRUD_editmeta", function() {
});

bthread("CRUD_email", function() {
});

bthread("CRUD_eval", function() {
});

bthread("CRUD_evaluate", function() {
});

bthread("CRUD_event", function() {
});

bthread("CRUD_expand", function() {
});

bthread("CRUD_export", function() {
});

bthread("CRUD_expression", function() {
});

bthread("CRUD_failed", function() {
});

bthread("CRUD_favourite", function() {
});

bthread("CRUD_feature", function() {
});

bthread("CRUD_field", function() {
});

bthread("CRUD_fieldconfiguration", function() {
});

bthread("CRUD_fieldconfigurationscheme", function() {
});

bthread("CRUD_filter", function() {
});

bthread("CRUD_forge", function() {
});

bthread("CRUD_function", function() {
});

bthread("CRUD_gadget", function() {
});

bthread("CRUD_group", function() {
});

bthread("CRUD_groupuserpicker", function() {
});

bthread("CRUD_hierarchy", function() {
});

bthread("CRUD_human", function() {
});

bthread("CRUD_instance", function() {
});

bthread("CRUD_issue", function() {
});

bthread("CRUD_issuelink", function() {
});

bthread("CRUD_issuelinktype", function() {
});

bthread("CRUD_issuesecuritylevelscheme", function() {
});

bthread("CRUD_issuesecurityscheme", function() {
});

bthread("CRUD_issuetype", function() {
});

bthread("CRUD_issuetypemapping", function() {
});

bthread("CRUD_issuetypescheme", function() {
});

bthread("CRUD_issuetypescreenscheme", function() {
});

bthread("CRUD_issuetypeusage", function() {
});

bthread("CRUD_item", function() {
});

bthread("CRUD_jql", function() {
});

bthread("CRUD_key", function() {
});

bthread("CRUD_label", function() {
});

bthread("CRUD_level", function() {
});

bthread("CRUD_license", function() {
});

bthread("CRUD_limit", function() {
});

bthread("CRUD_list", function() {
});

bthread("CRUD_live_template", function() {
});

bthread("CRUD_locale", function() {
});

bthread("CRUD_mapping", function() {
});

bthread("CRUD_match", function() {
});

bthread("CRUD_member", function() {
});

bthread("CRUD_mergeto", function() {
});

bthread("CRUD_meta", function() {
});

bthread("CRUD_migration", function() {
});

bthread("CRUD_module", function() {
});

bthread("CRUD_move", function() {
});

bthread("CRUD_multi", function() {
});

bthread("CRUD_multiprojectsearch", function() {
});

bthread("CRUD_my", function() {
});

bthread("CRUD_mypermission", function() {
});

bthread("CRUD_mypreference", function() {
});

bthread("CRUD_myself", function() {
});

bthread("CRUD_nav4_opt_property", function() {
});

bthread("CRUD_notification", function() {
});

bthread("CRUD_notificationscheme", function() {
});

bthread("CRUD_notify", function() {
});

bthread("CRUD_option", function() {
});

bthread("CRUD_owner", function() {
});

bthread("CRUD_parse", function() {
});

bthread("CRUD_pdcleaner", function() {
});

bthread("CRUD_permission", function() {
});

bthread("CRUD_permissionscheme", function() {
});

bthread("CRUD_picker", function() {
});

bthread("CRUD_plan", function() {
});

bthread("CRUD_planonly", function() {
});

bthread("CRUD_preview", function() {
});

bthread("CRUD_priority", function() {
});

bthread("CRUD_priorityscheme", function() {
});

bthread("CRUD_product", function() {
});

bthread("CRUD_project", function() {
});

bthread("CRUD_project_template", function() {
});

bthread("CRUD_projectcategory", function() {
});

bthread("CRUD_projectmapping", function() {
});

bthread("CRUD_projectusage", function() {
});

bthread("CRUD_projectvalidate", function() {
});

bthread("CRUD_property", function() {
});

bthread("CRUD_publish", function() {
});

bthread("CRUD_query", function() {
});

bthread("CRUD_queue", function() {
});

bthread("CRUD_raw", function() {
});

bthread("CRUD_read", function() {
});

bthread("CRUD_recent", function() {
});

bthread("CRUD_record", function() {
});

bthread("CRUD_redact", function() {
});

bthread("CRUD_refresh", function() {
});

bthread("CRUD_relatedissuecount", function() {
});

bthread("CRUD_relatedwork", function() {
});

bthread("CRUD_remotelink", function() {
});

bthread("CRUD_remove", function() {
});

bthread("CRUD_remove_template", function() {
});

bthread("CRUD_removeandswap", function() {
});

bthread("CRUD_report", function() {
});

bthread("CRUD_resolution", function() {
});

bthread("CRUD_rest", function() {
});

bthread("CRUD_restore", function() {
});

bthread("CRUD_role", function() {
});

bthread("CRUD_roledetail", function() {
});

bthread("CRUD_rule", function() {
});

bthread("CRUD_sanitize", function() {
});

bthread("CRUD_save_template", function() {
});

bthread("CRUD_screen", function() {
});

bthread("CRUD_screenscheme", function() {
});

bthread("CRUD_search", function() {
});

bthread("CRUD_securitylevel", function() {
});

bthread("CRUD_serverinfo", function() {
});

bthread("CRUD_service_registry", function() {
});

bthread("CRUD_setting", function() {
});

bthread("CRUD_statu", function() {
});

bthread("CRUD_status", function() {
});

bthread("CRUD_statuscategory", function() {
});

bthread("CRUD_suggestion", function() {
});

bthread("CRUD_system", function() {
});

bthread("CRUD_tab", function() {
});

bthread("CRUD_task", function() {
});

bthread("CRUD_team", function() {
});

bthread("CRUD_thumbnail", function() {
});

bthread("CRUD_timetracking", function() {
});

bthread("CRUD_transition", function() {
});

bthread("CRUD_trash", function() {
});

bthread("CRUD_trashed", function() {
});

bthread("CRUD_type", function() {
});

bthread("CRUD_uimodification", function() {
});

bthread("CRUD_unarchive", function() {
});

bthread("CRUD_universal_avatar", function() {
});

bthread("CRUD_unresolvedissuecount", function() {
});

bthread("CRUD_unwatch", function() {
});

bthread("CRUD_update", function() {
});

bthread("CRUD_updated", function() {
});

bthread("CRUD_user", function() {
});

bthread("CRUD_validation", function() {
});

bthread("CRUD_validprojectkey", function() {
});

bthread("CRUD_validprojectname", function() {
});

bthread("CRUD_value", function() {
});

bthread("CRUD_version", function() {
});

bthread("CRUD_view", function() {
});

bthread("CRUD_viewissue", function() {
});

bthread("CRUD_vote", function() {
});

bthread("CRUD_watch", function() {
});

bthread("CRUD_watcher", function() {
});

bthread("CRUD_watching", function() {
});

bthread("CRUD_webhook", function() {
});

bthread("CRUD_workflow", function() {
});

bthread("CRUD_workflowscheme", function() {
});

bthread("CRUD_workflowusage", function() {
});

bthread("CRUD_worklog", function() {
});
