// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

bp.registerBThread("User_basicCrud", function() {
  // Basic CRUD story for User
  addUser("name_201", undefined, "name_201");
  verifyUserExists("name_201", undefined, "name_201");
  deleteUser("name_201", undefined, "name_201");
});

bp.registerBThread("Repo_basicCrud", function() {
  // Basic CRUD story for Repository
  createRepo(undefined, undefined);
  verifyRepoExists(undefined, undefined);
  deleteRepo(undefined, undefined);
});

bp.registerBThread("Issue_basicCrud", function() {
  // Basic CRUD story for Issue
  createIssue(undefined, undefined, undefined);
  verifyIssueExists(undefined, undefined, undefined);
  deleteIssue(undefined, undefined, undefined);
});

bp.registerBThread("User_duplicateAdd", function() {
  // Duplicate-add scenario for User
  addUser("name_202", undefined, "name_202");
  verifyUserExists("name_202", undefined, "name_202");
  addUser("name_202", undefined, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("Repo_duplicateAdd", function() {
  // Duplicate-add scenario for Repository
  createRepo(undefined, undefined);
  verifyRepoExists(undefined, undefined);
  createRepo(undefined, undefined);  // expected to fail or be blocked
});

bp.registerBThread("Issue_duplicateAdd", function() {
  // Duplicate-add scenario for Issue
  createIssue(undefined, undefined, undefined);
  verifyIssueExists(undefined, undefined, undefined);
  createIssue(undefined, undefined, undefined);  // expected to fail or be blocked
});

