#!/usr/bin/env python
"""Generate interfaces.readable.js and stories_hls.js from a unified SUT spec."""

import argparse
import json
from pathlib import Path
from typing import Dict, Any, List


JS_HEADER_INTERFACES = """\
//@provengo summon rest

// === Auto-generated interfaces.readable.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

var host = (typeof host !== 'undefined') ? host : 'localhost';
var port = (typeof port !== 'undefined') ? port : 8080;

const svc = new RESTSession("http://" + host + ":" + port, "provengo-client", {
  headers: { "Content-Type": "application/json" },
});

function matchesDescriptionRegex(re) {
  return bp.EventSet("Match description", function (e) {
    return e && e.data && e.data.parameters && typeof e.data.parameters.description === "string"
           && re.test(e.data.parameters.description);
  });
}

"""


JS_HEADER_STORIES = """\
// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

"""


def js_param_list(params: List[str]) -> str:
    return ", ".join(params)


def render_body_template(body_template: Dict[str, Any]) -> str:
    lines = []
    for k, v in body_template.items():
        if isinstance(v, str) and v.startswith("{") and v.endswith("}"):
            pname = v[1:-1]
            lines.append(f'    "{k}": {pname}')
        else:
            lit = json.dumps(v)
            lines.append(f'    "{k}": {lit}')
    if not lines:
        return "{}"
    return "{\n" + ",\n".join(lines) + "\n  }"


def render_interfaces_for_entity(name: str, ent: Dict[str, Any]) -> str:
    params = ent.get("params", [])
    ops = ent.get("operations", {})
    waits = ent.get("waitForPatterns", {})

    out: List[str] = []
    out.append(f"// ---- Entity: {name} ----\n\n")

    # CRUD-like operations
    for op_key, op in ops.items():
        fname = op["name"]
        method = op.get("method")
        path_tmpl = op.get("path", "")
        desc_tmpl = op.get("descriptionTemplate")
        body_tmpl = op.get("bodyTemplate")

        sig = js_param_list(params)
        out.append(f"function {fname}({sig}) {{\n")

        if not method:
            out.append("  // TODO: implement verification or guard logic if needed.\n")
            out.append("}\n\n")
            continue

        # Path expression with {param} placeholders
        path_expr = '"' + path_tmpl + '"'
        for p in params:
            placeholder = "{" + p + "}"
            if placeholder in path_tmpl:
                path_expr = '"' + path_tmpl.replace(placeholder, '" + ' + p + ' + "') + '"'

        out.append(f"  var url = {path_expr};\n")

        # Description
        if desc_tmpl:
            desc_js = desc_tmpl
            for p in params:
                desc_js = desc_js.replace("{" + p + "}", '" + ' + p + ' + "')
            desc_expr = '"' + desc_js + '"'
            out.append("  var description = " + desc_expr + ";\n")
        else:
            out.append('  var description = "";\n')

        # Body
        if body_tmpl:
            body_expr = render_body_template(body_tmpl)
            out.append("  var body = " + body_expr + ";\n")
        else:
            out.append("  var body = undefined;\n")

        out.append("  return svc.request({\n")
        out.append(f'    method: "{method}",\n')
        out.append("    url: url,\n")
        out.append("    parameters: { description: description },\n")
        out.append("    body: body\n")
        out.append("  });\n")
        out.append("}\n\n")

    # Wait-for patterns
    for key, wf in waits.items():
        wname = wf["name"]
        regex = wf["descriptionRegex"]
        out.append(f"function {wname}() {{\n")
        out.append(f"  var ev = bp.sync({{waitFor: matchesDescriptionRegex(/{regex}/)}});\n")
        out.append(f"  var m = ev.data.parameters.description.match(/{regex}/);\n")
        out.append("  var captures = m.slice(1);\n")
        out.append("  var names = " + json.dumps(params) + ";\n")
        out.append("  var obj = {};\n")
        out.append("  for (var i = 0; i < names.length; i++) {\n")
        out.append("    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;\n")
        out.append("  }\n")
        out.append("  return obj;\n")
        out.append("}\n\n")

    return "".join(out)


def render_interfaces_for_spec(spec: Dict[str, Any]) -> str:
    ents = spec.get("entities", {})
    out: List[str] = [JS_HEADER_INTERFACES]
    for name, ent in ents.items():
        out.append(render_interfaces_for_entity(name, ent))
    return "".join(out)


def render_stories_for_spec(spec: Dict[str, Any]) -> str:
    ents = spec.get("entities", {})
    stories = spec.get("stories", [])
    out: List[str] = [JS_HEADER_STORIES]

    def ent_params(entity_name: str) -> List[str]:
        return ents[entity_name].get("params", [])

    for s in stories:
        sname = s["name"]
        ent_name = s["entity"]
        pattern = s["pattern"]
        params = ent_params(ent_name)
        ent = ents[ent_name]
        ops = ent["operations"]

        out.append(f'bp.registerBThread("{sname}", function() {{\n')

        if pattern == "crud_basic":
            add_f = ops["add"]["name"]
            ver_f = ops["verifyExists"]["name"]
            del_f = ops["delete"]["name"]

            args_literal = []
            for p in params:
                if p == "id":
                    args_literal.append("201")
                elif "name" in p:
                    args_literal.append('"name_201"')
                else:
                    args_literal.append("undefined")
            args_str = ", ".join(args_literal)

            out.append(f"  // Basic CRUD story for {ent_name}\n")
            out.append(f"  {add_f}({args_str});\n")
            out.append(f"  {ver_f}({args_str});\n")
            out.append(f"  {del_f}({args_str});\n")
            out.append("});\n\n")

        elif pattern == "duplicate_add":
            add_f = ops["add"]["name"]
            ver_f = ops["verifyExists"]["name"]

            args_literal = []
            for p in params:
                if p == "id":
                    args_literal.append("202")
                elif "name" in p:
                    args_literal.append('"name_202"')
                else:
                    args_literal.append("undefined")
            args_str = ", ".join(args_literal)

            out.append(f"  // Duplicate-add scenario for {ent_name}\n")
            out.append(f"  {add_f}({args_str});\n")
            out.append(f"  {ver_f}({args_str});\n")
            out.append(f"  {add_f}({args_str});  // expected to fail or be blocked\n")
            out.append("});\n\n")

        else:
            out.append(f"  // TODO: pattern {pattern!r} not implemented yet.\n")
            out.append("});\n\n")

    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True, help="Path to unified SUT spec JSON")
    ap.add_argument("--out-dir", required=True, help="Directory to write JS outputs")
    args = ap.parse_args()

    spec_path = Path(args.spec)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    spec = json.loads(spec_path.read_text(encoding="utf-8"))

    interfaces_js = render_interfaces_for_spec(spec)
    stories_js = render_stories_for_spec(spec)

    (out_dir / "interfaces.readable.js").write_text(interfaces_js, encoding="utf-8")
    (out_dir / "stories_hls.js").write_text(stories_js, encoding="utf-8")

    print(f"[OK] Wrote interfaces.readable.js and stories_hls.js to {out_dir}")


if __name__ == "__main__":
    main()
