// Auto-generated HLS stories (readable)
// DO NOT EDIT MANUALLY – generated by emit_hls_all_in_one.py
// SUT      : pharmacy
// Provider : 7_suts_llm_provider
// Mode     : nondet
// Source   : hls_gold.json
// Stories  : 70

//@provengo summon rest


// Story: crud:drug:nondet:1:1
// ---- crud:drug:nondet:1:1 ----
bthread("crud:drug:nondet:1:1", function () {
  let id = 200;
  let drug_name = "Name 200";
  addDrug(id, drug_name);
  tryToAddExistingDrug(id, drug_name);
  verifyDrugExists(id, drug_name);
  updateDrug(id, drug_name);
  deleteDrug(id, drug_name);
  tryToDeleteANonExistingDrug(id, drug_name);
  verifyDrugDoesNotExist(id, drug_name);
});


// Story: crud:drug:nondet:1:2
// ---- crud:drug:nondet:1:2 ----
bthread("crud:drug:nondet:1:2", function () {
  let id = 201;
  let drug_name = "Name 201";
  addDrug(id, drug_name);
  tryToAddExistingDrug(id, drug_name);
  updateDrug(id, drug_name);
  verifyDrugExists(id, drug_name);
  deleteDrug(id, drug_name);
  tryToDeleteANonExistingDrug(id, drug_name);
  verifyDrugDoesNotExist(id, drug_name);
});


// Story: crud:drug:nondet:1:3
// ---- crud:drug:nondet:1:3 ----
bthread("crud:drug:nondet:1:3", function () {
  let id = 202;
  let drug_name = "Name 202";
  addDrug(id, drug_name);
  tryToAddExistingDrug(id, drug_name);
  verifyDrugExists(id, drug_name);
  deleteDrug(id, drug_name);
  tryToDeleteANonExistingDrug(id, drug_name);
  verifyDrugDoesNotExist(id, drug_name);
});


// Story: crud:drug:nondet:1:4
// ---- crud:drug:nondet:1:4 ----
bthread("crud:drug:nondet:1:4", function () {
  let id = 204;
  let drug_name = "Name 204";
  addDrug(id, drug_name);
  tryToAddExistingDrug(id, drug_name);
  deleteDrug(id, drug_name);
  tryToDeleteANonExistingDrug(id, drug_name);
  verifyDrugDoesNotExist(id, drug_name);
});


// Story: crud:inventory:nondet:2:1
// ---- crud:inventory:nondet:2:1 ----
bthread("crud:inventory:nondet:2:1", function () {
  let ndc = "ndc_210";
  addInventory(ndc);
  tryToAddExistingInventory(ndc);
  verifyInventoryExists(ndc);
  updateInventory(ndc);
  deleteInventory(ndc);
  tryToDeleteANonExistingInventory(ndc);
  verifyInventoryDoesNotExist(ndc);
});


// Story: crud:inventory:nondet:2:2
// ---- crud:inventory:nondet:2:2 ----
bthread("crud:inventory:nondet:2:2", function () {
  let ndc = "ndc_211";
  addInventory(ndc);
  tryToAddExistingInventory(ndc);
  updateInventory(ndc);
  verifyInventoryExists(ndc);
  deleteInventory(ndc);
  tryToDeleteANonExistingInventory(ndc);
  verifyInventoryDoesNotExist(ndc);
});


// Story: crud:inventory:nondet:2:3
// ---- crud:inventory:nondet:2:3 ----
bthread("crud:inventory:nondet:2:3", function () {
  let ndc = "ndc_212";
  addInventory(ndc);
  tryToAddExistingInventory(ndc);
  verifyInventoryExists(ndc);
  deleteInventory(ndc);
  tryToDeleteANonExistingInventory(ndc);
  verifyInventoryDoesNotExist(ndc);
});


// Story: crud:inventory:nondet:2:4
// ---- crud:inventory:nondet:2:4 ----
bthread("crud:inventory:nondet:2:4", function () {
  let ndc = "ndc_214";
  addInventory(ndc);
  tryToAddExistingInventory(ndc);
  deleteInventory(ndc);
  tryToDeleteANonExistingInventory(ndc);
  verifyInventoryDoesNotExist(ndc);
});


// Story: crud:order:nondet:3:1
// ---- crud:order:nondet:3:1 ----
bthread("crud:order:nondet:3:1", function () {
  let id = 220;
  addOrder(id);
  tryToAddExistingOrder(id);
  verifyOrderExists(id);
  updateOrder(id);
  deleteOrder(id);
  tryToDeleteANonExistingOrder(id);
  verifyOrderDoesNotExist(id);
});


// Story: crud:order:nondet:3:2
// ---- crud:order:nondet:3:2 ----
bthread("crud:order:nondet:3:2", function () {
  let id = 221;
  addOrder(id);
  tryToAddExistingOrder(id);
  updateOrder(id);
  verifyOrderExists(id);
  deleteOrder(id);
  tryToDeleteANonExistingOrder(id);
  verifyOrderDoesNotExist(id);
});


// Story: crud:order:nondet:3:3
// ---- crud:order:nondet:3:3 ----
bthread("crud:order:nondet:3:3", function () {
  let id = 222;
  addOrder(id);
  tryToAddExistingOrder(id);
  verifyOrderExists(id);
  deleteOrder(id);
  tryToDeleteANonExistingOrder(id);
  verifyOrderDoesNotExist(id);
});


// Story: crud:order:nondet:3:4
// ---- crud:order:nondet:3:4 ----
bthread("crud:order:nondet:3:4", function () {
  let id = 224;
  addOrder(id);
  tryToAddExistingOrder(id);
  deleteOrder(id);
  tryToDeleteANonExistingOrder(id);
  verifyOrderDoesNotExist(id);
});


// Story: crud:patient:nondet:4:1
// ---- crud:patient:nondet:4:1 ----
bthread("crud:patient:nondet:4:1", function () {
  let id = 230;
  let patient_name = "Name 230";
  addPatient(id, patient_name);
  tryToAddExistingPatient(id, patient_name);
  verifyPatientExists(id, patient_name);
  updatePatient(id, patient_name);
  deletePatient(id, patient_name);
  tryToDeleteANonExistingPatient(id, patient_name);
  verifyPatientDoesNotExist(id, patient_name);
});


// Story: crud:patient:nondet:4:2
// ---- crud:patient:nondet:4:2 ----
bthread("crud:patient:nondet:4:2", function () {
  let id = 231;
  let patient_name = "Name 231";
  addPatient(id, patient_name);
  tryToAddExistingPatient(id, patient_name);
  updatePatient(id, patient_name);
  verifyPatientExists(id, patient_name);
  deletePatient(id, patient_name);
  tryToDeleteANonExistingPatient(id, patient_name);
  verifyPatientDoesNotExist(id, patient_name);
});


// Story: crud:patient:nondet:4:3
// ---- crud:patient:nondet:4:3 ----
bthread("crud:patient:nondet:4:3", function () {
  let id = 232;
  let patient_name = "Name 232";
  addPatient(id, patient_name);
  tryToAddExistingPatient(id, patient_name);
  verifyPatientExists(id, patient_name);
  deletePatient(id, patient_name);
  tryToDeleteANonExistingPatient(id, patient_name);
  verifyPatientDoesNotExist(id, patient_name);
});


// Story: crud:patient:nondet:4:4
// ---- crud:patient:nondet:4:4 ----
bthread("crud:patient:nondet:4:4", function () {
  let id = 234;
  let patient_name = "Name 234";
  addPatient(id, patient_name);
  tryToAddExistingPatient(id, patient_name);
  deletePatient(id, patient_name);
  tryToDeleteANonExistingPatient(id, patient_name);
  verifyPatientDoesNotExist(id, patient_name);
});


// Story: crud:prescription:nondet:5:1
// ---- crud:prescription:nondet:5:1 ----
bthread("crud:prescription:nondet:5:1", function () {
  let id = 240;
  addPrescription(id);
  tryToAddExistingPrescription(id);
  verifyPrescriptionExists(id);
  updatePrescription(id);
  deletePrescription(id);
  tryToDeleteANonExistingPrescription(id);
  verifyPrescriptionDoesNotExist(id);
});


// Story: crud:prescription:nondet:5:2
// ---- crud:prescription:nondet:5:2 ----
bthread("crud:prescription:nondet:5:2", function () {
  let id = 241;
  addPrescription(id);
  tryToAddExistingPrescription(id);
  updatePrescription(id);
  verifyPrescriptionExists(id);
  deletePrescription(id);
  tryToDeleteANonExistingPrescription(id);
  verifyPrescriptionDoesNotExist(id);
});


// Story: crud:prescription:nondet:5:3
// ---- crud:prescription:nondet:5:3 ----
bthread("crud:prescription:nondet:5:3", function () {
  let id = 242;
  addPrescription(id);
  tryToAddExistingPrescription(id);
  verifyPrescriptionExists(id);
  deletePrescription(id);
  tryToDeleteANonExistingPrescription(id);
  verifyPrescriptionDoesNotExist(id);
});


// Story: crud:prescription:nondet:5:4
// ---- crud:prescription:nondet:5:4 ----
bthread("crud:prescription:nondet:5:4", function () {
  let id = 244;
  addPrescription(id);
  tryToAddExistingPrescription(id);
  deletePrescription(id);
  tryToDeleteANonExistingPrescription(id);
  verifyPrescriptionDoesNotExist(id);
});


// Story: crud:reset:nondet:6:1
// ---- crud:reset:nondet:6:1 ----
bthread("crud:reset:nondet:6:1", function () {
  let id = 250;
  addReset(id);
  tryToAddExistingReset(id);
  verifyResetExists(id);
  updateReset(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
});


// Story: crud:reset:nondet:6:2
// ---- crud:reset:nondet:6:2 ----
bthread("crud:reset:nondet:6:2", function () {
  let id = 251;
  addReset(id);
  tryToAddExistingReset(id);
  updateReset(id);
  verifyResetExists(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
});


// Story: crud:reset:nondet:6:3
// ---- crud:reset:nondet:6:3 ----
bthread("crud:reset:nondet:6:3", function () {
  let id = 252;
  addReset(id);
  tryToAddExistingReset(id);
  verifyResetExists(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
});


// Story: crud:reset:nondet:6:4
// ---- crud:reset:nondet:6:4 ----
bthread("crud:reset:nondet:6:4", function () {
  let id = 254;
  addReset(id);
  tryToAddExistingReset(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
});


// Story: crud:reset-all:nondet:7:1
// ---- crud:reset-all:nondet:7:1 ----
bthread("crud:reset-all:nondet:7:1", function () {
  let id = 260;
  addReset-all(id);
  tryToAddExistingReset-all(id);
  verifyReset-allExists(id);
  updateReset-all(id);
  deleteReset-all(id);
  tryToDeleteANonExistingReset-all(id);
  verifyReset-allDoesNotExist(id);
});


// Story: crud:reset-all:nondet:7:2
// ---- crud:reset-all:nondet:7:2 ----
bthread("crud:reset-all:nondet:7:2", function () {
  let id = 261;
  addReset-all(id);
  tryToAddExistingReset-all(id);
  updateReset-all(id);
  verifyReset-allExists(id);
  deleteReset-all(id);
  tryToDeleteANonExistingReset-all(id);
  verifyReset-allDoesNotExist(id);
});


// Story: crud:reset-all:nondet:7:3
// ---- crud:reset-all:nondet:7:3 ----
bthread("crud:reset-all:nondet:7:3", function () {
  let id = 262;
  addReset-all(id);
  tryToAddExistingReset-all(id);
  verifyReset-allExists(id);
  deleteReset-all(id);
  tryToDeleteANonExistingReset-all(id);
  verifyReset-allDoesNotExist(id);
});


// Story: crud:reset-all:nondet:7:4
// ---- crud:reset-all:nondet:7:4 ----
bthread("crud:reset-all:nondet:7:4", function () {
  let id = 264;
  addReset-all(id);
  tryToAddExistingReset-all(id);
  deleteReset-all(id);
  tryToDeleteANonExistingReset-all(id);
  verifyReset-allDoesNotExist(id);
});


// Story: crud:drug:nondet:negative:dup-add
bthread("crud:drug:nondet:negative:dup-add", function () {
  let drugId = 200;
  addDrug(drugId);
  verifyDrugExists(drugId);
  tryToAddExistingDrug(drugId);
  verifyDrugExists(drugId);
});

// Story: crud:drug:nondet:negative:delete-nonexistent
bthread("crud:drug:nondet:negative:delete-nonexistent", function () {
  let drugId = 201;
  tryToDeleteANonExistingDrug(drugId);
});

// Story: crud:drug:nondet:existing:update
bthread("crud:drug:nondet:existing:update", function () {
  // Wait for some existing drug to be added (from any other story)
  let ev = waitForAnyDrugAdded();
  let idField = "drugid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  // Ensure it really exists, then update (with all key fields)
  verifyDrugExists.apply(null, args);
  updateDrug.apply(null, args);
  verifyDrugExists.apply(null, args);
});

// Story: crud:drug:nondet:existing:dup-add
bthread("crud:drug:nondet:existing:dup-add", function () {
  // Wait for some existing drug to be added first
  let ev = waitForAnyDrugAdded();
  let idField = "drugid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  verifyDrugExists.apply(null, args);
  tryToAddExistingDrug.apply(null, args);
  verifyDrugExists.apply(null, args);
});

// Story: monitor:drug:add
bthread("monitor:drug:add", function () {
  while (true) {
    let ev = waitForAnyDrugAdded();
    let idField = "drugid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchDeleteDrug.apply(null, args), function () {
      verifyDrugExists.apply(null, args);
    });
  }
});

// Story: monitor:drug:delete
bthread("monitor:drug:delete", function () {
  while (true) {
    let ev = waitForAnyDrugDeleted();
    let idField = "drugid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchAddDrug.apply(null, args), function () {
      verifyDrugDoesNotExist.apply(null, args);
    });
  }
});

// Story: crud:inventory:nondet:negative:dup-add
bthread("crud:inventory:nondet:negative:dup-add", function () {
  let inventoryId = 200;
  addInventory(inventoryId);
  verifyInventoryExists(inventoryId);
  tryToAddExistingInventory(inventoryId);
  verifyInventoryExists(inventoryId);
});

// Story: crud:inventory:nondet:negative:delete-nonexistent
bthread("crud:inventory:nondet:negative:delete-nonexistent", function () {
  let inventoryId = 201;
  tryToDeleteANonExistingInventory(inventoryId);
});

// Story: crud:inventory:nondet:existing:update
bthread("crud:inventory:nondet:existing:update", function () {
  // Wait for some existing inventory to be added (from any other story)
  let ev = waitForAnyInventoryAdded();
  let idField = "inventoryid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  // Ensure it really exists, then update (with all key fields)
  verifyInventoryExists.apply(null, args);
  updateInventory.apply(null, args);
  verifyInventoryExists.apply(null, args);
});

// Story: crud:inventory:nondet:existing:dup-add
bthread("crud:inventory:nondet:existing:dup-add", function () {
  // Wait for some existing inventory to be added first
  let ev = waitForAnyInventoryAdded();
  let idField = "inventoryid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  verifyInventoryExists.apply(null, args);
  tryToAddExistingInventory.apply(null, args);
  verifyInventoryExists.apply(null, args);
});

// Story: monitor:inventory:add
bthread("monitor:inventory:add", function () {
  while (true) {
    let ev = waitForAnyInventoryAdded();
    let idField = "inventoryid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchDeleteInventory.apply(null, args), function () {
      verifyInventoryExists.apply(null, args);
    });
  }
});

// Story: monitor:inventory:delete
bthread("monitor:inventory:delete", function () {
  while (true) {
    let ev = waitForAnyInventoryDeleted();
    let idField = "inventoryid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchAddInventory.apply(null, args), function () {
      verifyInventoryDoesNotExist.apply(null, args);
    });
  }
});

// Story: crud:order:nondet:negative:dup-add
bthread("crud:order:nondet:negative:dup-add", function () {
  let orderId = 200;
  addOrder(orderId);
  verifyOrderExists(orderId);
  tryToAddExistingOrder(orderId);
  verifyOrderExists(orderId);
});

// Story: crud:order:nondet:negative:delete-nonexistent
bthread("crud:order:nondet:negative:delete-nonexistent", function () {
  let orderId = 201;
  tryToDeleteANonExistingOrder(orderId);
});

// Story: crud:order:nondet:existing:update
bthread("crud:order:nondet:existing:update", function () {
  // Wait for some existing order to be added (from any other story)
  let ev = waitForAnyOrderAdded();
  let idField = "orderid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  // Ensure it really exists, then update (with all key fields)
  verifyOrderExists.apply(null, args);
  updateOrder.apply(null, args);
  verifyOrderExists.apply(null, args);
});

// Story: crud:order:nondet:existing:dup-add
bthread("crud:order:nondet:existing:dup-add", function () {
  // Wait for some existing order to be added first
  let ev = waitForAnyOrderAdded();
  let idField = "orderid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  verifyOrderExists.apply(null, args);
  tryToAddExistingOrder.apply(null, args);
  verifyOrderExists.apply(null, args);
});

// Story: monitor:order:add
bthread("monitor:order:add", function () {
  while (true) {
    let ev = waitForAnyOrderAdded();
    let idField = "orderid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchDeleteOrder.apply(null, args), function () {
      verifyOrderExists.apply(null, args);
    });
  }
});

// Story: monitor:order:delete
bthread("monitor:order:delete", function () {
  while (true) {
    let ev = waitForAnyOrderDeleted();
    let idField = "orderid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchAddOrder.apply(null, args), function () {
      verifyOrderDoesNotExist.apply(null, args);
    });
  }
});

// Story: crud:patient:nondet:negative:dup-add
bthread("crud:patient:nondet:negative:dup-add", function () {
  let patientId = 200;
  addPatient(patientId);
  verifyPatientExists(patientId);
  tryToAddExistingPatient(patientId);
  verifyPatientExists(patientId);
});

// Story: crud:patient:nondet:negative:delete-nonexistent
bthread("crud:patient:nondet:negative:delete-nonexistent", function () {
  let patientId = 201;
  tryToDeleteANonExistingPatient(patientId);
});

// Story: crud:patient:nondet:existing:update
bthread("crud:patient:nondet:existing:update", function () {
  // Wait for some existing patient to be added (from any other story)
  let ev = waitForAnyPatientAdded();
  let idField = "patientid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  // Ensure it really exists, then update (with all key fields)
  verifyPatientExists.apply(null, args);
  updatePatient.apply(null, args);
  verifyPatientExists.apply(null, args);
});

// Story: crud:patient:nondet:existing:dup-add
bthread("crud:patient:nondet:existing:dup-add", function () {
  // Wait for some existing patient to be added first
  let ev = waitForAnyPatientAdded();
  let idField = "patientid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  verifyPatientExists.apply(null, args);
  tryToAddExistingPatient.apply(null, args);
  verifyPatientExists.apply(null, args);
});

// Story: monitor:patient:add
bthread("monitor:patient:add", function () {
  while (true) {
    let ev = waitForAnyPatientAdded();
    let idField = "patientid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchDeletePatient.apply(null, args), function () {
      verifyPatientExists.apply(null, args);
    });
  }
});

// Story: monitor:patient:delete
bthread("monitor:patient:delete", function () {
  while (true) {
    let ev = waitForAnyPatientDeleted();
    let idField = "patientid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchAddPatient.apply(null, args), function () {
      verifyPatientDoesNotExist.apply(null, args);
    });
  }
});

// Story: crud:prescription:nondet:negative:dup-add
bthread("crud:prescription:nondet:negative:dup-add", function () {
  let prescriptionId = 200;
  addPrescription(prescriptionId);
  verifyPrescriptionExists(prescriptionId);
  tryToAddExistingPrescription(prescriptionId);
  verifyPrescriptionExists(prescriptionId);
});

// Story: crud:prescription:nondet:negative:delete-nonexistent
bthread("crud:prescription:nondet:negative:delete-nonexistent", function () {
  let prescriptionId = 201;
  tryToDeleteANonExistingPrescription(prescriptionId);
});

// Story: crud:prescription:nondet:existing:update
bthread("crud:prescription:nondet:existing:update", function () {
  // Wait for some existing prescription to be added (from any other story)
  let ev = waitForAnyPrescriptionAdded();
  let idField = "prescriptionid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  // Ensure it really exists, then update (with all key fields)
  verifyPrescriptionExists.apply(null, args);
  updatePrescription.apply(null, args);
  verifyPrescriptionExists.apply(null, args);
});

// Story: crud:prescription:nondet:existing:dup-add
bthread("crud:prescription:nondet:existing:dup-add", function () {
  // Wait for some existing prescription to be added first
  let ev = waitForAnyPrescriptionAdded();
  let idField = "prescriptionid";
  let idValue = ev[idField];
  let args = Object.values(ev);

  verifyPrescriptionExists.apply(null, args);
  tryToAddExistingPrescription.apply(null, args);
  verifyPrescriptionExists.apply(null, args);
});

// Story: monitor:prescription:add
bthread("monitor:prescription:add", function () {
  while (true) {
    let ev = waitForAnyPrescriptionAdded();
    let idField = "prescriptionid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchDeletePrescription.apply(null, args), function () {
      verifyPrescriptionExists.apply(null, args);
    });
  }
});

// Story: monitor:prescription:delete
bthread("monitor:prescription:delete", function () {
  while (true) {
    let ev = waitForAnyPrescriptionDeleted();
    let idField = "prescriptionid";
    let idValue = ev[idField];
    let args = Object.values(ev);
    block(matchAddPrescription.apply(null, args), function () {
      verifyPrescriptionDoesNotExist.apply(null, args);
    });
  }
});

