// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

bp.registerBThread("Activity_basicCrud", function() {
  // Basic CRUD story for Activity
  addActivity(201, undefined, undefined, undefined, undefined);
  verifyActivityExists(201, undefined, undefined, undefined, undefined);
  deleteActivity(201, undefined, undefined, undefined, undefined);
});

bp.registerBThread("Preset_basicCrud", function() {
  // Basic CRUD story for Preset
  addPreset(201, undefined, undefined, undefined);
  verifyPresetExists(201, undefined, undefined, undefined);
  deletePreset(201, undefined, undefined, undefined);
});

bp.registerBThread("Collection_basicCrud", function() {
  // Basic CRUD story for Collection
  addCollection(201, "name_201");
  verifyCollectionExists(201, "name_201");
  deleteCollection(201, "name_201");
});

bp.registerBThread("Comment_basicCrud", function() {
  // Basic CRUD story for Comment
  addComment(201, undefined, undefined, undefined);
  verifyCommentExists(201, undefined, undefined, undefined);
  deleteComment(201, undefined, undefined, undefined);
});

bp.registerBThread("File_basicCrud", function() {
  // Basic CRUD story for File
  addFile(201, undefined, "name_201");
  verifyFileExists(201, undefined, "name_201");
  deleteFile(201, undefined, "name_201");
});

bp.registerBThread("User_basicCrud", function() {
  // Basic CRUD story for User
  addUser(201, undefined, "name_201", "name_201");
  verifyUserExists(201, undefined, "name_201", "name_201");
  deleteUser(201, undefined, "name_201", "name_201");
});

bp.registerBThread("Preset_duplicateAdd", function() {
  // Duplicate-add scenario for Preset
  addPreset(202, undefined, undefined, undefined);
  verifyPresetExists(202, undefined, undefined, undefined);
  addPreset(202, undefined, undefined, undefined);  // expected to fail or be blocked
});

bp.registerBThread("Collection_duplicateAdd", function() {
  // Duplicate-add scenario for Collection
  addCollection(202, "name_202");
  verifyCollectionExists(202, "name_202");
  addCollection(202, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("Comment_duplicateAdd", function() {
  // Duplicate-add scenario for Comment
  addComment(202, undefined, undefined, undefined);
  verifyCommentExists(202, undefined, undefined, undefined);
  addComment(202, undefined, undefined, undefined);  // expected to fail or be blocked
});

bp.registerBThread("File_duplicateAdd", function() {
  // Duplicate-add scenario for File
  addFile(202, undefined, "name_202");
  verifyFileExists(202, undefined, "name_202");
  addFile(202, undefined, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("User_duplicateAdd", function() {
  // Duplicate-add scenario for User
  addUser(202, undefined, "name_202", "name_202");
  verifyUserExists(202, undefined, "name_202", "name_202");
  addUser(202, undefined, "name_202", "name_202");  // expected to fail or be blocked
});

