// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=pharmacy  Provider=7_suts_llm_provider  Mode=?  Stories=28
// Source: artifacts/hls_nondet/7_suts_llm_provider/pharmacy/hls_gold.json
// ============================================================================
// ---- crud:drug:nondet:1:1 ----
bthread("crud:drug:nondet:1:1", function () {
  let id = 200;
  addDrug(id);
  tryToAddExistingDrug(id);
  verifyDrugExists(id);
  updateDrug(id);
  deleteDrug(id);
  tryToDeleteANonExistingDrug(id);
  verifyDrugDoesNotExist(id);
  
});

// ---- crud:drug:nondet:1:2 ----
bthread("crud:drug:nondet:1:2", function () {
  let id = 200;
  addDrug(id);
  tryToAddExistingDrug(id);
  updateDrug(id);
  verifyDrugExists(id);
  deleteDrug(id);
  tryToDeleteANonExistingDrug(id);
  verifyDrugDoesNotExist(id);
  
});

// ---- crud:drug:nondet:1:3 ----
bthread("crud:drug:nondet:1:3", function () {
  let id = 200;
  addDrug(id);
  tryToAddExistingDrug(id);
  verifyDrugExists(id);
  deleteDrug(id);
  tryToDeleteANonExistingDrug(id);
  verifyDrugDoesNotExist(id);
  
});

// ---- crud:drug:nondet:1:4 ----
bthread("crud:drug:nondet:1:4", function () {
  let id = 201;
  addDrug(id);
  tryToAddExistingDrug(id);
  deleteDrug(id);
  tryToDeleteANonExistingDrug(id);
  verifyDrugDoesNotExist(id);
  
});

// ---- crud:inventory:nondet:2:1 ----
bthread("crud:inventory:nondet:2:1", function () {
  let ndc = "ndc_201";
  addInventory(ndc);
  tryToAddExistingInventory(ndc);
  verifyInventoryExists(ndc);
  updateInventory(ndc);
  deleteInventory(ndc);
  tryToDeleteANonExistingInventory(ndc);
  verifyInventoryDoesNotExist(ndc);
  
});

// ---- crud:inventory:nondet:2:2 ----
bthread("crud:inventory:nondet:2:2", function () {
  let ndc = "ndc_201";
  addInventory(ndc);
  tryToAddExistingInventory(ndc);
  updateInventory(ndc);
  verifyInventoryExists(ndc);
  deleteInventory(ndc);
  tryToDeleteANonExistingInventory(ndc);
  verifyInventoryDoesNotExist(ndc);
  
});

// ---- crud:inventory:nondet:2:3 ----
bthread("crud:inventory:nondet:2:3", function () {
  let ndc = "ndc_201";
  addInventory(ndc);
  tryToAddExistingInventory(ndc);
  verifyInventoryExists(ndc);
  deleteInventory(ndc);
  tryToDeleteANonExistingInventory(ndc);
  verifyInventoryDoesNotExist(ndc);
  
});

// ---- crud:inventory:nondet:2:4 ----
bthread("crud:inventory:nondet:2:4", function () {
  let ndc = "ndc_202";
  addInventory(ndc);
  tryToAddExistingInventory(ndc);
  deleteInventory(ndc);
  tryToDeleteANonExistingInventory(ndc);
  verifyInventoryDoesNotExist(ndc);
  
});

// ---- crud:order:nondet:3:1 ----
bthread("crud:order:nondet:3:1", function () {
  let id = 202;
  addOrder(id);
  tryToAddExistingOrder(id);
  verifyOrderExists(id);
  updateOrder(id);
  deleteOrder(id);
  tryToDeleteANonExistingOrder(id);
  verifyOrderDoesNotExist(id);
  
});

// ---- crud:order:nondet:3:2 ----
bthread("crud:order:nondet:3:2", function () {
  let id = 202;
  addOrder(id);
  tryToAddExistingOrder(id);
  updateOrder(id);
  verifyOrderExists(id);
  deleteOrder(id);
  tryToDeleteANonExistingOrder(id);
  verifyOrderDoesNotExist(id);
  
});

// ---- crud:order:nondet:3:3 ----
bthread("crud:order:nondet:3:3", function () {
  let id = 202;
  addOrder(id);
  tryToAddExistingOrder(id);
  verifyOrderExists(id);
  deleteOrder(id);
  tryToDeleteANonExistingOrder(id);
  verifyOrderDoesNotExist(id);
  
});

// ---- crud:order:nondet:3:4 ----
bthread("crud:order:nondet:3:4", function () {
  let id = 203;
  addOrder(id);
  tryToAddExistingOrder(id);
  deleteOrder(id);
  tryToDeleteANonExistingOrder(id);
  verifyOrderDoesNotExist(id);
  
});

// ---- crud:patient:nondet:4:1 ----
bthread("crud:patient:nondet:4:1", function () {
  let id = 203;
  addPatient(id);
  tryToAddExistingPatient(id);
  verifyPatientExists(id);
  updatePatient(id);
  deletePatient(id);
  tryToDeleteANonExistingPatient(id);
  verifyPatientDoesNotExist(id);
  
});

// ---- crud:patient:nondet:4:2 ----
bthread("crud:patient:nondet:4:2", function () {
  let id = 203;
  addPatient(id);
  tryToAddExistingPatient(id);
  updatePatient(id);
  verifyPatientExists(id);
  deletePatient(id);
  tryToDeleteANonExistingPatient(id);
  verifyPatientDoesNotExist(id);
  
});

// ---- crud:patient:nondet:4:3 ----
bthread("crud:patient:nondet:4:3", function () {
  let id = 203;
  addPatient(id);
  tryToAddExistingPatient(id);
  verifyPatientExists(id);
  deletePatient(id);
  tryToDeleteANonExistingPatient(id);
  verifyPatientDoesNotExist(id);
  
});

// ---- crud:patient:nondet:4:4 ----
bthread("crud:patient:nondet:4:4", function () {
  let id = 204;
  addPatient(id);
  tryToAddExistingPatient(id);
  deletePatient(id);
  tryToDeleteANonExistingPatient(id);
  verifyPatientDoesNotExist(id);
  
});

// ---- crud:prescription:nondet:5:1 ----
bthread("crud:prescription:nondet:5:1", function () {
  let id = 204;
  addPrescription(id);
  tryToAddExistingPrescription(id);
  verifyPrescriptionExists(id);
  updatePrescription(id);
  deletePrescription(id);
  tryToDeleteANonExistingPrescription(id);
  verifyPrescriptionDoesNotExist(id);
  
});

// ---- crud:prescription:nondet:5:2 ----
bthread("crud:prescription:nondet:5:2", function () {
  let id = 204;
  addPrescription(id);
  tryToAddExistingPrescription(id);
  updatePrescription(id);
  verifyPrescriptionExists(id);
  deletePrescription(id);
  tryToDeleteANonExistingPrescription(id);
  verifyPrescriptionDoesNotExist(id);
  
});

// ---- crud:prescription:nondet:5:3 ----
bthread("crud:prescription:nondet:5:3", function () {
  let id = 204;
  addPrescription(id);
  tryToAddExistingPrescription(id);
  verifyPrescriptionExists(id);
  deletePrescription(id);
  tryToDeleteANonExistingPrescription(id);
  verifyPrescriptionDoesNotExist(id);
  
});

// ---- crud:prescription:nondet:5:4 ----
bthread("crud:prescription:nondet:5:4", function () {
  let id = 205;
  addPrescription(id);
  tryToAddExistingPrescription(id);
  deletePrescription(id);
  tryToDeleteANonExistingPrescription(id);
  verifyPrescriptionDoesNotExist(id);
  
});

// ---- crud:reset:nondet:6:1 ----
bthread("crud:reset:nondet:6:1", function () {
  let id = 205;
  addReset(id);
  tryToAddExistingReset(id);
  verifyResetExists(id);
  updateReset(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
  
});

// ---- crud:reset:nondet:6:2 ----
bthread("crud:reset:nondet:6:2", function () {
  let id = 205;
  addReset(id);
  tryToAddExistingReset(id);
  updateReset(id);
  verifyResetExists(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
  
});

// ---- crud:reset:nondet:6:3 ----
bthread("crud:reset:nondet:6:3", function () {
  let id = 205;
  addReset(id);
  tryToAddExistingReset(id);
  verifyResetExists(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
  
});

// ---- crud:reset:nondet:6:4 ----
bthread("crud:reset:nondet:6:4", function () {
  let id = 206;
  addReset(id);
  tryToAddExistingReset(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
  
});

// ---- crud:reset_all:nondet:7:1 ----
bthread("crud:reset_all:nondet:7:1", function () {
  let id = 206;
  addReset_all(id);
  tryToAddExistingReset_all(id);
  verifyReset_allExists(id);
  updateReset_all(id);
  deleteReset_all(id);
  tryToDeleteANonExistingReset_all(id);
  verifyReset_allDoesNotExist(id);
  
});

// ---- crud:reset_all:nondet:7:2 ----
bthread("crud:reset_all:nondet:7:2", function () {
  let id = 206;
  addReset_all(id);
  tryToAddExistingReset_all(id);
  updateReset_all(id);
  verifyReset_allExists(id);
  deleteReset_all(id);
  tryToDeleteANonExistingReset_all(id);
  verifyReset_allDoesNotExist(id);
  
});

// ---- crud:reset_all:nondet:7:3 ----
bthread("crud:reset_all:nondet:7:3", function () {
  let id = 206;
  addReset_all(id);
  tryToAddExistingReset_all(id);
  verifyReset_allExists(id);
  deleteReset_all(id);
  tryToDeleteANonExistingReset_all(id);
  verifyReset_allDoesNotExist(id);
  
});

// ---- crud:reset_all:nondet:7:4 ----
bthread("crud:reset_all:nondet:7:4", function () {
  let id = 207;
  addReset_all(id);
  tryToAddExistingReset_all(id);
  deleteReset_all(id);
  tryToDeleteANonExistingReset_all(id);
  verifyReset_allDoesNotExist(id);
  
});
