// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=trello  Provider=real_world_llm_provider  Mode=?  Stories=60
// Source: artifacts/hls_nondet/real_world_llm_provider/trello/hls_gold.json
// ============================================================================
// ---- crud:action:nondet:1:1 ----
bthread("crud:action:nondet:1:1", function () {
  let idAction = "idAction_200";
  let field = "field_200";
  addAction(idAction, field);
  tryToAddExistingAction(idAction, field);
  verifyActionExists(idAction, field);
  updateAction(idAction, field);
  deleteAction(idAction, field);
  tryToDeleteANonExistingAction(idAction, field);
  verifyActionDoesNotExist(idAction, field);
  
});

// ---- crud:action:nondet:1:2 ----
bthread("crud:action:nondet:1:2", function () {
  let idAction = "idAction_200";
  let field = "field_200";
  addAction(idAction, field);
  tryToAddExistingAction(idAction, field);
  updateAction(idAction, field);
  verifyActionExists(idAction, field);
  deleteAction(idAction, field);
  tryToDeleteANonExistingAction(idAction, field);
  verifyActionDoesNotExist(idAction, field);
  
});

// ---- crud:action:nondet:1:3 ----
bthread("crud:action:nondet:1:3", function () {
  let idAction = "idAction_200";
  let field = "field_200";
  addAction(idAction, field);
  tryToAddExistingAction(idAction, field);
  verifyActionExists(idAction, field);
  deleteAction(idAction, field);
  tryToDeleteANonExistingAction(idAction, field);
  verifyActionDoesNotExist(idAction, field);
  
});

// ---- crud:action:nondet:1:4 ----
bthread("crud:action:nondet:1:4", function () {
  let idAction = "idAction_201";
  let field = "field_201";
  addAction(idAction, field);
  tryToAddExistingAction(idAction, field);
  deleteAction(idAction, field);
  tryToDeleteANonExistingAction(idAction, field);
  verifyActionDoesNotExist(idAction, field);
  
});

// ---- crud:batch:nondet:2:1 ----
bthread("crud:batch:nondet:2:1", function () {
  let id = 201;
  addBatch(id);
  tryToAddExistingBatch(id);
  verifyBatchExists(id);
  updateBatch(id);
  deleteBatch(id);
  tryToDeleteANonExistingBatch(id);
  verifyBatchDoesNotExist(id);
  
});

// ---- crud:batch:nondet:2:2 ----
bthread("crud:batch:nondet:2:2", function () {
  let id = 201;
  addBatch(id);
  tryToAddExistingBatch(id);
  updateBatch(id);
  verifyBatchExists(id);
  deleteBatch(id);
  tryToDeleteANonExistingBatch(id);
  verifyBatchDoesNotExist(id);
  
});

// ---- crud:batch:nondet:2:3 ----
bthread("crud:batch:nondet:2:3", function () {
  let id = 201;
  addBatch(id);
  tryToAddExistingBatch(id);
  verifyBatchExists(id);
  deleteBatch(id);
  tryToDeleteANonExistingBatch(id);
  verifyBatchDoesNotExist(id);
  
});

// ---- crud:batch:nondet:2:4 ----
bthread("crud:batch:nondet:2:4", function () {
  let id = 202;
  addBatch(id);
  tryToAddExistingBatch(id);
  deleteBatch(id);
  tryToDeleteANonExistingBatch(id);
  verifyBatchDoesNotExist(id);
  
});

// ---- crud:board:nondet:3:1 ----
bthread("crud:board:nondet:3:1", function () {
  let idBoard = "idBoard_202";
  let filter = "filter_202";
  let idMember = "idMember_202";
  let field = "field_202";
  let idMembership = "idMembership_202";
  let idCard = "idCard_202";
  let idLabel = "idLabel_202";
  let powerUp = "powerUp_202";
  addBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  tryToAddExistingBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  verifyBoardExists(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  updateBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  deleteBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  tryToDeleteANonExistingBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  verifyBoardDoesNotExist(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  
});

// ---- crud:board:nondet:3:2 ----
bthread("crud:board:nondet:3:2", function () {
  let idBoard = "idBoard_202";
  let filter = "filter_202";
  let idMember = "idMember_202";
  let field = "field_202";
  let idMembership = "idMembership_202";
  let idCard = "idCard_202";
  let idLabel = "idLabel_202";
  let powerUp = "powerUp_202";
  addBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  tryToAddExistingBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  updateBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  verifyBoardExists(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  deleteBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  tryToDeleteANonExistingBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  verifyBoardDoesNotExist(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  
});

// ---- crud:board:nondet:3:3 ----
bthread("crud:board:nondet:3:3", function () {
  let idBoard = "idBoard_202";
  let filter = "filter_202";
  let idMember = "idMember_202";
  let field = "field_202";
  let idMembership = "idMembership_202";
  let idCard = "idCard_202";
  let idLabel = "idLabel_202";
  let powerUp = "powerUp_202";
  addBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  tryToAddExistingBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  verifyBoardExists(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  deleteBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  tryToDeleteANonExistingBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  verifyBoardDoesNotExist(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  
});

// ---- crud:board:nondet:3:4 ----
bthread("crud:board:nondet:3:4", function () {
  let idBoard = "idBoard_203";
  let filter = "filter_203";
  let idMember = "idMember_203";
  let field = "field_203";
  let idMembership = "idMembership_203";
  let idCard = "idCard_203";
  let idLabel = "idLabel_203";
  let powerUp = "powerUp_203";
  addBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  tryToAddExistingBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  deleteBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  tryToDeleteANonExistingBoard(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  verifyBoardDoesNotExist(idBoard, filter, idMember, field, idMembership, idCard, idLabel, powerUp);
  
});

// ---- crud:card:nondet:4:1 ----
bthread("crud:card:nondet:4:1", function () {
  let idCard = "idCard_203";
  let idChecklist = "idChecklist_203";
  let idCheckItem = "idCheckItem_203";
  let field = "field_203";
  let idSticker = "idSticker_203";
  let idAction = "idAction_203";
  let idAttachment = "idAttachment_203";
  let idMember = "idMember_203";
  let idChecklistCurrent = "idChecklistCurrent_203";
  let idLabel = "idLabel_203";
  let color = "color_203";
  addCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  tryToAddExistingCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  verifyCardExists(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  updateCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  deleteCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  tryToDeleteANonExistingCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  verifyCardDoesNotExist(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  
});

// ---- crud:card:nondet:4:2 ----
bthread("crud:card:nondet:4:2", function () {
  let idCard = "idCard_203";
  let idChecklist = "idChecklist_203";
  let idCheckItem = "idCheckItem_203";
  let field = "field_203";
  let idSticker = "idSticker_203";
  let idAction = "idAction_203";
  let idAttachment = "idAttachment_203";
  let idMember = "idMember_203";
  let idChecklistCurrent = "idChecklistCurrent_203";
  let idLabel = "idLabel_203";
  let color = "color_203";
  addCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  tryToAddExistingCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  updateCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  verifyCardExists(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  deleteCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  tryToDeleteANonExistingCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  verifyCardDoesNotExist(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  
});

// ---- crud:card:nondet:4:3 ----
bthread("crud:card:nondet:4:3", function () {
  let idCard = "idCard_203";
  let idChecklist = "idChecklist_203";
  let idCheckItem = "idCheckItem_203";
  let field = "field_203";
  let idSticker = "idSticker_203";
  let idAction = "idAction_203";
  let idAttachment = "idAttachment_203";
  let idMember = "idMember_203";
  let idChecklistCurrent = "idChecklistCurrent_203";
  let idLabel = "idLabel_203";
  let color = "color_203";
  addCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  tryToAddExistingCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  verifyCardExists(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  deleteCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  tryToDeleteANonExistingCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  verifyCardDoesNotExist(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  
});

// ---- crud:card:nondet:4:4 ----
bthread("crud:card:nondet:4:4", function () {
  let idCard = "idCard_204";
  let idChecklist = "idChecklist_204";
  let idCheckItem = "idCheckItem_204";
  let field = "field_204";
  let idSticker = "idSticker_204";
  let idAction = "idAction_204";
  let idAttachment = "idAttachment_204";
  let idMember = "idMember_204";
  let idChecklistCurrent = "idChecklistCurrent_204";
  let idLabel = "idLabel_204";
  let color = "color_204";
  addCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  tryToAddExistingCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  deleteCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  tryToDeleteANonExistingCard(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  verifyCardDoesNotExist(idCard, idChecklist, idCheckItem, field, idSticker, idAction, idAttachment, idMember, idChecklistCurrent, idLabel, color);
  
});

// ---- crud:checklist:nondet:5:1 ----
bthread("crud:checklist:nondet:5:1", function () {
  let idChecklist = "idChecklist_204";
  let field = "field_204";
  let idCheckItem = "idCheckItem_204";
  let filter = "filter_204";
  addChecklist(idChecklist, field, idCheckItem, filter);
  tryToAddExistingChecklist(idChecklist, field, idCheckItem, filter);
  verifyChecklistExists(idChecklist, field, idCheckItem, filter);
  updateChecklist(idChecklist, field, idCheckItem, filter);
  deleteChecklist(idChecklist, field, idCheckItem, filter);
  tryToDeleteANonExistingChecklist(idChecklist, field, idCheckItem, filter);
  verifyChecklistDoesNotExist(idChecklist, field, idCheckItem, filter);
  
});

// ---- crud:checklist:nondet:5:2 ----
bthread("crud:checklist:nondet:5:2", function () {
  let idChecklist = "idChecklist_204";
  let field = "field_204";
  let idCheckItem = "idCheckItem_204";
  let filter = "filter_204";
  addChecklist(idChecklist, field, idCheckItem, filter);
  tryToAddExistingChecklist(idChecklist, field, idCheckItem, filter);
  updateChecklist(idChecklist, field, idCheckItem, filter);
  verifyChecklistExists(idChecklist, field, idCheckItem, filter);
  deleteChecklist(idChecklist, field, idCheckItem, filter);
  tryToDeleteANonExistingChecklist(idChecklist, field, idCheckItem, filter);
  verifyChecklistDoesNotExist(idChecklist, field, idCheckItem, filter);
  
});

// ---- crud:checklist:nondet:5:3 ----
bthread("crud:checklist:nondet:5:3", function () {
  let idChecklist = "idChecklist_204";
  let field = "field_204";
  let idCheckItem = "idCheckItem_204";
  let filter = "filter_204";
  addChecklist(idChecklist, field, idCheckItem, filter);
  tryToAddExistingChecklist(idChecklist, field, idCheckItem, filter);
  verifyChecklistExists(idChecklist, field, idCheckItem, filter);
  deleteChecklist(idChecklist, field, idCheckItem, filter);
  tryToDeleteANonExistingChecklist(idChecklist, field, idCheckItem, filter);
  verifyChecklistDoesNotExist(idChecklist, field, idCheckItem, filter);
  
});

// ---- crud:checklist:nondet:5:4 ----
bthread("crud:checklist:nondet:5:4", function () {
  let idChecklist = "idChecklist_205";
  let field = "field_205";
  let idCheckItem = "idCheckItem_205";
  let filter = "filter_205";
  addChecklist(idChecklist, field, idCheckItem, filter);
  tryToAddExistingChecklist(idChecklist, field, idCheckItem, filter);
  deleteChecklist(idChecklist, field, idCheckItem, filter);
  tryToDeleteANonExistingChecklist(idChecklist, field, idCheckItem, filter);
  verifyChecklistDoesNotExist(idChecklist, field, idCheckItem, filter);
  
});

// ---- crud:label:nondet:6:1 ----
bthread("crud:label:nondet:6:1", function () {
  let idLabel = "idLabel_205";
  let field = "field_205";
  addLabel(idLabel, field);
  tryToAddExistingLabel(idLabel, field);
  verifyLabelExists(idLabel, field);
  updateLabel(idLabel, field);
  deleteLabel(idLabel, field);
  tryToDeleteANonExistingLabel(idLabel, field);
  verifyLabelDoesNotExist(idLabel, field);
  
});

// ---- crud:label:nondet:6:2 ----
bthread("crud:label:nondet:6:2", function () {
  let idLabel = "idLabel_205";
  let field = "field_205";
  addLabel(idLabel, field);
  tryToAddExistingLabel(idLabel, field);
  updateLabel(idLabel, field);
  verifyLabelExists(idLabel, field);
  deleteLabel(idLabel, field);
  tryToDeleteANonExistingLabel(idLabel, field);
  verifyLabelDoesNotExist(idLabel, field);
  
});

// ---- crud:label:nondet:6:3 ----
bthread("crud:label:nondet:6:3", function () {
  let idLabel = "idLabel_205";
  let field = "field_205";
  addLabel(idLabel, field);
  tryToAddExistingLabel(idLabel, field);
  verifyLabelExists(idLabel, field);
  deleteLabel(idLabel, field);
  tryToDeleteANonExistingLabel(idLabel, field);
  verifyLabelDoesNotExist(idLabel, field);
  
});

// ---- crud:label:nondet:6:4 ----
bthread("crud:label:nondet:6:4", function () {
  let idLabel = "idLabel_206";
  let field = "field_206";
  addLabel(idLabel, field);
  tryToAddExistingLabel(idLabel, field);
  deleteLabel(idLabel, field);
  tryToDeleteANonExistingLabel(idLabel, field);
  verifyLabelDoesNotExist(idLabel, field);
  
});

// ---- crud:list:nondet:7:1 ----
bthread("crud:list:nondet:7:1", function () {
  let idList = "idList_206";
  let field = "field_206";
  let filter = "filter_206";
  addList(idList, field, filter);
  tryToAddExistingList(idList, field, filter);
  verifyListExists(idList, field, filter);
  updateList(idList, field, filter);
  deleteList(idList, field, filter);
  tryToDeleteANonExistingList(idList, field, filter);
  verifyListDoesNotExist(idList, field, filter);
  
});

// ---- crud:list:nondet:7:2 ----
bthread("crud:list:nondet:7:2", function () {
  let idList = "idList_206";
  let field = "field_206";
  let filter = "filter_206";
  addList(idList, field, filter);
  tryToAddExistingList(idList, field, filter);
  updateList(idList, field, filter);
  verifyListExists(idList, field, filter);
  deleteList(idList, field, filter);
  tryToDeleteANonExistingList(idList, field, filter);
  verifyListDoesNotExist(idList, field, filter);
  
});

// ---- crud:list:nondet:7:3 ----
bthread("crud:list:nondet:7:3", function () {
  let idList = "idList_206";
  let field = "field_206";
  let filter = "filter_206";
  addList(idList, field, filter);
  tryToAddExistingList(idList, field, filter);
  verifyListExists(idList, field, filter);
  deleteList(idList, field, filter);
  tryToDeleteANonExistingList(idList, field, filter);
  verifyListDoesNotExist(idList, field, filter);
  
});

// ---- crud:list:nondet:7:4 ----
bthread("crud:list:nondet:7:4", function () {
  let idList = "idList_207";
  let field = "field_207";
  let filter = "filter_207";
  addList(idList, field, filter);
  tryToAddExistingList(idList, field, filter);
  deleteList(idList, field, filter);
  tryToDeleteANonExistingList(idList, field, filter);
  verifyListDoesNotExist(idList, field, filter);
  
});

// ---- crud:member:nondet:8:1 ----
bthread("crud:member:nondet:8:1", function () {
  let idMember = "idMember_207";
  let idBoardBackground = "idBoardBackground_207";
  let idSavedSearch = "idSavedSearch_207";
  let idBoardStar = "idBoardStar_207";
  let filter = "filter_207";
  let field = "field_207";
  let idCustomSticker = "idCustomSticker_207";
  let idCustomEmoji = "idCustomEmoji_207";
  addMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  tryToAddExistingMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  verifyMemberExists(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  updateMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  deleteMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  tryToDeleteANonExistingMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  verifyMemberDoesNotExist(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  
});

// ---- crud:member:nondet:8:2 ----
bthread("crud:member:nondet:8:2", function () {
  let idMember = "idMember_207";
  let idBoardBackground = "idBoardBackground_207";
  let idSavedSearch = "idSavedSearch_207";
  let idBoardStar = "idBoardStar_207";
  let filter = "filter_207";
  let field = "field_207";
  let idCustomSticker = "idCustomSticker_207";
  let idCustomEmoji = "idCustomEmoji_207";
  addMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  tryToAddExistingMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  updateMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  verifyMemberExists(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  deleteMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  tryToDeleteANonExistingMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  verifyMemberDoesNotExist(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  
});

// ---- crud:member:nondet:8:3 ----
bthread("crud:member:nondet:8:3", function () {
  let idMember = "idMember_207";
  let idBoardBackground = "idBoardBackground_207";
  let idSavedSearch = "idSavedSearch_207";
  let idBoardStar = "idBoardStar_207";
  let filter = "filter_207";
  let field = "field_207";
  let idCustomSticker = "idCustomSticker_207";
  let idCustomEmoji = "idCustomEmoji_207";
  addMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  tryToAddExistingMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  verifyMemberExists(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  deleteMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  tryToDeleteANonExistingMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  verifyMemberDoesNotExist(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  
});

// ---- crud:member:nondet:8:4 ----
bthread("crud:member:nondet:8:4", function () {
  let idMember = "idMember_208";
  let idBoardBackground = "idBoardBackground_208";
  let idSavedSearch = "idSavedSearch_208";
  let idBoardStar = "idBoardStar_208";
  let filter = "filter_208";
  let field = "field_208";
  let idCustomSticker = "idCustomSticker_208";
  let idCustomEmoji = "idCustomEmoji_208";
  addMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  tryToAddExistingMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  deleteMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  tryToDeleteANonExistingMember(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  verifyMemberDoesNotExist(idMember, idBoardBackground, idSavedSearch, idBoardStar, filter, field, idCustomSticker, idCustomEmoji);
  
});

// ---- crud:notification:nondet:9:1 ----
bthread("crud:notification:nondet:9:1", function () {
  let idNotification = "idNotification_208";
  let field = "field_208";
  addNotification(idNotification, field);
  tryToAddExistingNotification(idNotification, field);
  verifyNotificationExists(idNotification, field);
  updateNotification(idNotification, field);
  deleteNotification(idNotification, field);
  tryToDeleteANonExistingNotification(idNotification, field);
  verifyNotificationDoesNotExist(idNotification, field);
  
});

// ---- crud:notification:nondet:9:2 ----
bthread("crud:notification:nondet:9:2", function () {
  let idNotification = "idNotification_208";
  let field = "field_208";
  addNotification(idNotification, field);
  tryToAddExistingNotification(idNotification, field);
  updateNotification(idNotification, field);
  verifyNotificationExists(idNotification, field);
  deleteNotification(idNotification, field);
  tryToDeleteANonExistingNotification(idNotification, field);
  verifyNotificationDoesNotExist(idNotification, field);
  
});

// ---- crud:notification:nondet:9:3 ----
bthread("crud:notification:nondet:9:3", function () {
  let idNotification = "idNotification_208";
  let field = "field_208";
  addNotification(idNotification, field);
  tryToAddExistingNotification(idNotification, field);
  verifyNotificationExists(idNotification, field);
  deleteNotification(idNotification, field);
  tryToDeleteANonExistingNotification(idNotification, field);
  verifyNotificationDoesNotExist(idNotification, field);
  
});

// ---- crud:notification:nondet:9:4 ----
bthread("crud:notification:nondet:9:4", function () {
  let idNotification = "idNotification_209";
  let field = "field_209";
  addNotification(idNotification, field);
  tryToAddExistingNotification(idNotification, field);
  deleteNotification(idNotification, field);
  tryToDeleteANonExistingNotification(idNotification, field);
  verifyNotificationDoesNotExist(idNotification, field);
  
});

// ---- crud:organization:nondet:10:1 ----
bthread("crud:organization:nondet:10:1", function () {
  let idOrg = "idOrg_209";
  let idMember = "idMember_209";
  let filter = "filter_209";
  let field = "field_209";
  let idMembership = "idMembership_209";
  addOrganization(idOrg, idMember, filter, field, idMembership);
  tryToAddExistingOrganization(idOrg, idMember, filter, field, idMembership);
  verifyOrganizationExists(idOrg, idMember, filter, field, idMembership);
  updateOrganization(idOrg, idMember, filter, field, idMembership);
  deleteOrganization(idOrg, idMember, filter, field, idMembership);
  tryToDeleteANonExistingOrganization(idOrg, idMember, filter, field, idMembership);
  verifyOrganizationDoesNotExist(idOrg, idMember, filter, field, idMembership);
  
});

// ---- crud:organization:nondet:10:2 ----
bthread("crud:organization:nondet:10:2", function () {
  let idOrg = "idOrg_209";
  let idMember = "idMember_209";
  let filter = "filter_209";
  let field = "field_209";
  let idMembership = "idMembership_209";
  addOrganization(idOrg, idMember, filter, field, idMembership);
  tryToAddExistingOrganization(idOrg, idMember, filter, field, idMembership);
  updateOrganization(idOrg, idMember, filter, field, idMembership);
  verifyOrganizationExists(idOrg, idMember, filter, field, idMembership);
  deleteOrganization(idOrg, idMember, filter, field, idMembership);
  tryToDeleteANonExistingOrganization(idOrg, idMember, filter, field, idMembership);
  verifyOrganizationDoesNotExist(idOrg, idMember, filter, field, idMembership);
  
});

// ---- crud:organization:nondet:10:3 ----
bthread("crud:organization:nondet:10:3", function () {
  let idOrg = "idOrg_209";
  let idMember = "idMember_209";
  let filter = "filter_209";
  let field = "field_209";
  let idMembership = "idMembership_209";
  addOrganization(idOrg, idMember, filter, field, idMembership);
  tryToAddExistingOrganization(idOrg, idMember, filter, field, idMembership);
  verifyOrganizationExists(idOrg, idMember, filter, field, idMembership);
  deleteOrganization(idOrg, idMember, filter, field, idMembership);
  tryToDeleteANonExistingOrganization(idOrg, idMember, filter, field, idMembership);
  verifyOrganizationDoesNotExist(idOrg, idMember, filter, field, idMembership);
  
});

// ---- crud:organization:nondet:10:4 ----
bthread("crud:organization:nondet:10:4", function () {
  let idOrg = "idOrg_210";
  let idMember = "idMember_210";
  let filter = "filter_210";
  let field = "field_210";
  let idMembership = "idMembership_210";
  addOrganization(idOrg, idMember, filter, field, idMembership);
  tryToAddExistingOrganization(idOrg, idMember, filter, field, idMembership);
  deleteOrganization(idOrg, idMember, filter, field, idMembership);
  tryToDeleteANonExistingOrganization(idOrg, idMember, filter, field, idMembership);
  verifyOrganizationDoesNotExist(idOrg, idMember, filter, field, idMembership);
  
});

// ---- crud:search:nondet:11:1 ----
bthread("crud:search:nondet:11:1", function () {
  let id = 210;
  addSearch(id);
  tryToAddExistingSearch(id);
  verifySearchExists(id);
  updateSearch(id);
  deleteSearch(id);
  tryToDeleteANonExistingSearch(id);
  verifySearchDoesNotExist(id);
  
});

// ---- crud:search:nondet:11:2 ----
bthread("crud:search:nondet:11:2", function () {
  let id = 210;
  addSearch(id);
  tryToAddExistingSearch(id);
  updateSearch(id);
  verifySearchExists(id);
  deleteSearch(id);
  tryToDeleteANonExistingSearch(id);
  verifySearchDoesNotExist(id);
  
});

// ---- crud:search:nondet:11:3 ----
bthread("crud:search:nondet:11:3", function () {
  let id = 210;
  addSearch(id);
  tryToAddExistingSearch(id);
  verifySearchExists(id);
  deleteSearch(id);
  tryToDeleteANonExistingSearch(id);
  verifySearchDoesNotExist(id);
  
});

// ---- crud:search:nondet:11:4 ----
bthread("crud:search:nondet:11:4", function () {
  let id = 211;
  addSearch(id);
  tryToAddExistingSearch(id);
  deleteSearch(id);
  tryToDeleteANonExistingSearch(id);
  verifySearchDoesNotExist(id);
  
});

// ---- crud:session:nondet:12:1 ----
bthread("crud:session:nondet:12:1", function () {
  let idSession = "idSession_211";
  addSession(idSession);
  tryToAddExistingSession(idSession);
  verifySessionExists(idSession);
  updateSession(idSession);
  deleteSession(idSession);
  tryToDeleteANonExistingSession(idSession);
  verifySessionDoesNotExist(idSession);
  
});

// ---- crud:session:nondet:12:2 ----
bthread("crud:session:nondet:12:2", function () {
  let idSession = "idSession_211";
  addSession(idSession);
  tryToAddExistingSession(idSession);
  updateSession(idSession);
  verifySessionExists(idSession);
  deleteSession(idSession);
  tryToDeleteANonExistingSession(idSession);
  verifySessionDoesNotExist(idSession);
  
});

// ---- crud:session:nondet:12:3 ----
bthread("crud:session:nondet:12:3", function () {
  let idSession = "idSession_211";
  addSession(idSession);
  tryToAddExistingSession(idSession);
  verifySessionExists(idSession);
  deleteSession(idSession);
  tryToDeleteANonExistingSession(idSession);
  verifySessionDoesNotExist(idSession);
  
});

// ---- crud:session:nondet:12:4 ----
bthread("crud:session:nondet:12:4", function () {
  let idSession = "idSession_212";
  addSession(idSession);
  tryToAddExistingSession(idSession);
  deleteSession(idSession);
  tryToDeleteANonExistingSession(idSession);
  verifySessionDoesNotExist(idSession);
  
});

// ---- crud:token:nondet:13:1 ----
bthread("crud:token:nondet:13:1", function () {
  let token = "token_212";
  let field = "field_212";
  let idWebhook = "idWebhook_212";
  addToken(token, field, idWebhook);
  tryToAddExistingToken(token, field, idWebhook);
  verifyTokenExists(token, field, idWebhook);
  updateToken(token, field, idWebhook);
  deleteToken(token, field, idWebhook);
  tryToDeleteANonExistingToken(token, field, idWebhook);
  verifyTokenDoesNotExist(token, field, idWebhook);
  
});

// ---- crud:token:nondet:13:2 ----
bthread("crud:token:nondet:13:2", function () {
  let token = "token_212";
  let field = "field_212";
  let idWebhook = "idWebhook_212";
  addToken(token, field, idWebhook);
  tryToAddExistingToken(token, field, idWebhook);
  updateToken(token, field, idWebhook);
  verifyTokenExists(token, field, idWebhook);
  deleteToken(token, field, idWebhook);
  tryToDeleteANonExistingToken(token, field, idWebhook);
  verifyTokenDoesNotExist(token, field, idWebhook);
  
});

// ---- crud:token:nondet:13:3 ----
bthread("crud:token:nondet:13:3", function () {
  let token = "token_212";
  let field = "field_212";
  let idWebhook = "idWebhook_212";
  addToken(token, field, idWebhook);
  tryToAddExistingToken(token, field, idWebhook);
  verifyTokenExists(token, field, idWebhook);
  deleteToken(token, field, idWebhook);
  tryToDeleteANonExistingToken(token, field, idWebhook);
  verifyTokenDoesNotExist(token, field, idWebhook);
  
});

// ---- crud:token:nondet:13:4 ----
bthread("crud:token:nondet:13:4", function () {
  let token = "token_213";
  let field = "field_213";
  let idWebhook = "idWebhook_213";
  addToken(token, field, idWebhook);
  tryToAddExistingToken(token, field, idWebhook);
  deleteToken(token, field, idWebhook);
  tryToDeleteANonExistingToken(token, field, idWebhook);
  verifyTokenDoesNotExist(token, field, idWebhook);
  
});

// ---- crud:type:nondet:14:1 ----
bthread("crud:type:nondet:14:1", function () {
  let id = 213;
  addType(id);
  tryToAddExistingType(id);
  verifyTypeExists(id);
  updateType(id);
  deleteType(id);
  tryToDeleteANonExistingType(id);
  verifyTypeDoesNotExist(id);
  
});

// ---- crud:type:nondet:14:2 ----
bthread("crud:type:nondet:14:2", function () {
  let id = 213;
  addType(id);
  tryToAddExistingType(id);
  updateType(id);
  verifyTypeExists(id);
  deleteType(id);
  tryToDeleteANonExistingType(id);
  verifyTypeDoesNotExist(id);
  
});

// ---- crud:type:nondet:14:3 ----
bthread("crud:type:nondet:14:3", function () {
  let id = 213;
  addType(id);
  tryToAddExistingType(id);
  verifyTypeExists(id);
  deleteType(id);
  tryToDeleteANonExistingType(id);
  verifyTypeDoesNotExist(id);
  
});

// ---- crud:type:nondet:14:4 ----
bthread("crud:type:nondet:14:4", function () {
  let id = 214;
  addType(id);
  tryToAddExistingType(id);
  deleteType(id);
  tryToDeleteANonExistingType(id);
  verifyTypeDoesNotExist(id);
  
});

// ---- crud:webhook:nondet:15:1 ----
bthread("crud:webhook:nondet:15:1", function () {
  let idWebhook = "idWebhook_214";
  let field = "field_214";
  addWebhook(idWebhook, field);
  tryToAddExistingWebhook(idWebhook, field);
  verifyWebhookExists(idWebhook, field);
  updateWebhook(idWebhook, field);
  deleteWebhook(idWebhook, field);
  tryToDeleteANonExistingWebhook(idWebhook, field);
  verifyWebhookDoesNotExist(idWebhook, field);
  
});

// ---- crud:webhook:nondet:15:2 ----
bthread("crud:webhook:nondet:15:2", function () {
  let idWebhook = "idWebhook_214";
  let field = "field_214";
  addWebhook(idWebhook, field);
  tryToAddExistingWebhook(idWebhook, field);
  updateWebhook(idWebhook, field);
  verifyWebhookExists(idWebhook, field);
  deleteWebhook(idWebhook, field);
  tryToDeleteANonExistingWebhook(idWebhook, field);
  verifyWebhookDoesNotExist(idWebhook, field);
  
});

// ---- crud:webhook:nondet:15:3 ----
bthread("crud:webhook:nondet:15:3", function () {
  let idWebhook = "idWebhook_214";
  let field = "field_214";
  addWebhook(idWebhook, field);
  tryToAddExistingWebhook(idWebhook, field);
  verifyWebhookExists(idWebhook, field);
  deleteWebhook(idWebhook, field);
  tryToDeleteANonExistingWebhook(idWebhook, field);
  verifyWebhookDoesNotExist(idWebhook, field);
  
});

// ---- crud:webhook:nondet:15:4 ----
bthread("crud:webhook:nondet:15:4", function () {
  let idWebhook = "idWebhook_215";
  let field = "field_215";
  addWebhook(idWebhook, field);
  tryToAddExistingWebhook(idWebhook, field);
  deleteWebhook(idWebhook, field);
  tryToDeleteANonExistingWebhook(idWebhook, field);
  verifyWebhookDoesNotExist(idWebhook, field);
  
});
