// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=factory  Provider=7_suts_llm_provider  Mode=?  Stories=5
// Source: artifacts/hls_det/7_suts_llm_provider/factory/hls_gold.json
// ============================================================================
bthread("CRUD_machine", function() {
});

bthread("CRUD_maintenance_ticket", function() {
});

bthread("CRUD_reset", function() {
});

bthread("CRUD_sensor_reading", function() {
});

bthread("CRUD_workorder", function() {
});
