// Auto-generated NEGATIVE (Fuzzing) stories for garage
//@provengo summon rest

bthread("fuzz:Chains:active_InvalidType", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let bad_active = "NOT_A_BOOL";
  verifyChainsRejects(bad_active, chainId_valid, description_valid, hqAddress_valid, name_valid, supportEmail_valid);
});
bthread("fuzz:Chains:chainId_InvalidType", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let bad_chainId = 12345;
  verifyChainsRejects(active_valid, bad_chainId, description_valid, hqAddress_valid, name_valid, supportEmail_valid);
});
bthread("fuzz:Chains:description_InvalidType", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let bad_description = 12345;
  verifyChainsRejects(active_valid, chainId_valid, bad_description, hqAddress_valid, name_valid, supportEmail_valid);
});
bthread("fuzz:Chains:hqAddress_InvalidType", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let bad_hqAddress = 12345;
  verifyChainsRejects(active_valid, chainId_valid, description_valid, bad_hqAddress, name_valid, supportEmail_valid);
});
bthread("fuzz:Chains:name_InvalidType", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let bad_name = 12345;
  verifyChainsRejects(active_valid, chainId_valid, description_valid, hqAddress_valid, bad_name, supportEmail_valid);
});
bthread("fuzz:Chains:supportEmail_InvalidType", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let bad_supportEmail = 12345;
  verifyChainsRejects(active_valid, chainId_valid, description_valid, hqAddress_valid, name_valid, bad_supportEmail);
});
bthread("fuzz:Chains:active_Missing", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let missing_active = undefined;
  verifyChainsRejects(missing_active, chainId_valid, description_valid, hqAddress_valid, name_valid, supportEmail_valid);
});
bthread("fuzz:Chains:chainId_Missing", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let missing_chainId = undefined;
  verifyChainsRejects(active_valid, missing_chainId, description_valid, hqAddress_valid, name_valid, supportEmail_valid);
});
bthread("fuzz:Chains:hqAddress_Missing", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let missing_hqAddress = undefined;
  verifyChainsRejects(active_valid, chainId_valid, description_valid, missing_hqAddress, name_valid, supportEmail_valid);
});
bthread("fuzz:Chains:name_Missing", function () {
  let active_valid = true;
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let hqAddress_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let supportEmail_valid = "supportEmail_valid_" + Math.floor(Math.random()*1000);
  let missing_name = undefined;
  verifyChainsRejects(active_valid, chainId_valid, description_valid, hqAddress_valid, missing_name, supportEmail_valid);
});
bthread("fuzz:Customers:customerId_InvalidType", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let bad_customerId = 12345;
  verifyCustomersRejects(bad_customerId, description_valid, email_valid, fullName_valid, name_valid, phone_valid, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:description_InvalidType", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let bad_description = 12345;
  verifyCustomersRejects(customerId_valid, bad_description, email_valid, fullName_valid, name_valid, phone_valid, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:email_InvalidType", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let bad_email = 12345;
  verifyCustomersRejects(customerId_valid, description_valid, bad_email, fullName_valid, name_valid, phone_valid, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:fullName_InvalidType", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let bad_fullName = 12345;
  verifyCustomersRejects(customerId_valid, description_valid, email_valid, bad_fullName, name_valid, phone_valid, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:name_InvalidType", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let bad_name = 12345;
  verifyCustomersRejects(customerId_valid, description_valid, email_valid, fullName_valid, bad_name, phone_valid, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:phone_InvalidType", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let bad_phone = 12345;
  verifyCustomersRejects(customerId_valid, description_valid, email_valid, fullName_valid, name_valid, bad_phone, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:preferredGarageId_InvalidType", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let bad_preferredGarageId = 12345;
  verifyCustomersRejects(customerId_valid, description_valid, email_valid, fullName_valid, name_valid, phone_valid, bad_preferredGarageId, type_valid);
});
bthread("fuzz:Customers:type_InvalidType", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let bad_type = 12345;
  verifyCustomersRejects(customerId_valid, description_valid, email_valid, fullName_valid, name_valid, phone_valid, preferredGarageId_valid, bad_type);
});
bthread("fuzz:Customers:customerId_Missing", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let missing_customerId = undefined;
  verifyCustomersRejects(missing_customerId, description_valid, email_valid, fullName_valid, name_valid, phone_valid, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:email_Missing", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let missing_email = undefined;
  verifyCustomersRejects(customerId_valid, description_valid, missing_email, fullName_valid, name_valid, phone_valid, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:fullName_Missing", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let missing_fullName = undefined;
  verifyCustomersRejects(customerId_valid, description_valid, email_valid, missing_fullName, name_valid, phone_valid, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:phone_Missing", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let missing_phone = undefined;
  verifyCustomersRejects(customerId_valid, description_valid, email_valid, fullName_valid, name_valid, missing_phone, preferredGarageId_valid, type_valid);
});
bthread("fuzz:Customers:type_Missing", function () {
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let email_valid = "email_valid_" + Math.floor(Math.random()*1000);
  let fullName_valid = "fullName_valid_" + Math.floor(Math.random()*1000);
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let preferredGarageId_valid = "preferredGarageId_valid_" + Math.floor(Math.random()*1000);
  let type_valid = "type_valid_" + Math.floor(Math.random()*1000);
  let missing_type = undefined;
  verifyCustomersRejects(customerId_valid, description_valid, email_valid, fullName_valid, name_valid, phone_valid, preferredGarageId_valid, missing_type);
});
bthread("fuzz:Garages:active_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_active = "NOT_A_BOOL";
  verifyGaragesRejects(bad_active, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:address_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_address = 12345;
  verifyGaragesRejects(active_valid, bad_address, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:bayCount_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_bayCount = "INVALID_STRING";
  verifyGaragesRejects(active_valid, address_valid, bad_bayCount, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:capacity_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_capacity = "INVALID_STRING";
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, bad_capacity, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:chainId_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_chainId = 12345;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, bad_chainId, description_valid, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:description_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_description = 12345;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, bad_description, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:garageId_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_garageId = 12345;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, bad_garageId, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:location_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_location = 12345;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, bad_location, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:name_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_name = 12345;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, bad_name, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:phone_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_phone = 12345;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, bad_phone, servicesOffered_valid);
});
bthread("fuzz:Garages:servicesOffered_InvalidType", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let bad_servicesOffered = "NOT_AN_ARRAY";
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, phone_valid, bad_servicesOffered);
});
bthread("fuzz:Garages:active_Missing", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let missing_active = undefined;
  verifyGaragesRejects(missing_active, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:address_Missing", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let missing_address = undefined;
  verifyGaragesRejects(active_valid, missing_address, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:chainId_Missing", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let missing_chainId = undefined;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, missing_chainId, description_valid, garageId_valid, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:garageId_Missing", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let missing_garageId = undefined;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, missing_garageId, location_valid, name_valid, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:name_Missing", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let missing_name = undefined;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, missing_name, phone_valid, servicesOffered_valid);
});
bthread("fuzz:Garages:phone_Missing", function () {
  let active_valid = true;
  let address_valid = {};
  let bayCount_valid = Math.floor(Math.random() * 1000000);
  let capacity_valid = Math.floor(Math.random() * 1000000);
  let chainId_valid = "chainId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let location_valid = {};
  let name_valid = "name_valid_" + Math.floor(Math.random()*1000);
  let phone_valid = "phone_valid_" + Math.floor(Math.random()*1000);
  let servicesOffered_valid = [];
  let missing_phone = undefined;
  verifyGaragesRejects(active_valid, address_valid, bayCount_valid, capacity_valid, chainId_valid, description_valid, garageId_valid, location_valid, name_valid, missing_phone, servicesOffered_valid);
});
bthread("fuzz:Cars:color_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_color = 12345;
  verifyCarsRejects(bad_color, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, model_valid, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:description_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_description = 12345;
  verifyCarsRejects(color_valid, bad_description, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, model_valid, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:homeGarageId_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_homeGarageId = 12345;
  verifyCarsRejects(color_valid, description_valid, bad_homeGarageId, licensePlate_valid, make_valid, mileage_valid, model_valid, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:licensePlate_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_licensePlate = 12345;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, bad_licensePlate, make_valid, mileage_valid, model_valid, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:make_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_make = 12345;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, bad_make, mileage_valid, model_valid, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:mileage_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_mileage = "INVALID_STRING";
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, bad_mileage, model_valid, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:model_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_model = 12345;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, bad_model, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:ownerCustomerId_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_ownerCustomerId = 12345;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, model_valid, bad_ownerCustomerId, vin_valid, year_valid);
});
bthread("fuzz:Cars:vin_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_vin = 12345;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, model_valid, ownerCustomerId_valid, bad_vin, year_valid);
});
bthread("fuzz:Cars:year_InvalidType", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let bad_year = "INVALID_STRING";
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, model_valid, ownerCustomerId_valid, vin_valid, bad_year);
});
bthread("fuzz:Cars:make_Missing", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let missing_make = undefined;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, missing_make, mileage_valid, model_valid, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:mileage_Missing", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let missing_mileage = undefined;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, missing_mileage, model_valid, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:model_Missing", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let missing_model = undefined;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, missing_model, ownerCustomerId_valid, vin_valid, year_valid);
});
bthread("fuzz:Cars:ownerCustomerId_Missing", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let missing_ownerCustomerId = undefined;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, model_valid, missing_ownerCustomerId, vin_valid, year_valid);
});
bthread("fuzz:Cars:vin_Missing", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let missing_vin = undefined;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, model_valid, ownerCustomerId_valid, missing_vin, year_valid);
});
bthread("fuzz:Cars:year_Missing", function () {
  let color_valid = "color_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let homeGarageId_valid = "homeGarageId_valid_" + Math.floor(Math.random()*1000);
  let licensePlate_valid = "licensePlate_valid_" + Math.floor(Math.random()*1000);
  let make_valid = "make_valid_" + Math.floor(Math.random()*1000);
  let mileage_valid = Math.floor(Math.random() * 1000000);
  let model_valid = "model_valid_" + Math.floor(Math.random()*1000);
  let ownerCustomerId_valid = "ownerCustomerId_valid_" + Math.floor(Math.random()*1000);
  let vin_valid = "vin_valid_" + Math.floor(Math.random()*1000);
  let year_valid = Math.floor(Math.random() * 1000000);
  let missing_year = undefined;
  verifyCarsRejects(color_valid, description_valid, homeGarageId_valid, licensePlate_valid, make_valid, mileage_valid, model_valid, ownerCustomerId_valid, vin_valid, missing_year);
});
bthread("fuzz:PeriodicMaintenance:carVin_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_carVin = 12345;
  verifyPeriodicMaintenanceRejects(bad_carVin, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:description_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_description = 12345;
  verifyPeriodicMaintenanceRejects(carVin_valid, bad_description, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:garageId_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_garageId = 12345;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, bad_garageId, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:intervalKm_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_intervalKm = "INVALID_STRING";
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, bad_intervalKm, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:intervalMonths_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_intervalMonths = "INVALID_STRING";
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, bad_intervalMonths, planType_valid, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:planType_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_planType = 12345;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, bad_planType, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:pmId_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_pmId = 12345;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, bad_pmId, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:schedule_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_schedule = 12345;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, bad_schedule, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:status_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_status = 12345;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, bad_status, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:tasks_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let bad_tasks = "NOT_AN_ARRAY";
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, status_valid, bad_tasks);
});
bthread("fuzz:PeriodicMaintenance:carVin_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let missing_carVin = undefined;
  verifyPeriodicMaintenanceRejects(missing_carVin, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:garageId_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let missing_garageId = undefined;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, missing_garageId, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:planType_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let missing_planType = undefined;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, missing_planType, pmId_valid, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:pmId_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let missing_pmId = undefined;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, missing_pmId, schedule_valid, status_valid, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:status_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let missing_status = undefined;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, missing_status, tasks_valid);
});
bthread("fuzz:PeriodicMaintenance:tasks_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let intervalKm_valid = Math.floor(Math.random() * 1000000);
  let intervalMonths_valid = Math.floor(Math.random() * 1000000);
  let planType_valid = "planType_valid_" + Math.floor(Math.random()*1000);
  let pmId_valid = "pmId_valid_" + Math.floor(Math.random()*1000);
  let schedule_valid = {};
  let status_valid = "open";
  let tasks_valid = [];
  let missing_tasks = undefined;
  verifyPeriodicMaintenanceRejects(carVin_valid, description_valid, garageId_valid, intervalKm_valid, intervalMonths_valid, planType_valid, pmId_valid, schedule_valid, status_valid, missing_tasks);
});
bthread("fuzz:RepairOrders:carVin_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let bad_carVin = 12345;
  verifyRepairOrdersRejects(bad_carVin, complaint_valid, customerId_valid, description_valid, garageId_valid, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:complaint_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let bad_complaint = 12345;
  verifyRepairOrdersRejects(carVin_valid, bad_complaint, customerId_valid, description_valid, garageId_valid, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:customerId_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let bad_customerId = 12345;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, bad_customerId, description_valid, garageId_valid, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:description_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let bad_description = 12345;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, customerId_valid, bad_description, garageId_valid, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:garageId_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let bad_garageId = 12345;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, customerId_valid, description_valid, bad_garageId, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:roId_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let bad_roId = 12345;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, customerId_valid, description_valid, garageId_valid, bad_roId, status_valid);
});
bthread("fuzz:RepairOrders:status_InvalidType", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let bad_status = 12345;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, customerId_valid, description_valid, garageId_valid, roId_valid, bad_status);
});
bthread("fuzz:RepairOrders:carVin_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let missing_carVin = undefined;
  verifyRepairOrdersRejects(missing_carVin, complaint_valid, customerId_valid, description_valid, garageId_valid, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:complaint_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let missing_complaint = undefined;
  verifyRepairOrdersRejects(carVin_valid, missing_complaint, customerId_valid, description_valid, garageId_valid, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:customerId_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let missing_customerId = undefined;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, missing_customerId, description_valid, garageId_valid, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:garageId_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let missing_garageId = undefined;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, customerId_valid, description_valid, missing_garageId, roId_valid, status_valid);
});
bthread("fuzz:RepairOrders:roId_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let missing_roId = undefined;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, customerId_valid, description_valid, garageId_valid, missing_roId, status_valid);
});
bthread("fuzz:RepairOrders:status_Missing", function () {
  let carVin_valid = "carVin_valid_" + Math.floor(Math.random()*1000);
  let complaint_valid = "complaint_valid_" + Math.floor(Math.random()*1000);
  let customerId_valid = "customerId_valid_" + Math.floor(Math.random()*1000);
  let description_valid = "description_valid_" + Math.floor(Math.random()*1000);
  let garageId_valid = "garageId_valid_" + Math.floor(Math.random()*1000);
  let roId_valid = "roId_valid_" + Math.floor(Math.random()*1000);
  let status_valid = "open";
  let missing_status = undefined;
  verifyRepairOrdersRejects(carVin_valid, complaint_valid, customerId_valid, description_valid, garageId_valid, roId_valid, missing_status);
});