// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

bp.registerBThread("Chain_basicCrud", function() {
  // Basic CRUD story for Chain
  addChain(undefined, "name_201", undefined, undefined, undefined);
  verifyChainExists(undefined, "name_201", undefined, undefined, undefined);
  deleteChain(undefined, "name_201", undefined, undefined, undefined);
});

bp.registerBThread("Garage_basicCrud", function() {
  // Basic CRUD story for Garage
  addGarage(undefined, undefined, "name_201", undefined, undefined, undefined, undefined, undefined);
  verifyGarageExists(undefined, undefined, "name_201", undefined, undefined, undefined, undefined, undefined);
  deleteGarage(undefined, undefined, "name_201", undefined, undefined, undefined, undefined, undefined);
});

bp.registerBThread("Customer_basicCrud", function() {
  // Basic CRUD story for Customer
  addCustomer(undefined, undefined, undefined, undefined, undefined, undefined);
  verifyCustomerExists(undefined, undefined, undefined, undefined, undefined, undefined);
  deleteCustomer(undefined, undefined, undefined, undefined, undefined, undefined);
});

bp.registerBThread("Car_basicCrud", function() {
  // Basic CRUD story for Car
  addCar(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  verifyCarExists(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  deleteCar(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
});

bp.registerBThread("PeriodicMaintenance_basicCrud", function() {
  // Basic CRUD story for PeriodicMaintenance
  addPeriodicMaintenance(undefined, undefined, undefined, undefined, undefined, undefined);
  verifyPeriodicMaintenanceExists(undefined, undefined, undefined, undefined, undefined, undefined);
  deletePeriodicMaintenance(undefined, undefined, undefined, undefined, undefined, undefined);
});

bp.registerBThread("RepairOrder_basicCrud", function() {
  // Basic CRUD story for RepairOrder
  addRepairOrder(undefined, undefined, undefined, undefined, undefined, undefined);
  verifyRepairOrderExists(undefined, undefined, undefined, undefined, undefined, undefined);
  deleteRepairOrder(undefined, undefined, undefined, undefined, undefined, undefined);
});

bp.registerBThread("Chain_duplicateAdd", function() {
  // Duplicate-add scenario for Chain
  addChain(undefined, "name_202", undefined, undefined, undefined);
  verifyChainExists(undefined, "name_202", undefined, undefined, undefined);
  addChain(undefined, "name_202", undefined, undefined, undefined);  // expected to fail or be blocked
});

bp.registerBThread("Garage_duplicateAdd", function() {
  // Duplicate-add scenario for Garage
  addGarage(undefined, undefined, "name_202", undefined, undefined, undefined, undefined, undefined);
  verifyGarageExists(undefined, undefined, "name_202", undefined, undefined, undefined, undefined, undefined);
  addGarage(undefined, undefined, "name_202", undefined, undefined, undefined, undefined, undefined);  // expected to fail or be blocked
});

bp.registerBThread("Customer_duplicateAdd", function() {
  // Duplicate-add scenario for Customer
  addCustomer(undefined, undefined, undefined, undefined, undefined, undefined);
  verifyCustomerExists(undefined, undefined, undefined, undefined, undefined, undefined);
  addCustomer(undefined, undefined, undefined, undefined, undefined, undefined);  // expected to fail or be blocked
});

bp.registerBThread("Car_duplicateAdd", function() {
  // Duplicate-add scenario for Car
  addCar(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  verifyCarExists(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  addCar(undefined, undefined, undefined, undefined, undefined, undefined, undefined);  // expected to fail or be blocked
});

bp.registerBThread("PeriodicMaintenance_duplicateAdd", function() {
  // Duplicate-add scenario for PeriodicMaintenance
  addPeriodicMaintenance(undefined, undefined, undefined, undefined, undefined, undefined);
  verifyPeriodicMaintenanceExists(undefined, undefined, undefined, undefined, undefined, undefined);
  addPeriodicMaintenance(undefined, undefined, undefined, undefined, undefined, undefined);  // expected to fail or be blocked
});

bp.registerBThread("RepairOrder_duplicateAdd", function() {
  // Duplicate-add scenario for RepairOrder
  addRepairOrder(undefined, undefined, undefined, undefined, undefined, undefined);
  verifyRepairOrderExists(undefined, undefined, undefined, undefined, undefined, undefined);
  addRepairOrder(undefined, undefined, undefined, undefined, undefined, undefined);  // expected to fail or be blocked
});

