// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=config_control  Provider=7_suts_llm_provider  Mode=?  Stories=6
// Source: artifacts/hls_det/7_suts_llm_provider/config_control/hls_gold.json
// ============================================================================
bthread("CRUD_app", function() {
});

bthread("CRUD_config", function() {
});

bthread("CRUD_env", function() {
});

bthread("CRUD_policy", function() {
});

bthread("CRUD_releas", function() {
});

bthread("CRUD_reset", function() {
});
