// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=zulip  Provider=real_world_llm_provider  Mode=?  Stories=75
// Source: artifacts/hls_det/real_world_llm_provider/zulip/hls_gold.json
// ============================================================================
bthread("CRUD_alert_word", function() {
});

bthread("CRUD_android_gcm_reg_id", function() {
});

bthread("CRUD_apns_device_token", function() {
});

bthread("CRUD_attachment", function() {
});

bthread("CRUD_bigbluebutton", function() {
});

bthread("CRUD_call", function() {
});

bthread("CRUD_channel", function() {
});

bthread("CRUD_channel_folder", function() {
});

bthread("CRUD_consent", function() {
});

bthread("CRUD_create", function() {
});

bthread("CRUD_deactivate", function() {
});

bthread("CRUD_default_stream", function() {
});

bthread("CRUD_delete_topic", function() {
});

bthread("CRUD_dev_fetch_api_key", function() {
});

bthread("CRUD_draft", function() {
});

bthread("CRUD_e2ee", function() {
});

bthread("CRUD_email_addres", function() {
});

bthread("CRUD_emoji", function() {
});

bthread("CRUD_event", function() {
});

bthread("CRUD_export", function() {
});

bthread("CRUD_fetch_api_key", function() {
});

bthread("CRUD_filter", function() {
});

bthread("CRUD_flag", function() {
});

bthread("CRUD_get_stream_id", function() {
});

bthread("CRUD_history", function() {
});

bthread("CRUD_invite", function() {
});

bthread("CRUD_linkifier", function() {
});

bthread("CRUD_mark_all_as_read", function() {
});

bthread("CRUD_mark_stream_as_read", function() {
});

bthread("CRUD_mark_topic_as_read", function() {
});

bthread("CRUD_matches_narrow", function() {
});

bthread("CRUD_me", function() {
});

bthread("CRUD_member", function() {
});

bthread("CRUD_message", function() {
});

bthread("CRUD_mobile_push", function() {
});

bthread("CRUD_multiuse", function() {
});

bthread("CRUD_muted_topic", function() {
});

bthread("CRUD_muted_user", function() {
});

bthread("CRUD_narrow", function() {
});

bthread("CRUD_navigation_view", function() {
});

bthread("CRUD_playground", function() {
});

bthread("CRUD_presence", function() {
});

bthread("CRUD_profile_field", function() {
});

bthread("CRUD_property", function() {
});

bthread("CRUD_push", function() {
});

bthread("CRUD_reaction", function() {
});

bthread("CRUD_reactivate", function() {
});

bthread("CRUD_read_receipt", function() {
});

bthread("CRUD_real_time", function() {
});

bthread("CRUD_realm", function() {
});

bthread("CRUD_register", function() {
});

bthread("CRUD_reminder", function() {
});

bthread("CRUD_remote", function() {
});

bthread("CRUD_render", function() {
});

bthread("CRUD_report", function() {
});

bthread("CRUD_resend", function() {
});

bthread("CRUD_rest_error_handling", function() {
});

bthread("CRUD_saved_snippet", function() {
});

bthread("CRUD_scheduled_message", function() {
});

bthread("CRUD_server_setting", function() {
});

bthread("CRUD_setting", function() {
});

bthread("CRUD_statu", function() {
});

bthread("CRUD_stream", function() {
});

bthread("CRUD_subgroup", function() {
});

bthread("CRUD_subscription", function() {
});

bthread("CRUD_test_notification", function() {
});

bthread("CRUD_test_welcome_bot_custom_message", function() {
});

bthread("CRUD_topic", function() {
});

bthread("CRUD_typing", function() {
});

bthread("CRUD_user", function() {
});

bthread("CRUD_user_group", function() {
});

bthread("CRUD_user_settings_default", function() {
});

bthread("CRUD_user_topic", function() {
});

bthread("CRUD_user_upload", function() {
});

bthread("CRUD_zulip_outgoing_webhook", function() {
});
