// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=keycloak_admin  Provider=real_world_llm_provider  Mode=?  Stories=8
// Source: artifacts/hls_nondet/real_world_llm_provider/keycloak_admin/hls_gold.json
// ============================================================================
// ---- crud:root:nondet:1:1 ----
bthread("crud:root:nondet:1:1", function () {
  let id = 200;
  addRoot(id);
  tryToAddExistingRoot(id);
  verifyRootExists(id);
  updateRoot(id);
  deleteRoot(id);
  tryToDeleteANonExistingRoot(id);
  verifyRootDoesNotExist(id);
  
});

// ---- crud:root:nondet:1:2 ----
bthread("crud:root:nondet:1:2", function () {
  let id = 200;
  addRoot(id);
  tryToAddExistingRoot(id);
  updateRoot(id);
  verifyRootExists(id);
  deleteRoot(id);
  tryToDeleteANonExistingRoot(id);
  verifyRootDoesNotExist(id);
  
});

// ---- crud:root:nondet:1:3 ----
bthread("crud:root:nondet:1:3", function () {
  let id = 200;
  addRoot(id);
  tryToAddExistingRoot(id);
  verifyRootExists(id);
  deleteRoot(id);
  tryToDeleteANonExistingRoot(id);
  verifyRootDoesNotExist(id);
  
});

// ---- crud:root:nondet:1:4 ----
bthread("crud:root:nondet:1:4", function () {
  let id = 201;
  addRoot(id);
  tryToAddExistingRoot(id);
  deleteRoot(id);
  tryToDeleteANonExistingRoot(id);
  verifyRootDoesNotExist(id);
  
});

// ---- crud:{realm}:nondet:2:1 ----
bthread("crud:{realm}:nondet:2:1", function () {
  let realm = "realm_201";
  let id = 201;
  let client = "client_201";
  let role-name = "role-name_201";
  let alias = "alias_201";
  let role-id = 201;
  let id1 = "id1_201";
  let id2 = "id2_201";
  let clientScopeId = 201;
  let executionId = 201;
  let attr = "attr_201";
  let locale = "locale_201";
  let flowAlias = "flowAlias_201";
  let clientUuid = 201;
  let groupId = 201;
  let credentialId = 201;
  let protocol = "protocol_201";
  let key = "key_201";
  let userId = 201;
  let providerId = 201;
  let roleContainerId = 201;
  let provider = "provider_201";
  let node = "node_201";
  let path = "path_201";
  let provider_id = 201;
  let session = "session_201";
  let newPreviousCredentialId = 201;
  add{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  tryToAddExisting{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  verify{realm}Exists(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  update{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  delete{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  tryToDeleteANonExisting{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  verify{realm}DoesNotExist(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  
});

// ---- crud:{realm}:nondet:2:2 ----
bthread("crud:{realm}:nondet:2:2", function () {
  let realm = "realm_201";
  let id = 201;
  let client = "client_201";
  let role-name = "role-name_201";
  let alias = "alias_201";
  let role-id = 201;
  let id1 = "id1_201";
  let id2 = "id2_201";
  let clientScopeId = 201;
  let executionId = 201;
  let attr = "attr_201";
  let locale = "locale_201";
  let flowAlias = "flowAlias_201";
  let clientUuid = 201;
  let groupId = 201;
  let credentialId = 201;
  let protocol = "protocol_201";
  let key = "key_201";
  let userId = 201;
  let providerId = 201;
  let roleContainerId = 201;
  let provider = "provider_201";
  let node = "node_201";
  let path = "path_201";
  let provider_id = 201;
  let session = "session_201";
  let newPreviousCredentialId = 201;
  add{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  tryToAddExisting{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  update{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  verify{realm}Exists(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  delete{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  tryToDeleteANonExisting{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  verify{realm}DoesNotExist(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  
});

// ---- crud:{realm}:nondet:2:3 ----
bthread("crud:{realm}:nondet:2:3", function () {
  let realm = "realm_201";
  let id = 201;
  let client = "client_201";
  let role-name = "role-name_201";
  let alias = "alias_201";
  let role-id = 201;
  let id1 = "id1_201";
  let id2 = "id2_201";
  let clientScopeId = 201;
  let executionId = 201;
  let attr = "attr_201";
  let locale = "locale_201";
  let flowAlias = "flowAlias_201";
  let clientUuid = 201;
  let groupId = 201;
  let credentialId = 201;
  let protocol = "protocol_201";
  let key = "key_201";
  let userId = 201;
  let providerId = 201;
  let roleContainerId = 201;
  let provider = "provider_201";
  let node = "node_201";
  let path = "path_201";
  let provider_id = 201;
  let session = "session_201";
  let newPreviousCredentialId = 201;
  add{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  tryToAddExisting{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  verify{realm}Exists(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  delete{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  tryToDeleteANonExisting{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  verify{realm}DoesNotExist(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  
});

// ---- crud:{realm}:nondet:2:4 ----
bthread("crud:{realm}:nondet:2:4", function () {
  let realm = "realm_202";
  let id = 202;
  let client = "client_202";
  let role-name = "role-name_202";
  let alias = "alias_202";
  let role-id = 202;
  let id1 = "id1_202";
  let id2 = "id2_202";
  let clientScopeId = 202;
  let executionId = 202;
  let attr = "attr_202";
  let locale = "locale_202";
  let flowAlias = "flowAlias_202";
  let clientUuid = 202;
  let groupId = 202;
  let credentialId = 202;
  let protocol = "protocol_202";
  let key = "key_202";
  let userId = 202;
  let providerId = 202;
  let roleContainerId = 202;
  let provider = "provider_202";
  let node = "node_202";
  let path = "path_202";
  let provider_id = 202;
  let session = "session_202";
  let newPreviousCredentialId = 202;
  add{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  tryToAddExisting{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  delete{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  tryToDeleteANonExisting{realm}(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  verify{realm}DoesNotExist(realm, id, client, role-name, alias, role-id, id1, id2, clientScopeId, executionId, attr, locale, flowAlias, clientUuid, groupId, credentialId, protocol, key, userId, providerId, roleContainerId, provider, node, path, provider_id, session, newPreviousCredentialId);
  
});
