// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=factory  Provider=7_suts_llm_provider  Mode=?  Stories=20
// Source: artifacts/hls_nondet/7_suts_llm_provider/factory/hls_gold.json
// ============================================================================
// ---- crud:machine:nondet:1:1 ----
bthread("crud:machine:nondet:1:1", function () {
  let id = 200;
  addMachine(id);
  tryToAddExistingMachine(id);
  verifyMachineExists(id);
  updateMachine(id);
  deleteMachine(id);
  tryToDeleteANonExistingMachine(id);
  verifyMachineDoesNotExist(id);
  
});

// ---- crud:machine:nondet:1:2 ----
bthread("crud:machine:nondet:1:2", function () {
  let id = 200;
  addMachine(id);
  tryToAddExistingMachine(id);
  updateMachine(id);
  verifyMachineExists(id);
  deleteMachine(id);
  tryToDeleteANonExistingMachine(id);
  verifyMachineDoesNotExist(id);
  
});

// ---- crud:machine:nondet:1:3 ----
bthread("crud:machine:nondet:1:3", function () {
  let id = 200;
  addMachine(id);
  tryToAddExistingMachine(id);
  verifyMachineExists(id);
  deleteMachine(id);
  tryToDeleteANonExistingMachine(id);
  verifyMachineDoesNotExist(id);
  
});

// ---- crud:machine:nondet:1:4 ----
bthread("crud:machine:nondet:1:4", function () {
  let id = 201;
  addMachine(id);
  tryToAddExistingMachine(id);
  deleteMachine(id);
  tryToDeleteANonExistingMachine(id);
  verifyMachineDoesNotExist(id);
  
});

// ---- crud:maintenance_ticket:nondet:2:1 ----
bthread("crud:maintenance_ticket:nondet:2:1", function () {
  let id = 201;
  addMaintenance_ticket(id);
  tryToAddExistingMaintenance_ticket(id);
  verifyMaintenance_ticketExists(id);
  updateMaintenance_ticket(id);
  deleteMaintenance_ticket(id);
  tryToDeleteANonExistingMaintenance_ticket(id);
  verifyMaintenance_ticketDoesNotExist(id);
  
});

// ---- crud:maintenance_ticket:nondet:2:2 ----
bthread("crud:maintenance_ticket:nondet:2:2", function () {
  let id = 201;
  addMaintenance_ticket(id);
  tryToAddExistingMaintenance_ticket(id);
  updateMaintenance_ticket(id);
  verifyMaintenance_ticketExists(id);
  deleteMaintenance_ticket(id);
  tryToDeleteANonExistingMaintenance_ticket(id);
  verifyMaintenance_ticketDoesNotExist(id);
  
});

// ---- crud:maintenance_ticket:nondet:2:3 ----
bthread("crud:maintenance_ticket:nondet:2:3", function () {
  let id = 201;
  addMaintenance_ticket(id);
  tryToAddExistingMaintenance_ticket(id);
  verifyMaintenance_ticketExists(id);
  deleteMaintenance_ticket(id);
  tryToDeleteANonExistingMaintenance_ticket(id);
  verifyMaintenance_ticketDoesNotExist(id);
  
});

// ---- crud:maintenance_ticket:nondet:2:4 ----
bthread("crud:maintenance_ticket:nondet:2:4", function () {
  let id = 202;
  addMaintenance_ticket(id);
  tryToAddExistingMaintenance_ticket(id);
  deleteMaintenance_ticket(id);
  tryToDeleteANonExistingMaintenance_ticket(id);
  verifyMaintenance_ticketDoesNotExist(id);
  
});

// ---- crud:reset:nondet:3:1 ----
bthread("crud:reset:nondet:3:1", function () {
  let id = 202;
  addReset(id);
  tryToAddExistingReset(id);
  verifyResetExists(id);
  updateReset(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
  
});

// ---- crud:reset:nondet:3:2 ----
bthread("crud:reset:nondet:3:2", function () {
  let id = 202;
  addReset(id);
  tryToAddExistingReset(id);
  updateReset(id);
  verifyResetExists(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
  
});

// ---- crud:reset:nondet:3:3 ----
bthread("crud:reset:nondet:3:3", function () {
  let id = 202;
  addReset(id);
  tryToAddExistingReset(id);
  verifyResetExists(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
  
});

// ---- crud:reset:nondet:3:4 ----
bthread("crud:reset:nondet:3:4", function () {
  let id = 203;
  addReset(id);
  tryToAddExistingReset(id);
  deleteReset(id);
  tryToDeleteANonExistingReset(id);
  verifyResetDoesNotExist(id);
  
});

// ---- crud:sensor_reading:nondet:4:1 ----
bthread("crud:sensor_reading:nondet:4:1", function () {
  let id = 203;
  addSensor_reading(id);
  tryToAddExistingSensor_reading(id);
  verifySensor_readingExists(id);
  updateSensor_reading(id);
  deleteSensor_reading(id);
  tryToDeleteANonExistingSensor_reading(id);
  verifySensor_readingDoesNotExist(id);
  
});

// ---- crud:sensor_reading:nondet:4:2 ----
bthread("crud:sensor_reading:nondet:4:2", function () {
  let id = 203;
  addSensor_reading(id);
  tryToAddExistingSensor_reading(id);
  updateSensor_reading(id);
  verifySensor_readingExists(id);
  deleteSensor_reading(id);
  tryToDeleteANonExistingSensor_reading(id);
  verifySensor_readingDoesNotExist(id);
  
});

// ---- crud:sensor_reading:nondet:4:3 ----
bthread("crud:sensor_reading:nondet:4:3", function () {
  let id = 203;
  addSensor_reading(id);
  tryToAddExistingSensor_reading(id);
  verifySensor_readingExists(id);
  deleteSensor_reading(id);
  tryToDeleteANonExistingSensor_reading(id);
  verifySensor_readingDoesNotExist(id);
  
});

// ---- crud:sensor_reading:nondet:4:4 ----
bthread("crud:sensor_reading:nondet:4:4", function () {
  let id = 204;
  addSensor_reading(id);
  tryToAddExistingSensor_reading(id);
  deleteSensor_reading(id);
  tryToDeleteANonExistingSensor_reading(id);
  verifySensor_readingDoesNotExist(id);
  
});

// ---- crud:workorder:nondet:5:1 ----
bthread("crud:workorder:nondet:5:1", function () {
  let id = 204;
  addWorkorder(id);
  tryToAddExistingWorkorder(id);
  verifyWorkorderExists(id);
  updateWorkorder(id);
  deleteWorkorder(id);
  tryToDeleteANonExistingWorkorder(id);
  verifyWorkorderDoesNotExist(id);
  
});

// ---- crud:workorder:nondet:5:2 ----
bthread("crud:workorder:nondet:5:2", function () {
  let id = 204;
  addWorkorder(id);
  tryToAddExistingWorkorder(id);
  updateWorkorder(id);
  verifyWorkorderExists(id);
  deleteWorkorder(id);
  tryToDeleteANonExistingWorkorder(id);
  verifyWorkorderDoesNotExist(id);
  
});

// ---- crud:workorder:nondet:5:3 ----
bthread("crud:workorder:nondet:5:3", function () {
  let id = 204;
  addWorkorder(id);
  tryToAddExistingWorkorder(id);
  verifyWorkorderExists(id);
  deleteWorkorder(id);
  tryToDeleteANonExistingWorkorder(id);
  verifyWorkorderDoesNotExist(id);
  
});

// ---- crud:workorder:nondet:5:4 ----
bthread("crud:workorder:nondet:5:4", function () {
  let id = 205;
  addWorkorder(id);
  tryToAddExistingWorkorder(id);
  deleteWorkorder(id);
  tryToDeleteANonExistingWorkorder(id);
  verifyWorkorderDoesNotExist(id);
  
});
