// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

bp.registerBThread("Patient_basicCrud", function() {
  // Basic CRUD story for Patient
  addPatient(201, "name_201");
  verifyPatientExists(201, "name_201");
  deletePatient(201, "name_201");
});

bp.registerBThread("Drug_basicCrud", function() {
  // Basic CRUD story for Drug
  addDrug(201, "name_201");
  verifyDrugExists(201, "name_201");
  deleteDrug(201, "name_201");
});

bp.registerBThread("Prescription_basicCrud", function() {
  // Basic CRUD story for Prescription
  addPrescription(201, undefined);
  verifyPrescriptionExists(201, undefined);
  deletePrescription(201, undefined);
});

bp.registerBThread("Order_basicCrud", function() {
  // Basic CRUD story for Order
  addOrder(201, undefined);
  verifyOrderExists(201, undefined);
  deleteOrder(201, undefined);
});

bp.registerBThread("Patient_duplicateAdd", function() {
  // Duplicate-add scenario for Patient
  addPatient(202, "name_202");
  verifyPatientExists(202, "name_202");
  addPatient(202, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("Drug_duplicateAdd", function() {
  // Duplicate-add scenario for Drug
  addDrug(202, "name_202");
  verifyDrugExists(202, "name_202");
  addDrug(202, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("Prescription_duplicateAdd", function() {
  // Duplicate-add scenario for Prescription
  addPrescription(202, undefined);
  verifyPrescriptionExists(202, undefined);
  addPrescription(202, undefined);  // expected to fail or be blocked
});

bp.registerBThread("Order_duplicateAdd", function() {
  // Duplicate-add scenario for Order
  addOrder(202, undefined);
  verifyOrderExists(202, undefined);
  addOrder(202, undefined);  // expected to fail or be blocked
});

