// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=directus  Provider=real_world_llm_provider  Mode=?  Stories=96
// Source: artifacts/hls_nondet/real_world_llm_provider/directus/hls_gold.json
// ============================================================================
// ---- crud:activity:nondet:1:1 ----
bthread("crud:activity:nondet:1:1", function () {
  let id = 200;
  addActivity(id);
  tryToAddExistingActivity(id);
  verifyActivityExists(id);
  updateActivity(id);
  deleteActivity(id);
  tryToDeleteANonExistingActivity(id);
  verifyActivityDoesNotExist(id);
  
});

// ---- crud:activity:nondet:1:2 ----
bthread("crud:activity:nondet:1:2", function () {
  let id = 200;
  addActivity(id);
  tryToAddExistingActivity(id);
  updateActivity(id);
  verifyActivityExists(id);
  deleteActivity(id);
  tryToDeleteANonExistingActivity(id);
  verifyActivityDoesNotExist(id);
  
});

// ---- crud:activity:nondet:1:3 ----
bthread("crud:activity:nondet:1:3", function () {
  let id = 200;
  addActivity(id);
  tryToAddExistingActivity(id);
  verifyActivityExists(id);
  deleteActivity(id);
  tryToDeleteANonExistingActivity(id);
  verifyActivityDoesNotExist(id);
  
});

// ---- crud:activity:nondet:1:4 ----
bthread("crud:activity:nondet:1:4", function () {
  let id = 201;
  addActivity(id);
  tryToAddExistingActivity(id);
  deleteActivity(id);
  tryToDeleteANonExistingActivity(id);
  verifyActivityDoesNotExist(id);
  
});

// ---- crud:asset:nondet:2:1 ----
bthread("crud:asset:nondet:2:1", function () {
  let id = 201;
  addAsset(id);
  tryToAddExistingAsset(id);
  verifyAssetExists(id);
  updateAsset(id);
  deleteAsset(id);
  tryToDeleteANonExistingAsset(id);
  verifyAssetDoesNotExist(id);
  
});

// ---- crud:asset:nondet:2:2 ----
bthread("crud:asset:nondet:2:2", function () {
  let id = 201;
  addAsset(id);
  tryToAddExistingAsset(id);
  updateAsset(id);
  verifyAssetExists(id);
  deleteAsset(id);
  tryToDeleteANonExistingAsset(id);
  verifyAssetDoesNotExist(id);
  
});

// ---- crud:asset:nondet:2:3 ----
bthread("crud:asset:nondet:2:3", function () {
  let id = 201;
  addAsset(id);
  tryToAddExistingAsset(id);
  verifyAssetExists(id);
  deleteAsset(id);
  tryToDeleteANonExistingAsset(id);
  verifyAssetDoesNotExist(id);
  
});

// ---- crud:asset:nondet:2:4 ----
bthread("crud:asset:nondet:2:4", function () {
  let id = 202;
  addAsset(id);
  tryToAddExistingAsset(id);
  deleteAsset(id);
  tryToDeleteANonExistingAsset(id);
  verifyAssetDoesNotExist(id);
  
});

// ---- crud:auth:nondet:3:1 ----
bthread("crud:auth:nondet:3:1", function () {
  let provider = "provider_202";
  addAuth(provider);
  tryToAddExistingAuth(provider);
  verifyAuthExists(provider);
  updateAuth(provider);
  deleteAuth(provider);
  tryToDeleteANonExistingAuth(provider);
  verifyAuthDoesNotExist(provider);
  
});

// ---- crud:auth:nondet:3:2 ----
bthread("crud:auth:nondet:3:2", function () {
  let provider = "provider_202";
  addAuth(provider);
  tryToAddExistingAuth(provider);
  updateAuth(provider);
  verifyAuthExists(provider);
  deleteAuth(provider);
  tryToDeleteANonExistingAuth(provider);
  verifyAuthDoesNotExist(provider);
  
});

// ---- crud:auth:nondet:3:3 ----
bthread("crud:auth:nondet:3:3", function () {
  let provider = "provider_202";
  addAuth(provider);
  tryToAddExistingAuth(provider);
  verifyAuthExists(provider);
  deleteAuth(provider);
  tryToDeleteANonExistingAuth(provider);
  verifyAuthDoesNotExist(provider);
  
});

// ---- crud:auth:nondet:3:4 ----
bthread("crud:auth:nondet:3:4", function () {
  let provider = "provider_203";
  addAuth(provider);
  tryToAddExistingAuth(provider);
  deleteAuth(provider);
  tryToDeleteANonExistingAuth(provider);
  verifyAuthDoesNotExist(provider);
  
});

// ---- crud:collection:nondet:4:1 ----
bthread("crud:collection:nondet:4:1", function () {
  let id = 203;
  addCollection(id);
  tryToAddExistingCollection(id);
  verifyCollectionExists(id);
  updateCollection(id);
  deleteCollection(id);
  tryToDeleteANonExistingCollection(id);
  verifyCollectionDoesNotExist(id);
  
});

// ---- crud:collection:nondet:4:2 ----
bthread("crud:collection:nondet:4:2", function () {
  let id = 203;
  addCollection(id);
  tryToAddExistingCollection(id);
  updateCollection(id);
  verifyCollectionExists(id);
  deleteCollection(id);
  tryToDeleteANonExistingCollection(id);
  verifyCollectionDoesNotExist(id);
  
});

// ---- crud:collection:nondet:4:3 ----
bthread("crud:collection:nondet:4:3", function () {
  let id = 203;
  addCollection(id);
  tryToAddExistingCollection(id);
  verifyCollectionExists(id);
  deleteCollection(id);
  tryToDeleteANonExistingCollection(id);
  verifyCollectionDoesNotExist(id);
  
});

// ---- crud:collection:nondet:4:4 ----
bthread("crud:collection:nondet:4:4", function () {
  let id = 204;
  addCollection(id);
  tryToAddExistingCollection(id);
  deleteCollection(id);
  tryToDeleteANonExistingCollection(id);
  verifyCollectionDoesNotExist(id);
  
});

// ---- crud:comment:nondet:5:1 ----
bthread("crud:comment:nondet:5:1", function () {
  let id = 204;
  addComment(id);
  tryToAddExistingComment(id);
  verifyCommentExists(id);
  updateComment(id);
  deleteComment(id);
  tryToDeleteANonExistingComment(id);
  verifyCommentDoesNotExist(id);
  
});

// ---- crud:comment:nondet:5:2 ----
bthread("crud:comment:nondet:5:2", function () {
  let id = 204;
  addComment(id);
  tryToAddExistingComment(id);
  updateComment(id);
  verifyCommentExists(id);
  deleteComment(id);
  tryToDeleteANonExistingComment(id);
  verifyCommentDoesNotExist(id);
  
});

// ---- crud:comment:nondet:5:3 ----
bthread("crud:comment:nondet:5:3", function () {
  let id = 204;
  addComment(id);
  tryToAddExistingComment(id);
  verifyCommentExists(id);
  deleteComment(id);
  tryToDeleteANonExistingComment(id);
  verifyCommentDoesNotExist(id);
  
});

// ---- crud:comment:nondet:5:4 ----
bthread("crud:comment:nondet:5:4", function () {
  let id = 205;
  addComment(id);
  tryToAddExistingComment(id);
  deleteComment(id);
  tryToDeleteANonExistingComment(id);
  verifyCommentDoesNotExist(id);
  
});

// ---- crud:extension:nondet:6:1 ----
bthread("crud:extension:nondet:6:1", function () {
  let name = "name_205";
  let bundle = "bundle_205";
  addExtension(name, bundle);
  tryToAddExistingExtension(name, bundle);
  verifyExtensionExists(name, bundle);
  updateExtension(name, bundle);
  deleteExtension(name, bundle);
  tryToDeleteANonExistingExtension(name, bundle);
  verifyExtensionDoesNotExist(name, bundle);
  
});

// ---- crud:extension:nondet:6:2 ----
bthread("crud:extension:nondet:6:2", function () {
  let name = "name_205";
  let bundle = "bundle_205";
  addExtension(name, bundle);
  tryToAddExistingExtension(name, bundle);
  updateExtension(name, bundle);
  verifyExtensionExists(name, bundle);
  deleteExtension(name, bundle);
  tryToDeleteANonExistingExtension(name, bundle);
  verifyExtensionDoesNotExist(name, bundle);
  
});

// ---- crud:extension:nondet:6:3 ----
bthread("crud:extension:nondet:6:3", function () {
  let name = "name_205";
  let bundle = "bundle_205";
  addExtension(name, bundle);
  tryToAddExistingExtension(name, bundle);
  verifyExtensionExists(name, bundle);
  deleteExtension(name, bundle);
  tryToDeleteANonExistingExtension(name, bundle);
  verifyExtensionDoesNotExist(name, bundle);
  
});

// ---- crud:extension:nondet:6:4 ----
bthread("crud:extension:nondet:6:4", function () {
  let name = "name_206";
  let bundle = "bundle_206";
  addExtension(name, bundle);
  tryToAddExistingExtension(name, bundle);
  deleteExtension(name, bundle);
  tryToDeleteANonExistingExtension(name, bundle);
  verifyExtensionDoesNotExist(name, bundle);
  
});

// ---- crud:field:nondet:7:1 ----
bthread("crud:field:nondet:7:1", function () {
  let collection = "collection_206";
  let id = 206;
  addField(collection, id);
  tryToAddExistingField(collection, id);
  verifyFieldExists(collection, id);
  updateField(collection, id);
  deleteField(collection, id);
  tryToDeleteANonExistingField(collection, id);
  verifyFieldDoesNotExist(collection, id);
  
});

// ---- crud:field:nondet:7:2 ----
bthread("crud:field:nondet:7:2", function () {
  let collection = "collection_206";
  let id = 206;
  addField(collection, id);
  tryToAddExistingField(collection, id);
  updateField(collection, id);
  verifyFieldExists(collection, id);
  deleteField(collection, id);
  tryToDeleteANonExistingField(collection, id);
  verifyFieldDoesNotExist(collection, id);
  
});

// ---- crud:field:nondet:7:3 ----
bthread("crud:field:nondet:7:3", function () {
  let collection = "collection_206";
  let id = 206;
  addField(collection, id);
  tryToAddExistingField(collection, id);
  verifyFieldExists(collection, id);
  deleteField(collection, id);
  tryToDeleteANonExistingField(collection, id);
  verifyFieldDoesNotExist(collection, id);
  
});

// ---- crud:field:nondet:7:4 ----
bthread("crud:field:nondet:7:4", function () {
  let collection = "collection_207";
  let id = 207;
  addField(collection, id);
  tryToAddExistingField(collection, id);
  deleteField(collection, id);
  tryToDeleteANonExistingField(collection, id);
  verifyFieldDoesNotExist(collection, id);
  
});

// ---- crud:file:nondet:8:1 ----
bthread("crud:file:nondet:8:1", function () {
  let id = 207;
  addFile(id);
  tryToAddExistingFile(id);
  verifyFileExists(id);
  updateFile(id);
  deleteFile(id);
  tryToDeleteANonExistingFile(id);
  verifyFileDoesNotExist(id);
  
});

// ---- crud:file:nondet:8:2 ----
bthread("crud:file:nondet:8:2", function () {
  let id = 207;
  addFile(id);
  tryToAddExistingFile(id);
  updateFile(id);
  verifyFileExists(id);
  deleteFile(id);
  tryToDeleteANonExistingFile(id);
  verifyFileDoesNotExist(id);
  
});

// ---- crud:file:nondet:8:3 ----
bthread("crud:file:nondet:8:3", function () {
  let id = 207;
  addFile(id);
  tryToAddExistingFile(id);
  verifyFileExists(id);
  deleteFile(id);
  tryToDeleteANonExistingFile(id);
  verifyFileDoesNotExist(id);
  
});

// ---- crud:file:nondet:8:4 ----
bthread("crud:file:nondet:8:4", function () {
  let id = 208;
  addFile(id);
  tryToAddExistingFile(id);
  deleteFile(id);
  tryToDeleteANonExistingFile(id);
  verifyFileDoesNotExist(id);
  
});

// ---- crud:flow:nondet:9:1 ----
bthread("crud:flow:nondet:9:1", function () {
  let id = 208;
  addFlow(id);
  tryToAddExistingFlow(id);
  verifyFlowExists(id);
  updateFlow(id);
  deleteFlow(id);
  tryToDeleteANonExistingFlow(id);
  verifyFlowDoesNotExist(id);
  
});

// ---- crud:flow:nondet:9:2 ----
bthread("crud:flow:nondet:9:2", function () {
  let id = 208;
  addFlow(id);
  tryToAddExistingFlow(id);
  updateFlow(id);
  verifyFlowExists(id);
  deleteFlow(id);
  tryToDeleteANonExistingFlow(id);
  verifyFlowDoesNotExist(id);
  
});

// ---- crud:flow:nondet:9:3 ----
bthread("crud:flow:nondet:9:3", function () {
  let id = 208;
  addFlow(id);
  tryToAddExistingFlow(id);
  verifyFlowExists(id);
  deleteFlow(id);
  tryToDeleteANonExistingFlow(id);
  verifyFlowDoesNotExist(id);
  
});

// ---- crud:flow:nondet:9:4 ----
bthread("crud:flow:nondet:9:4", function () {
  let id = 209;
  addFlow(id);
  tryToAddExistingFlow(id);
  deleteFlow(id);
  tryToDeleteANonExistingFlow(id);
  verifyFlowDoesNotExist(id);
  
});

// ---- crud:folder:nondet:10:1 ----
bthread("crud:folder:nondet:10:1", function () {
  let id = 209;
  addFolder(id);
  tryToAddExistingFolder(id);
  verifyFolderExists(id);
  updateFolder(id);
  deleteFolder(id);
  tryToDeleteANonExistingFolder(id);
  verifyFolderDoesNotExist(id);
  
});

// ---- crud:folder:nondet:10:2 ----
bthread("crud:folder:nondet:10:2", function () {
  let id = 209;
  addFolder(id);
  tryToAddExistingFolder(id);
  updateFolder(id);
  verifyFolderExists(id);
  deleteFolder(id);
  tryToDeleteANonExistingFolder(id);
  verifyFolderDoesNotExist(id);
  
});

// ---- crud:folder:nondet:10:3 ----
bthread("crud:folder:nondet:10:3", function () {
  let id = 209;
  addFolder(id);
  tryToAddExistingFolder(id);
  verifyFolderExists(id);
  deleteFolder(id);
  tryToDeleteANonExistingFolder(id);
  verifyFolderDoesNotExist(id);
  
});

// ---- crud:folder:nondet:10:4 ----
bthread("crud:folder:nondet:10:4", function () {
  let id = 210;
  addFolder(id);
  tryToAddExistingFolder(id);
  deleteFolder(id);
  tryToDeleteANonExistingFolder(id);
  verifyFolderDoesNotExist(id);
  
});

// ---- crud:item:nondet:11:1 ----
bthread("crud:item:nondet:11:1", function () {
  let collection = "collection_210";
  let id = 210;
  addItem(collection, id);
  tryToAddExistingItem(collection, id);
  verifyItemExists(collection, id);
  updateItem(collection, id);
  deleteItem(collection, id);
  tryToDeleteANonExistingItem(collection, id);
  verifyItemDoesNotExist(collection, id);
  
});

// ---- crud:item:nondet:11:2 ----
bthread("crud:item:nondet:11:2", function () {
  let collection = "collection_210";
  let id = 210;
  addItem(collection, id);
  tryToAddExistingItem(collection, id);
  updateItem(collection, id);
  verifyItemExists(collection, id);
  deleteItem(collection, id);
  tryToDeleteANonExistingItem(collection, id);
  verifyItemDoesNotExist(collection, id);
  
});

// ---- crud:item:nondet:11:3 ----
bthread("crud:item:nondet:11:3", function () {
  let collection = "collection_210";
  let id = 210;
  addItem(collection, id);
  tryToAddExistingItem(collection, id);
  verifyItemExists(collection, id);
  deleteItem(collection, id);
  tryToDeleteANonExistingItem(collection, id);
  verifyItemDoesNotExist(collection, id);
  
});

// ---- crud:item:nondet:11:4 ----
bthread("crud:item:nondet:11:4", function () {
  let collection = "collection_211";
  let id = 211;
  addItem(collection, id);
  tryToAddExistingItem(collection, id);
  deleteItem(collection, id);
  tryToDeleteANonExistingItem(collection, id);
  verifyItemDoesNotExist(collection, id);
  
});

// ---- crud:operation:nondet:12:1 ----
bthread("crud:operation:nondet:12:1", function () {
  let id = 211;
  addOperation(id);
  tryToAddExistingOperation(id);
  verifyOperationExists(id);
  updateOperation(id);
  deleteOperation(id);
  tryToDeleteANonExistingOperation(id);
  verifyOperationDoesNotExist(id);
  
});

// ---- crud:operation:nondet:12:2 ----
bthread("crud:operation:nondet:12:2", function () {
  let id = 211;
  addOperation(id);
  tryToAddExistingOperation(id);
  updateOperation(id);
  verifyOperationExists(id);
  deleteOperation(id);
  tryToDeleteANonExistingOperation(id);
  verifyOperationDoesNotExist(id);
  
});

// ---- crud:operation:nondet:12:3 ----
bthread("crud:operation:nondet:12:3", function () {
  let id = 211;
  addOperation(id);
  tryToAddExistingOperation(id);
  verifyOperationExists(id);
  deleteOperation(id);
  tryToDeleteANonExistingOperation(id);
  verifyOperationDoesNotExist(id);
  
});

// ---- crud:operation:nondet:12:4 ----
bthread("crud:operation:nondet:12:4", function () {
  let id = 212;
  addOperation(id);
  tryToAddExistingOperation(id);
  deleteOperation(id);
  tryToDeleteANonExistingOperation(id);
  verifyOperationDoesNotExist(id);
  
});

// ---- crud:permission:nondet:13:1 ----
bthread("crud:permission:nondet:13:1", function () {
  let id = 212;
  addPermission(id);
  tryToAddExistingPermission(id);
  verifyPermissionExists(id);
  updatePermission(id);
  deletePermission(id);
  tryToDeleteANonExistingPermission(id);
  verifyPermissionDoesNotExist(id);
  
});

// ---- crud:permission:nondet:13:2 ----
bthread("crud:permission:nondet:13:2", function () {
  let id = 212;
  addPermission(id);
  tryToAddExistingPermission(id);
  updatePermission(id);
  verifyPermissionExists(id);
  deletePermission(id);
  tryToDeleteANonExistingPermission(id);
  verifyPermissionDoesNotExist(id);
  
});

// ---- crud:permission:nondet:13:3 ----
bthread("crud:permission:nondet:13:3", function () {
  let id = 212;
  addPermission(id);
  tryToAddExistingPermission(id);
  verifyPermissionExists(id);
  deletePermission(id);
  tryToDeleteANonExistingPermission(id);
  verifyPermissionDoesNotExist(id);
  
});

// ---- crud:permission:nondet:13:4 ----
bthread("crud:permission:nondet:13:4", function () {
  let id = 213;
  addPermission(id);
  tryToAddExistingPermission(id);
  deletePermission(id);
  tryToDeleteANonExistingPermission(id);
  verifyPermissionDoesNotExist(id);
  
});

// ---- crud:preset:nondet:14:1 ----
bthread("crud:preset:nondet:14:1", function () {
  let id = 213;
  addPreset(id);
  tryToAddExistingPreset(id);
  verifyPresetExists(id);
  updatePreset(id);
  deletePreset(id);
  tryToDeleteANonExistingPreset(id);
  verifyPresetDoesNotExist(id);
  
});

// ---- crud:preset:nondet:14:2 ----
bthread("crud:preset:nondet:14:2", function () {
  let id = 213;
  addPreset(id);
  tryToAddExistingPreset(id);
  updatePreset(id);
  verifyPresetExists(id);
  deletePreset(id);
  tryToDeleteANonExistingPreset(id);
  verifyPresetDoesNotExist(id);
  
});

// ---- crud:preset:nondet:14:3 ----
bthread("crud:preset:nondet:14:3", function () {
  let id = 213;
  addPreset(id);
  tryToAddExistingPreset(id);
  verifyPresetExists(id);
  deletePreset(id);
  tryToDeleteANonExistingPreset(id);
  verifyPresetDoesNotExist(id);
  
});

// ---- crud:preset:nondet:14:4 ----
bthread("crud:preset:nondet:14:4", function () {
  let id = 214;
  addPreset(id);
  tryToAddExistingPreset(id);
  deletePreset(id);
  tryToDeleteANonExistingPreset(id);
  verifyPresetDoesNotExist(id);
  
});

// ---- crud:relation:nondet:15:1 ----
bthread("crud:relation:nondet:15:1", function () {
  let id = 214;
  addRelation(id);
  tryToAddExistingRelation(id);
  verifyRelationExists(id);
  updateRelation(id);
  deleteRelation(id);
  tryToDeleteANonExistingRelation(id);
  verifyRelationDoesNotExist(id);
  
});

// ---- crud:relation:nondet:15:2 ----
bthread("crud:relation:nondet:15:2", function () {
  let id = 214;
  addRelation(id);
  tryToAddExistingRelation(id);
  updateRelation(id);
  verifyRelationExists(id);
  deleteRelation(id);
  tryToDeleteANonExistingRelation(id);
  verifyRelationDoesNotExist(id);
  
});

// ---- crud:relation:nondet:15:3 ----
bthread("crud:relation:nondet:15:3", function () {
  let id = 214;
  addRelation(id);
  tryToAddExistingRelation(id);
  verifyRelationExists(id);
  deleteRelation(id);
  tryToDeleteANonExistingRelation(id);
  verifyRelationDoesNotExist(id);
  
});

// ---- crud:relation:nondet:15:4 ----
bthread("crud:relation:nondet:15:4", function () {
  let id = 215;
  addRelation(id);
  tryToAddExistingRelation(id);
  deleteRelation(id);
  tryToDeleteANonExistingRelation(id);
  verifyRelationDoesNotExist(id);
  
});

// ---- crud:revision:nondet:16:1 ----
bthread("crud:revision:nondet:16:1", function () {
  let id = 215;
  addRevision(id);
  tryToAddExistingRevision(id);
  verifyRevisionExists(id);
  updateRevision(id);
  deleteRevision(id);
  tryToDeleteANonExistingRevision(id);
  verifyRevisionDoesNotExist(id);
  
});

// ---- crud:revision:nondet:16:2 ----
bthread("crud:revision:nondet:16:2", function () {
  let id = 215;
  addRevision(id);
  tryToAddExistingRevision(id);
  updateRevision(id);
  verifyRevisionExists(id);
  deleteRevision(id);
  tryToDeleteANonExistingRevision(id);
  verifyRevisionDoesNotExist(id);
  
});

// ---- crud:revision:nondet:16:3 ----
bthread("crud:revision:nondet:16:3", function () {
  let id = 215;
  addRevision(id);
  tryToAddExistingRevision(id);
  verifyRevisionExists(id);
  deleteRevision(id);
  tryToDeleteANonExistingRevision(id);
  verifyRevisionDoesNotExist(id);
  
});

// ---- crud:revision:nondet:16:4 ----
bthread("crud:revision:nondet:16:4", function () {
  let id = 216;
  addRevision(id);
  tryToAddExistingRevision(id);
  deleteRevision(id);
  tryToDeleteANonExistingRevision(id);
  verifyRevisionDoesNotExist(id);
  
});

// ---- crud:role:nondet:17:1 ----
bthread("crud:role:nondet:17:1", function () {
  let id = 216;
  addRole(id);
  tryToAddExistingRole(id);
  verifyRoleExists(id);
  updateRole(id);
  deleteRole(id);
  tryToDeleteANonExistingRole(id);
  verifyRoleDoesNotExist(id);
  
});

// ---- crud:role:nondet:17:2 ----
bthread("crud:role:nondet:17:2", function () {
  let id = 216;
  addRole(id);
  tryToAddExistingRole(id);
  updateRole(id);
  verifyRoleExists(id);
  deleteRole(id);
  tryToDeleteANonExistingRole(id);
  verifyRoleDoesNotExist(id);
  
});

// ---- crud:role:nondet:17:3 ----
bthread("crud:role:nondet:17:3", function () {
  let id = 216;
  addRole(id);
  tryToAddExistingRole(id);
  verifyRoleExists(id);
  deleteRole(id);
  tryToDeleteANonExistingRole(id);
  verifyRoleDoesNotExist(id);
  
});

// ---- crud:role:nondet:17:4 ----
bthread("crud:role:nondet:17:4", function () {
  let id = 217;
  addRole(id);
  tryToAddExistingRole(id);
  deleteRole(id);
  tryToDeleteANonExistingRole(id);
  verifyRoleDoesNotExist(id);
  
});

// ---- crud:schema:nondet:18:1 ----
bthread("crud:schema:nondet:18:1", function () {
  let id = 217;
  addSchema(id);
  tryToAddExistingSchema(id);
  verifySchemaExists(id);
  updateSchema(id);
  deleteSchema(id);
  tryToDeleteANonExistingSchema(id);
  verifySchemaDoesNotExist(id);
  
});

// ---- crud:schema:nondet:18:2 ----
bthread("crud:schema:nondet:18:2", function () {
  let id = 217;
  addSchema(id);
  tryToAddExistingSchema(id);
  updateSchema(id);
  verifySchemaExists(id);
  deleteSchema(id);
  tryToDeleteANonExistingSchema(id);
  verifySchemaDoesNotExist(id);
  
});

// ---- crud:schema:nondet:18:3 ----
bthread("crud:schema:nondet:18:3", function () {
  let id = 217;
  addSchema(id);
  tryToAddExistingSchema(id);
  verifySchemaExists(id);
  deleteSchema(id);
  tryToDeleteANonExistingSchema(id);
  verifySchemaDoesNotExist(id);
  
});

// ---- crud:schema:nondet:18:4 ----
bthread("crud:schema:nondet:18:4", function () {
  let id = 218;
  addSchema(id);
  tryToAddExistingSchema(id);
  deleteSchema(id);
  tryToDeleteANonExistingSchema(id);
  verifySchemaDoesNotExist(id);
  
});

// ---- crud:server:nondet:19:1 ----
bthread("crud:server:nondet:19:1", function () {
  let id = 218;
  addServer(id);
  tryToAddExistingServer(id);
  verifyServerExists(id);
  updateServer(id);
  deleteServer(id);
  tryToDeleteANonExistingServer(id);
  verifyServerDoesNotExist(id);
  
});

// ---- crud:server:nondet:19:2 ----
bthread("crud:server:nondet:19:2", function () {
  let id = 218;
  addServer(id);
  tryToAddExistingServer(id);
  updateServer(id);
  verifyServerExists(id);
  deleteServer(id);
  tryToDeleteANonExistingServer(id);
  verifyServerDoesNotExist(id);
  
});

// ---- crud:server:nondet:19:3 ----
bthread("crud:server:nondet:19:3", function () {
  let id = 218;
  addServer(id);
  tryToAddExistingServer(id);
  verifyServerExists(id);
  deleteServer(id);
  tryToDeleteANonExistingServer(id);
  verifyServerDoesNotExist(id);
  
});

// ---- crud:server:nondet:19:4 ----
bthread("crud:server:nondet:19:4", function () {
  let id = 219;
  addServer(id);
  tryToAddExistingServer(id);
  deleteServer(id);
  tryToDeleteANonExistingServer(id);
  verifyServerDoesNotExist(id);
  
});

// ---- crud:setting:nondet:20:1 ----
bthread("crud:setting:nondet:20:1", function () {
  let id = 219;
  addSetting(id);
  tryToAddExistingSetting(id);
  verifySettingExists(id);
  updateSetting(id);
  deleteSetting(id);
  tryToDeleteANonExistingSetting(id);
  verifySettingDoesNotExist(id);
  
});

// ---- crud:setting:nondet:20:2 ----
bthread("crud:setting:nondet:20:2", function () {
  let id = 219;
  addSetting(id);
  tryToAddExistingSetting(id);
  updateSetting(id);
  verifySettingExists(id);
  deleteSetting(id);
  tryToDeleteANonExistingSetting(id);
  verifySettingDoesNotExist(id);
  
});

// ---- crud:setting:nondet:20:3 ----
bthread("crud:setting:nondet:20:3", function () {
  let id = 219;
  addSetting(id);
  tryToAddExistingSetting(id);
  verifySettingExists(id);
  deleteSetting(id);
  tryToDeleteANonExistingSetting(id);
  verifySettingDoesNotExist(id);
  
});

// ---- crud:setting:nondet:20:4 ----
bthread("crud:setting:nondet:20:4", function () {
  let id = 220;
  addSetting(id);
  tryToAddExistingSetting(id);
  deleteSetting(id);
  tryToDeleteANonExistingSetting(id);
  verifySettingDoesNotExist(id);
  
});

// ---- crud:user:nondet:21:1 ----
bthread("crud:user:nondet:21:1", function () {
  let id = 220;
  addUser(id);
  tryToAddExistingUser(id);
  verifyUserExists(id);
  updateUser(id);
  deleteUser(id);
  tryToDeleteANonExistingUser(id);
  verifyUserDoesNotExist(id);
  
});

// ---- crud:user:nondet:21:2 ----
bthread("crud:user:nondet:21:2", function () {
  let id = 220;
  addUser(id);
  tryToAddExistingUser(id);
  updateUser(id);
  verifyUserExists(id);
  deleteUser(id);
  tryToDeleteANonExistingUser(id);
  verifyUserDoesNotExist(id);
  
});

// ---- crud:user:nondet:21:3 ----
bthread("crud:user:nondet:21:3", function () {
  let id = 220;
  addUser(id);
  tryToAddExistingUser(id);
  verifyUserExists(id);
  deleteUser(id);
  tryToDeleteANonExistingUser(id);
  verifyUserDoesNotExist(id);
  
});

// ---- crud:user:nondet:21:4 ----
bthread("crud:user:nondet:21:4", function () {
  let id = 221;
  addUser(id);
  tryToAddExistingUser(id);
  deleteUser(id);
  tryToDeleteANonExistingUser(id);
  verifyUserDoesNotExist(id);
  
});

// ---- crud:util:nondet:22:1 ----
bthread("crud:util:nondet:22:1", function () {
  let collection = "collection_221";
  addUtil(collection);
  tryToAddExistingUtil(collection);
  verifyUtilExists(collection);
  updateUtil(collection);
  deleteUtil(collection);
  tryToDeleteANonExistingUtil(collection);
  verifyUtilDoesNotExist(collection);
  
});

// ---- crud:util:nondet:22:2 ----
bthread("crud:util:nondet:22:2", function () {
  let collection = "collection_221";
  addUtil(collection);
  tryToAddExistingUtil(collection);
  updateUtil(collection);
  verifyUtilExists(collection);
  deleteUtil(collection);
  tryToDeleteANonExistingUtil(collection);
  verifyUtilDoesNotExist(collection);
  
});

// ---- crud:util:nondet:22:3 ----
bthread("crud:util:nondet:22:3", function () {
  let collection = "collection_221";
  addUtil(collection);
  tryToAddExistingUtil(collection);
  verifyUtilExists(collection);
  deleteUtil(collection);
  tryToDeleteANonExistingUtil(collection);
  verifyUtilDoesNotExist(collection);
  
});

// ---- crud:util:nondet:22:4 ----
bthread("crud:util:nondet:22:4", function () {
  let collection = "collection_222";
  addUtil(collection);
  tryToAddExistingUtil(collection);
  deleteUtil(collection);
  tryToDeleteANonExistingUtil(collection);
  verifyUtilDoesNotExist(collection);
  
});

// ---- crud:version:nondet:23:1 ----
bthread("crud:version:nondet:23:1", function () {
  let id = 222;
  addVersion(id);
  tryToAddExistingVersion(id);
  verifyVersionExists(id);
  updateVersion(id);
  deleteVersion(id);
  tryToDeleteANonExistingVersion(id);
  verifyVersionDoesNotExist(id);
  
});

// ---- crud:version:nondet:23:2 ----
bthread("crud:version:nondet:23:2", function () {
  let id = 222;
  addVersion(id);
  tryToAddExistingVersion(id);
  updateVersion(id);
  verifyVersionExists(id);
  deleteVersion(id);
  tryToDeleteANonExistingVersion(id);
  verifyVersionDoesNotExist(id);
  
});

// ---- crud:version:nondet:23:3 ----
bthread("crud:version:nondet:23:3", function () {
  let id = 222;
  addVersion(id);
  tryToAddExistingVersion(id);
  verifyVersionExists(id);
  deleteVersion(id);
  tryToDeleteANonExistingVersion(id);
  verifyVersionDoesNotExist(id);
  
});

// ---- crud:version:nondet:23:4 ----
bthread("crud:version:nondet:23:4", function () {
  let id = 223;
  addVersion(id);
  tryToAddExistingVersion(id);
  deleteVersion(id);
  tryToDeleteANonExistingVersion(id);
  verifyVersionDoesNotExist(id);
  
});

// ---- crud:webhook:nondet:24:1 ----
bthread("crud:webhook:nondet:24:1", function () {
  let id = 223;
  addWebhook(id);
  tryToAddExistingWebhook(id);
  verifyWebhookExists(id);
  updateWebhook(id);
  deleteWebhook(id);
  tryToDeleteANonExistingWebhook(id);
  verifyWebhookDoesNotExist(id);
  
});

// ---- crud:webhook:nondet:24:2 ----
bthread("crud:webhook:nondet:24:2", function () {
  let id = 223;
  addWebhook(id);
  tryToAddExistingWebhook(id);
  updateWebhook(id);
  verifyWebhookExists(id);
  deleteWebhook(id);
  tryToDeleteANonExistingWebhook(id);
  verifyWebhookDoesNotExist(id);
  
});

// ---- crud:webhook:nondet:24:3 ----
bthread("crud:webhook:nondet:24:3", function () {
  let id = 223;
  addWebhook(id);
  tryToAddExistingWebhook(id);
  verifyWebhookExists(id);
  deleteWebhook(id);
  tryToDeleteANonExistingWebhook(id);
  verifyWebhookDoesNotExist(id);
  
});

// ---- crud:webhook:nondet:24:4 ----
bthread("crud:webhook:nondet:24:4", function () {
  let id = 224;
  addWebhook(id);
  tryToAddExistingWebhook(id);
  deleteWebhook(id);
  tryToDeleteANonExistingWebhook(id);
  verifyWebhookDoesNotExist(id);
  
});
