// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=twilio  Provider=real_world_llm_provider  Mode=?  Stories=108
// Source: artifacts/hls_det/real_world_llm_provider/twilio/hls_gold.json
// ============================================================================
bthread("CRUD_2010_04_01", function() {
});

bthread("CRUD_account", function() {
});

bthread("CRUD_accounts_json", function() {
});

bthread("CRUD_addonresult", function() {
});

bthread("CRUD_addonresults_json", function() {
});

bthread("CRUD_address", function() {
});

bthread("CRUD_addresses_json", function() {
});

bthread("CRUD_alltime_json", function() {
});

bthread("CRUD_application", function() {
});

bthread("CRUD_applications_json", function() {
});

bthread("CRUD_assignedaddon", function() {
});

bthread("CRUD_assignedaddons_json", function() {
});

bthread("CRUD_auth", function() {
});

bthread("CRUD_authorizedconnectapp", function() {
});

bthread("CRUD_authorizedconnectapps_json", function() {
});

bthread("CRUD_availablephonenumber", function() {
});

bthread("CRUD_availablephonenumbers_json", function() {
});

bthread("CRUD_balance_json", function() {
});

bthread("CRUD_call", function() {
});

bthread("CRUD_calls_json", function() {
});

bthread("CRUD_callsid_json", function() {
});

bthread("CRUD_conference", function() {
});

bthread("CRUD_conferences_json", function() {
});

bthread("CRUD_connectapp", function() {
});

bthread("CRUD_connectapps_json", function() {
});

bthread("CRUD_connectappsid_json", function() {
});

bthread("CRUD_countrycode_json", function() {
});

bthread("CRUD_credential", function() {
});

bthread("CRUD_credentiallist", function() {
});

bthread("CRUD_credentiallistmapping", function() {
});

bthread("CRUD_credentiallistmappings_json", function() {
});

bthread("CRUD_credentiallists_json", function() {
});

bthread("CRUD_credentials_json", function() {
});

bthread("CRUD_daily_json", function() {
});

bthread("CRUD_data_json", function() {
});

bthread("CRUD_dependentphonenumbers_json", function() {
});

bthread("CRUD_domain", function() {
});

bthread("CRUD_domains_json", function() {
});

bthread("CRUD_events_json", function() {
});

bthread("CRUD_extension", function() {
});

bthread("CRUD_extensions_json", function() {
});

bthread("CRUD_feedback_json", function() {
});

bthread("CRUD_incomingphonenumber", function() {
});

bthread("CRUD_incomingphonenumbers_json", function() {
});

bthread("CRUD_ipaccesscontrollist", function() {
});

bthread("CRUD_ipaccesscontrollistmapping", function() {
});

bthread("CRUD_ipaccesscontrollistmappings_json", function() {
});

bthread("CRUD_ipaccesscontrollists_json", function() {
});

bthread("CRUD_ipaddress", function() {
});

bthread("CRUD_ipaddresses_json", function() {
});

bthread("CRUD_key", function() {
});

bthread("CRUD_keys_json", function() {
});

bthread("CRUD_lastmonth_json", function() {
});

bthread("CRUD_local_json", function() {
});

bthread("CRUD_machinetomachine_json", function() {
});

bthread("CRUD_media", function() {
});

bthread("CRUD_media_json", function() {
});

bthread("CRUD_member", function() {
});

bthread("CRUD_members_json", function() {
});

bthread("CRUD_message", function() {
});

bthread("CRUD_messages_json", function() {
});

bthread("CRUD_mobile_json", function() {
});

bthread("CRUD_monthly_json", function() {
});

bthread("CRUD_national_json", function() {
});

bthread("CRUD_notification", function() {
});

bthread("CRUD_notifications_json", function() {
});

bthread("CRUD_outgoingcallerid", function() {
});

bthread("CRUD_outgoingcallerids_json", function() {
});

bthread("CRUD_participant", function() {
});

bthread("CRUD_participants_json", function() {
});

bthread("CRUD_payload", function() {
});

bthread("CRUD_payloads_json", function() {
});

bthread("CRUD_payment", function() {
});

bthread("CRUD_payments_json", function() {
});

bthread("CRUD_queue", function() {
});

bthread("CRUD_queues_json", function() {
});

bthread("CRUD_record", function() {
});

bthread("CRUD_recording", function() {
});

bthread("CRUD_recordings_json", function() {
});

bthread("CRUD_records_json", function() {
});

bthread("CRUD_registration", function() {
});

bthread("CRUD_sharedcost_json", function() {
});

bthread("CRUD_shortcode", function() {
});

bthread("CRUD_shortcodes_json", function() {
});

bthread("CRUD_sid_json", function() {
});

bthread("CRUD_signingkey", function() {
});

bthread("CRUD_signingkeys_json", function() {
});

bthread("CRUD_sip", function() {
});

bthread("CRUD_siprec", function() {
});

bthread("CRUD_siprec_json", function() {
});

bthread("CRUD_sm", function() {
});

bthread("CRUD_stream", function() {
});

bthread("CRUD_streams_json", function() {
});

bthread("CRUD_thismonth_json", function() {
});

bthread("CRUD_today_json", function() {
});

bthread("CRUD_tokens_json", function() {
});

bthread("CRUD_tollfree_json", function() {
});

bthread("CRUD_transcription", function() {
});

bthread("CRUD_transcriptions_json", function() {
});

bthread("CRUD_trigger", function() {
});

bthread("CRUD_triggers_json", function() {
});

bthread("CRUD_usage", function() {
});

bthread("CRUD_userdefinedmessages_json", function() {
});

bthread("CRUD_userdefinedmessagesubscription", function() {
});

bthread("CRUD_userdefinedmessagesubscriptions_json", function() {
});

bthread("CRUD_voip_json", function() {
});

bthread("CRUD_yearly_json", function() {
});

bthread("CRUD_yesterday_json", function() {
});
