from __future__ import annotations

from pathlib import Path
from typing import Dict, Any, List, Tuple

import re
import json


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _escape_js_string(s: str) -> str:
    """Escape a Python string for safe inclusion in double-quoted JS string."""
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("\n", "\\n")
         .replace("\r", "\\r")
    )


def _template_to_js_expr(template: str) -> str:
    """
    Convert a descriptionTemplate like:
        "Add a customer with id {id} and name {name}"
    into a JS expression:
        "Add a customer with id " + id + " and name " + name
    """
    if template is None:
        return '""'
    parts: List[str] = []
    i = 0
    while i < len(template):
        j = template.find("{", i)
        if j == -1:
            # remaining literal
            literal = template[i:]
            if literal:
                parts.append(f'"{_escape_js_string(literal)}"')
            break
        if j > i:
            literal = template[i:j]
            parts.append(f'"{_escape_js_string(literal)}"')
        k = template.find("}", j + 1)
        if k == -1:
            # unmatched "{", treat as literal
            literal = template[j:]
            parts.append(f'"{_escape_js_string(literal)}"')
            break
        var_name = template[j + 1 : k].strip()
        if var_name:
            parts.append(var_name)
        i = k + 1

    if not parts:
        return '""'
    if len(parts) == 1 and parts[0].startswith('"') and parts[0].endswith('"'):
        return parts[0]
    return " + ".join(parts)


def _path_template_to_js(path: str) -> str:
    """
    Convert a path template like:
        "/customers/{id}"
    into JS expression:
        "/customers/" + id
    """
    if path is None:
        return '""'
    tokens = re.split(r"(\{[A-Za-z0-9_]+\})", path)
    parts: List[str] = []
    for tok in tokens:
        if not tok:
            continue
        if tok.startswith("{") and tok.endswith("}"):
            var_name = tok[1:-1].strip()
            if var_name:
                parts.append(var_name)
        else:
            parts.append(f'"{_escape_js_string(tok)}"')
    if not parts:
        return '""'
    if len(parts) == 1 and parts[0].startswith('"') and parts[0].endswith('"'):
        return parts[0]
    return " + ".join(parts)


def _iter_entities(spec: Dict[str, Any]) -> List[Tuple[str, Dict[str, Any]]]:
    """
    Normalize entities to a list of (name, entity_spec) preserving JSON order.
    """
    entities = spec.get("entities") or {}
    if isinstance(entities, dict):
        return list(entities.items())
    elif isinstance(entities, list):
        out: List[Tuple[str, Dict[str, Any]]] = []
        for i, ent in enumerate(entities):
            name = ent.get("name") or ent.get("displayName") or f"Entity{i+1}"
            out.append((name, ent))
        return out
    return []


def _slug_for_entity(ent_name: str, ent: Dict[str, Any]) -> str:
    slug = ent.get("displayName") or ent_name
    return str(slug).lower()


# ---------------------------------------------------------------------------
# interfaces.readable.js
# ---------------------------------------------------------------------------

def _emit_interfaces(spec: Dict[str, Any], out_dir: Path) -> None:
    entities = _iter_entities(spec)

    lines: List[str] = []
    lines.append("//@provengo summon rest")
    lines.append("")
    lines.append("// === Auto-generated interfaces.readable.js ===")
    lines.append("// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py")
    lines.append("")
    lines.append("var host = (typeof host !== 'undefined') ? host : 'localhost';")
    lines.append("var port = (typeof port !== 'undefined') ? port : 8080;")
    lines.append("")
    lines.append('const svc = new RESTSession("http://" + host + ":" + port, "provengo-client", {')
    lines.append('  headers: { "Content-Type": "application/json" },')
    lines.append("});")
    lines.append("")
    lines.append("function matchesDescriptionRegex(re) {")
    lines.append('  return bp.EventSet("Match description", function (e) {')
    lines.append('    return e && e.data && e.data.parameters && typeof e.data.parameters.description === "string"')
    lines.append("           && re.test(e.data.parameters.description);")
    lines.append("  });")
    lines.append("}")
    lines.append("")

    for ent_name, ent in entities:
        slug = _slug_for_entity(ent_name, ent)
        params: List[str] = list(ent.get("params") or [])
        ops: Dict[str, Any] = ent.get("operations") or {}
        waits: Dict[str, Any] = ent.get("waitForPatterns") or {}

        add_op = ops.get("add") or {}
        del_op = ops.get("delete") or {}
        ver_op = ops.get("verifyExists") or {}

        add_fn = add_op.get("name") or f"add{ent_name}"
        del_fn = del_op.get("name") or f"delete{ent_name}"
        ver_fn = ver_op.get("name") or f"verify{ent_name}Exists"

        add_path = add_op.get("path") or f"/{slug}s"
        add_method = (add_op.get("method") or "POST").upper()
        add_desc_tmpl = add_op.get("descriptionTemplate") or f"Add a {ent.get('displayName', ent_name)} entity"
        add_body_tmpl = add_op.get("bodyTemplate") or {}

        # ---- header per-entity ----
        lines.append(f"// ---- Entity: {ent_name} ----")
        lines.append("")

        # --- add<Entity> ---
        param_sig = ", ".join(params)
        lines.append(f"function {add_fn}({param_sig}) {{")
        lines.append(f'  var url = "{_escape_js_string(add_path)}";')
        lines.append(f"  var description = {_template_to_js_expr(add_desc_tmpl)};")
        if add_body_tmpl:
            lines.append("  var body = {")
            items = list(add_body_tmpl.items())
            for idx, (field, placeholder) in enumerate(items):
                if isinstance(placeholder, str) and placeholder.startswith("{") and placeholder.endswith("}"):
                    var = placeholder[1:-1].strip()
                    value_expr = var
                else:
                    value_expr = json.dumps(placeholder)
                comma = "," if idx < len(items) - 1 else ""
                lines.append(f'    "{field}": {value_expr}{comma}')
            lines.append("  };")
        else:
            lines.append("  var body = undefined;")
        lines.append("  return svc.request({")
        lines.append(f'    method: "{add_method}",')
        lines.append("    url: url,")
        lines.append("    parameters: { description: description },")
        lines.append("    body: body")
        lines.append("  });")
        lines.append("}")
        lines.append("")

        # --- delete<Entity> ---
        del_path = del_op.get("path") or (
            add_path.rstrip("/") + ("/{" + params[0] + "}" if params else "")
        )
        del_method = (del_op.get("method") or "DELETE").upper()
        del_desc_tmpl = del_op.get("descriptionTemplate") or f"Delete a {ent.get('displayName', ent_name)} entity"

        lines.append(f"function {del_fn}({param_sig}) {{")
        lines.append(f"  var url = {_path_template_to_js(del_path)};")
        lines.append(f"  var description = {_template_to_js_expr(del_desc_tmpl)};")
        lines.append("  var body = undefined;")
        lines.append("  return svc.request({")
        lines.append(f'    method: "{del_method}",')
        lines.append("    url: url,")
        lines.append("    parameters: { description: description },")
        lines.append("    body: body")
        lines.append("  });")
        lines.append("}")
        lines.append("")

        # --- verify<Entity>Exists ---
        lines.append(f"function {ver_fn}({param_sig}) {{")
        lines.append("  // TODO: implement verification or guard logic if needed.")
        lines.append("}")
        lines.append("")

        # --- synthesized high-level operations used by HLS stories ---
        try_add_fn = f"tryToAddExisting{ent_name}"
        update_fn = f"update{ent_name}"
        try_del_non_fn = f"tryToDeleteANonExisting{ent_name}"
        ver_not_exists_fn = f"verify{ent_name}DoesNotExist"

        # tryToAddExisting<Entity>: by default, reuse add<Entity>
        lines.append(f"function {try_add_fn}({param_sig}) {{")
        call_args = ", ".join(params)
        lines.append(f"  return {add_fn}({call_args});")
        lines.append("}")
        lines.append("")

        # update<Entity>: if an explicit 'update' operation exists, call it; otherwise reuse add<Entity>
        upd_op = ops.get("update")
        if upd_op:
            upd_path = upd_op.get("path") or add_path
            upd_method = (upd_op.get("method") or "PUT").upper()
            upd_desc_tmpl = upd_op.get("descriptionTemplate") or f"Update a {ent.get('displayName', ent_name)} entity"
            upd_body_tmpl = upd_op.get("bodyTemplate") or add_body_tmpl or {}
            lines.append(f"function {update_fn}({param_sig}) {{")
            lines.append(f'  var url = "{_escape_js_string(upd_path)}";')
            lines.append(f"  var description = {_template_to_js_expr(upd_desc_tmpl)};")
            if upd_body_tmpl:
                lines.append("  var body = {")
                items2 = list(upd_body_tmpl.items())
                for idx, (field, placeholder) in enumerate(items2):
                    if isinstance(placeholder, str) and placeholder.startswith("{") and placeholder.endswith("}"):
                        var = placeholder[1:-1].strip()
                        value_expr = var
                    else:
                        value_expr = json.dumps(placeholder)
                    comma = "," if idx < len(items2) - 1 else ""
                    lines.append(f'    "{field}": {value_expr}{comma}')
                lines.append("  };")
            else:
                lines.append("  var body = undefined;")
            lines.append("  return svc.request({")
            lines.append(f'    method: "{upd_method}",')
            lines.append("    url: url,")
            lines.append("    parameters: { description: description },")
            lines.append("    body: body")
            lines.append("  });")
            lines.append("}")
            lines.append("")
        else:
            lines.append(f"function {update_fn}({param_sig}) {{")
            call_args2 = ", ".join(params)
            lines.append(f"  // No explicit 'update' operation; reuse {add_fn} semantics.")
            lines.append(f"  return {add_fn}({call_args2});")
            lines.append("}")
            lines.append("")

        # tryToDeleteANonExisting<Entity>: reuse delete<Entity>
        lines.append(f"function {try_del_non_fn}({param_sig}) {{")
        call_args3 = ", ".join(params)
        lines.append(f"  return {del_fn}({call_args3});")
        lines.append("}")
        lines.append("")

        # verify<Entity>DoesNotExist: stub (monitors / hazards should check)
        lines.append(f"function {ver_not_exists_fn}({param_sig}) {{")
        lines.append("  // TODO: implement real not-exists verification or rely on monitors.")
        lines.append("}")
        lines.append("")

        # --- waitForAny<Entity>Added/Deleted ---
        for key, label in (("added", "Added"), ("deleted", "Deleted")):
            patt = waits.get(key) if isinstance(waits, dict) else None
            if not patt:
                continue
            wname = patt.get("name") or f"waitForAny{ent_name}{label}"
            regex = patt.get("descriptionRegex")
            if not regex:
                continue
            lines.append(f"function {wname}() {{")
            lines.append(f"  var ev = bp.sync({{waitFor: matchesDescriptionRegex(/{regex}/)}});")
            lines.append(f"  var m = ev.data.parameters.description.match(/{regex}/);")
            lines.append("  var captures = m.slice(1);")
            names_array = ", ".join(f'"{p}"' for p in params)
            lines.append(f"  var names = [{names_array}];")
            lines.append("  var obj = {};")
            lines.append("  for (var i = 0; i < names.length; i++) {")
            lines.append("    obj[names[i]] = (i < captures.length) ? captures[i] : undefined;")
            lines.append("  }")
            lines.append("  return obj;")
            lines.append("}")
            lines.append("")

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "interfaces.readable.js"
    out_path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# stories_hls.js
# ---------------------------------------------------------------------------

def _make_args_for_basic_crud(params: List[str]) -> List[str]:
    """
    Basic CRUD pattern:
      - First parameter (id-like) gets 201
      - Params whose name contains "name" get "name_201"
      - All others are undefined
    """
    args: List[str] = []
    for i, p in enumerate(params):
        lp = p.lower()
        if i == 0 or lp.endswith("id"):
            args.append("201")
        elif "name" in lp:
            args.append('"name_201"')
        else:
            args.append("undefined")
    return args


def _make_args_for_duplicate_add(params: List[str]) -> List[str]:
    """
    Duplicate-add pattern:
      - First parameter (id-like) gets 202
      - Params whose name contains "name" get "name_202"
      - All others are undefined
    """
    args: List[str] = []
    for i, p in enumerate(params):
        lp = p.lower()
        if i == 0 or lp.endswith("id"):
            args.append("202")
        elif "name" in lp:
            args.append('"name_202"')
        else:
            args.append("undefined")
    return args


def _make_args_for_id(params: List[str], base_id: int) -> List[str]:
    """
    Helper for old 4+2 CRUD variants.
    - First param and any '*id' param get base_id
    - 'name' params get "name_<base_id>"
    - Others undefined
    """
    args: List[str] = []
    for i, p in enumerate(params):
        lp = p.lower()
        if i == 0 or lp.endswith("id"):
            args.append(str(base_id))
        elif "name" in lp:
            args.append(f'"name_{base_id}"')
        else:
            args.append("undefined")
    return args


def _emit_stories(spec: Dict[str, Any], out_dir: Path) -> None:
    entities = _iter_entities(spec)
    stories_spec = spec.get("stories") or []

    # Build quick index of patterns per entity (may be useful later)
    patterns_by_entity: Dict[str, set] = {}
    for st in stories_spec:
        ent = st.get("entity")
        pat = st.get("pattern")
        if not ent or not pat:
            continue
        patterns_by_entity.setdefault(ent, set()).add(pat)

    lines: List[str] = []
    lines.append("// === Auto-generated stories_hls.js ===")
    lines.append("// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py")
    lines.append("")

    # First, keep simple new-style stories as a lightweight layer
    for ent_name, ent in entities:
        params: List[str] = list(ent.get("params") or [])
        ops: Dict[str, Any] = ent.get("operations") or {}
        add_op = ops.get("add") or {}
        ver_op = ops.get("verifyExists") or {}
        del_op = ops.get("delete") or {}

        add_fn = add_op.get("name") or f"add{ent_name}"
        ver_fn = ver_op.get("name") or f"verify{ent_name}Exists"
        del_fn = del_op.get("name") or f"delete{ent_name}"

        pats = patterns_by_entity.get(ent_name, set())
        if "crud_basic" in pats:
            args = _make_args_for_basic_crud(params)
            arg_str = ", ".join(args)
            lines.append(f'bp.registerBThread("{ent_name}_basicCrud", function() {{')
            lines.append(f"  // Basic CRUD story for {ent_name}")
            lines.append(f"  {add_fn}({arg_str});")
            lines.append(f"  {ver_fn}({arg_str});")
            lines.append(f"  {del_fn}({arg_str});")
            lines.append("});")
            lines.append("")

        if "duplicate_add" in pats:
            args2 = _make_args_for_duplicate_add(params)
            arg_str2 = ", ".join(args2)
            lines.append(f'bp.registerBThread("{ent_name}_duplicateAdd", function() {{')
            lines.append(f"  // Duplicate-add scenario for {ent_name}")
            lines.append(f"  {add_fn}({arg_str2});")
            lines.append(f"  {ver_fn}({arg_str2});")
            lines.append(f"  {add_fn}({arg_str2});  // expected to fail or be blocked")
            lines.append("});")
            lines.append("")

    # Now, emit old-style 4+2 nondet CRUD stories per entity
    for idx, (ent_name, ent) in enumerate(entities, start=1):
        slug = _slug_for_entity(ent_name, ent)
        params: List[str] = list(ent.get("params") or [])
        ops: Dict[str, Any] = ent.get("operations") or {}
        add_op = ops.get("add") or {}
        del_op = ops.get("delete") or {}
        ver_op = ops.get("verifyExists") or {}

        add_fn = add_op.get("name") or f"add{ent_name}"
        del_fn = del_op.get("name") or f"delete{ent_name}"
        ver_fn = ver_op.get("name") or f"verify{ent_name}Exists"

        try_add_fn = f"tryToAddExisting{ent_name}"
        update_fn = f"update{ent_name}"
        try_del_non_fn = f"tryToDeleteANonExisting{ent_name}"
        ver_not_exists_fn = f"verify{ent_name}DoesNotExist"

        # Four main nondet variants
        for variant, order in [
            ("1", ["add", "dup-add", "verify", "update", "delete", "delete-nonexisting", "verify-not-exists"]),
            ("2", ["add", "dup-add", "update", "verify", "delete", "delete-nonexisting", "verify-not-exists"]),
            ("3", ["add", "dup-add", "verify", "delete", "delete-nonexisting", "verify-not-exists"]),
            ("4", ["add", "dup-add", "delete", "delete-nonexisting", "verify-not-exists"]),
        ]:
            base_id = 200 + (idx * 10) + int(variant)  # spread ids by entity & variant
            args = _make_args_for_id(params, base_id)
            arg_str = ", ".join(args)
            story_name = f"crud:{slug}:nondet:1:{variant}"

            lines.append(f'bp.registerBThread("{story_name}", function() {{')
            lines.append(f"  // Old-style nondet variant {variant} for {ent_name}")
            for step in order:
                if step == "add":
                    lines.append(f"  {add_fn}({arg_str});")
                elif step == "dup-add":
                    lines.append(f"  {try_add_fn}({arg_str});")
                elif step == "verify":
                    lines.append(f"  {ver_fn}({arg_str});")
                elif step == "update":
                    lines.append(f"  {update_fn}({arg_str});")
                elif step == "delete":
                    lines.append(f"  {del_fn}({arg_str});")
                elif step == "delete-nonexisting":
                    lines.append(f"  {try_del_non_fn}({arg_str});")
                elif step == "verify-not-exists":
                    lines.append(f"  {ver_not_exists_fn}({arg_str});")
            lines.append("});")
            lines.append("")

        # Negative dup-add story
        neg_dup_id = 1000 + idx * 10
        neg_dup_args = _make_args_for_id(params, neg_dup_id)
        neg_dup_arg_str = ", ".join(neg_dup_args)
        neg_dup_name = f"crud:{slug}:nondet:negative:dup-add"
        lines.append(f'bp.registerBThread("{neg_dup_name}", function() {{')
        lines.append(f"  // Negative: duplicate-add for {ent_name}")
        lines.append(f"  {add_fn}({neg_dup_arg_str});")
        lines.append(f"  {ver_fn}({neg_dup_arg_str});")
        lines.append(f"  {try_add_fn}({neg_dup_arg_str});")
        lines.append("});")
        lines.append("")

        # Negative delete-nonexisting story
        neg_del_id = 2000 + idx * 10
        neg_del_args = _make_args_for_id(params, neg_del_id)
        neg_del_arg_str = ", ".join(neg_del_args)
        neg_del_name = f"crud:{slug}:nondet:negative:delete-nonexisting"
        lines.append(f'bp.registerBThread("{neg_del_name}", function() {{')
        lines.append(f"  // Negative: delete non-existing for {ent_name}")
        lines.append(f"  {add_fn}({neg_del_arg_str});")
        lines.append(f"  {del_fn}({neg_del_arg_str});")
        lines.append(f"  {try_del_non_fn}({neg_del_arg_str});")
        lines.append("});")
        lines.append("")

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "stories_hls.js"
    out_path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def emit_interfaces_and_stories(spec: Dict[str, Any], out_dir: Path) -> None:
    """
    Single public entry point used by run_openapi_to_interfaces_and_stories.py.

    - spec: JSON spec produced by the LLM (sut, entities, stories)
    - out_dir: provengo_ready/<sut>/spec/js
    """
    if not isinstance(out_dir, Path):
        out_dir = Path(out_dir)
    _emit_interfaces(spec, out_dir)
    _emit_stories(spec, out_dir)
