// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

bp.registerBThread("App_basicCrud", function() {
  // Basic CRUD story for App
  addApp(201, "name_201");
  verifyAppExists(201, "name_201");
  deleteApp(201, "name_201");
});

bp.registerBThread("Env_basicCrud", function() {
  // Basic CRUD story for Env
  addEnv(201, "name_201");
  verifyEnvExists(201, "name_201");
  deleteEnv(201, "name_201");
});

bp.registerBThread("Config_basicCrud", function() {
  // Basic CRUD story for Config
  addConfig(201, "name_201");
  verifyConfigExists(201, "name_201");
  deleteConfig(201, "name_201");
});

bp.registerBThread("Release_basicCrud", function() {
  // Basic CRUD story for Release
  addRelease(201, "name_201");
  verifyReleaseExists(201, "name_201");
  deleteRelease(201, "name_201");
});

bp.registerBThread("Policy_basicCrud", function() {
  // Basic CRUD story for Policy
  addPolicy(201, "name_201");
  verifyPolicyExists(201, "name_201");
  deletePolicy(201, "name_201");
});

bp.registerBThread("App_duplicateAdd", function() {
  // Duplicate-add scenario for App
  addApp(202, "name_202");
  verifyAppExists(202, "name_202");
  addApp(202, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("Env_duplicateAdd", function() {
  // Duplicate-add scenario for Env
  addEnv(202, "name_202");
  verifyEnvExists(202, "name_202");
  addEnv(202, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("Config_duplicateAdd", function() {
  // Duplicate-add scenario for Config
  addConfig(202, "name_202");
  verifyConfigExists(202, "name_202");
  addConfig(202, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("Release_duplicateAdd", function() {
  // Duplicate-add scenario for Release
  addRelease(202, "name_202");
  verifyReleaseExists(202, "name_202");
  addRelease(202, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("Policy_duplicateAdd", function() {
  // Duplicate-add scenario for Policy
  addPolicy(202, "name_202");
  verifyPolicyExists(202, "name_202");
  addPolicy(202, "name_202");  // expected to fail or be blocked
});

