// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

bp.registerBThread("Machine_basicCrud", function() {
  // Basic CRUD story for Machine
  addMachine(201, "name_201");
  verifyMachineExists(201, "name_201");
  deleteMachine(201, "name_201");
});

bp.registerBThread("WorkOrder_basicCrud", function() {
  // Basic CRUD story for WorkOrder
  addWorkOrder(201, undefined);
  verifyWorkOrderExists(201, undefined);
  deleteWorkOrder(201, undefined);
});

bp.registerBThread("MaintenanceTicket_basicCrud", function() {
  // Basic CRUD story for MaintenanceTicket
  addMaintenanceTicket(201, undefined);
  verifyMaintenanceTicketExists(201, undefined);
  deleteMaintenanceTicket(201, undefined);
});

bp.registerBThread("SensorReading_basicCrud", function() {
  // Basic CRUD story for SensorReading
  addSensorReading(201, undefined);
  verifySensorReadingExists(201, undefined);
  deleteSensorReading(201, undefined);
});

bp.registerBThread("Machine_duplicateAdd", function() {
  // Duplicate-add scenario for Machine
  addMachine(202, "name_202");
  verifyMachineExists(202, "name_202");
  addMachine(202, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("WorkOrder_duplicateAdd", function() {
  // Duplicate-add scenario for WorkOrder
  addWorkOrder(202, undefined);
  verifyWorkOrderExists(202, undefined);
  addWorkOrder(202, undefined);  // expected to fail or be blocked
});

bp.registerBThread("MaintenanceTicket_duplicateAdd", function() {
  // Duplicate-add scenario for MaintenanceTicket
  addMaintenanceTicket(202, undefined);
  verifyMaintenanceTicketExists(202, undefined);
  addMaintenanceTicket(202, undefined);  // expected to fail or be blocked
});

bp.registerBThread("SensorReading_duplicateAdd", function() {
  // Duplicate-add scenario for SensorReading
  addSensorReading(202, undefined);
  verifySensorReadingExists(202, undefined);
  addSensorReading(202, undefined);  // expected to fail or be blocked
});

