// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT=keycloak_admin  Provider=real_world_llm_provider  Mode=?  Stories=110
// Source: artifacts/hls_det/real_world_llm_provider/keycloak_admin/hls_gold.json
// ============================================================================
bthread("CRUD_add_model", function() {
});

bthread("CRUD_admin_event", function() {
});

bthread("CRUD_attack_detection", function() {
});

bthread("CRUD_authentication", function() {
});

bthread("CRUD_authenticator_provider", function() {
});

bthread("CRUD_available", function() {
});

bthread("CRUD_brute_force", function() {
});

bthread("CRUD_certificate", function() {
});

bthread("CRUD_children", function() {
});

bthread("CRUD_client", function() {
});

bthread("CRUD_client_authenticator_provider", function() {
});

bthread("CRUD_client_description_converter", function() {
});

bthread("CRUD_client_policy", function() {
});

bthread("CRUD_client_registration_policy", function() {
});

bthread("CRUD_client_scope", function() {
});

bthread("CRUD_client_secret", function() {
});

bthread("CRUD_client_session_stat", function() {
});

bthread("CRUD_client_template", function() {
});

bthread("CRUD_clients_initial_acces", function() {
});

bthread("CRUD_component", function() {
});

bthread("CRUD_composite", function() {
});

bthread("CRUD_config", function() {
});

bthread("CRUD_config_description", function() {
});

bthread("CRUD_configured_user_storage_credential_type", function() {
});

bthread("CRUD_consent", function() {
});

bthread("CRUD_copy", function() {
});

bthread("CRUD_count", function() {
});

bthread("CRUD_credential", function() {
});

bthread("CRUD_credential_registrator", function() {
});

bthread("CRUD_default_client_scope", function() {
});

bthread("CRUD_default_default_client_scope", function() {
});

bthread("CRUD_default_group", function() {
});

bthread("CRUD_default_optional_client_scope", function() {
});

bthread("CRUD_disable_credential_type", function() {
});

bthread("CRUD_download", function() {
});

bthread("CRUD_evaluate_scope", function() {
});

bthread("CRUD_event", function() {
});

bthread("CRUD_execute_actions_email", function() {
});

bthread("CRUD_execution", function() {
});

bthread("CRUD_export", function() {
});

bthread("CRUD_federated_identity", function() {
});

bthread("CRUD_flow", function() {
});

bthread("CRUD_form_action_provider", function() {
});

bthread("CRUD_form_provider", function() {
});

bthread("CRUD_generate", function() {
});

bthread("CRUD_generate_and_download", function() {
});

bthread("CRUD_generate_example_access_token", function() {
});

bthread("CRUD_generate_example_id_token", function() {
});

bthread("CRUD_generate_example_userinfo", function() {
});

bthread("CRUD_granted", function() {
});

bthread("CRUD_group", function() {
});

bthread("CRUD_group_by_path", function() {
});

bthread("CRUD_identity_provider", function() {
});

bthread("CRUD_impersonation", function() {
});

bthread("CRUD_import_config", function() {
});

bthread("CRUD_installation", function() {
});

bthread("CRUD_instance", function() {
});

bthread("CRUD_key", function() {
});

bthread("CRUD_localization", function() {
});

bthread("CRUD_logout", function() {
});

bthread("CRUD_logout_all", function() {
});

bthread("CRUD_lower_priority", function() {
});

bthread("CRUD_management", function() {
});

bthread("CRUD_mapper", function() {
});

bthread("CRUD_mapper_type", function() {
});

bthread("CRUD_member", function() {
});

bthread("CRUD_model", function() {
});

bthread("CRUD_moveafter", function() {
});

bthread("CRUD_movetofirst", function() {
});

bthread("CRUD_node", function() {
});

bthread("CRUD_not_granted", function() {
});

bthread("CRUD_offline_session", function() {
});

bthread("CRUD_offline_session_count", function() {
});

bthread("CRUD_optional_client_scope", function() {
});

bthread("CRUD_partial_export", function() {
});

bthread("CRUD_partialimport", function() {
});

bthread("CRUD_per_client_config_description", function() {
});

bthread("CRUD_permission", function() {
});

bthread("CRUD_policy", function() {
});

bthread("CRUD_profile", function() {
});

bthread("CRUD_protocol", function() {
});

bthread("CRUD_protocol_mapper", function() {
});

bthread("CRUD_provider", function() {
});

bthread("CRUD_push_revocation", function() {
});

bthread("CRUD_raise_priority", function() {
});

bthread("CRUD_realm", function() {
});

bthread("CRUD_register_required_action", function() {
});

bthread("CRUD_registration_access_token", function() {
});

bthread("CRUD_required_action", function() {
});

bthread("CRUD_reset_password", function() {
});

bthread("CRUD_reset_password_email", function() {
});

bthread("CRUD_role", function() {
});

bthread("CRUD_role_mapping", function() {
});

bthread("CRUD_roles_by_id", function() {
});

bthread("CRUD_rotated", function() {
});

bthread("CRUD_scope_mapping", function() {
});

bthread("CRUD_send_verify_email", function() {
});

bthread("CRUD_service_account_user", function() {
});

bthread("CRUD_session", function() {
});

bthread("CRUD_session_count", function() {
});

bthread("CRUD_sub_component_type", function() {
});

bthread("CRUD_test_nodes_available", function() {
});

bthread("CRUD_testsmtpconnection", function() {
});

bthread("CRUD_unregistered_required_action", function() {
});

bthread("CRUD_upload", function() {
});

bthread("CRUD_upload_certificate", function() {
});

bthread("CRUD_user", function() {
});

bthread("CRUD_user_session", function() {
});

bthread("CRUD_userlabel", function() {
});

bthread("CRUD_users_management_permission", function() {
});
