// === Auto-generated stories_hls.js ===
// DO NOT EDIT BY HAND. Generated by emit_interfaces_and_stories_from_spec.py

bp.registerBThread("Realm_basicCrud", function() {
  // Basic CRUD story for Realm
  addRealm(undefined);
  verifyRealmExists(undefined);
  deleteRealm(undefined);
});

bp.registerBThread("Client_basicCrud", function() {
  // Basic CRUD story for Client
  addClient(201, undefined, "name_201");
  verifyClientExists(201, undefined, "name_201");
  deleteClient(201, undefined, "name_201");
});

bp.registerBThread("User_basicCrud", function() {
  // Basic CRUD story for User
  addUser(201, "name_201", undefined);
  verifyUserExists(201, "name_201", undefined);
  deleteUser(201, "name_201", undefined);
});

bp.registerBThread("Client_duplicateAdd", function() {
  // Duplicate-add scenario for Client
  addClient(202, undefined, "name_202");
  verifyClientExists(202, undefined, "name_202");
  addClient(202, undefined, "name_202");  // expected to fail or be blocked
});

bp.registerBThread("User_duplicateAdd", function() {
  // Duplicate-add scenario for User
  addUser(202, "name_202", undefined);
  verifyUserExists(202, "name_202", undefined);
  addUser(202, "name_202", undefined);  // expected to fail or be blocked
});

