# scripts/readable/emit_hls_all_in_one.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
emit_hls_all_in_one.py
----------------------
Robust emitter for stories_hls.js from HLS GOLD.

- Works for both det/nondet GOLD.
- Consumes either "stories_js" (string) or "stories" (array with "js" or "steps").
- Always writes stories_hls.js to --out_dir.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

HEADER = """// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT={sut}  Provider={provider}  Mode=?  Stories={count}
// Source: {source}
// ============================================================================
"""

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--gold", required=True, help="Path to HLS GOLD (det/nondet)")
    p.add_argument("--out_dir", required=True, help="Directory to write stories_hls.js")
    p.add_argument("--dsl_map", default=None)
    p.add_argument("--graph", default=None)
    p.add_argument("--max_stories", type=int, default=0)
    return p.parse_args()

def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)

def synthesize_bthread(name: str, entity: Optional[str], steps: list) -> str:
    # Minimal synthesis: renders a bthread from step names; safe fallback.
    safe_name = name.replace('"', '\\"')
    lines = [f'bthread("{safe_name}", function() {{']
    for s in steps or []:
        # accept dict step with fields or a simple string
        if isinstance(s, dict):
            what = s.get("name") or s.get("event") or s.get("action") or "step"
        else:
            what = str(s)
        what = what.replace('"', '\\"')
        lines.append(f'  bp.sync({{request: bp.Event("{what}")}});')
    lines.append("});")
    return "\n".join(lines)

def stories_from_gold(gold: Dict[str, Any], max_stories: int) -> str:
    # 1) direct JS bundle?
    sj = gold.get("stories_js")
    if isinstance(sj, str) and sj.strip():
        return sj

    # 2) list of stories with js or steps
    arr = gold.get("stories") or []
    out_chunks: List[str] = []
    count = 0
    for item in arr:
        if max_stories and count >= max_stories:
            break
        if not isinstance(item, dict):
            continue
        name = item.get("name") or f"story_{count+1}"
        entity = item.get("entity")
        if "js" in item and isinstance(item["js"], str) and item["js"].strip():
            out_chunks.append(item["js"])
            count += 1
            continue
        steps = item.get("steps") or []
        out_chunks.append(synthesize_bthread(name, entity, steps))
        count += 1
    return "\n\n".join(out_chunks)

def main() -> None:
    args = parse_args()
    gold_path = Path(args.gold)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    gold = load_json(gold_path)
    provider = gold.get("provider") or gold.get("meta", {}).get("provider") or "?"
    sut = gold.get("sut") or gold.get("meta", {}).get("sut") or "?"
    src = gold_path.as_posix()

    stories_js = stories_from_gold(gold, args.max_stories)
    # Count (best-effort) = number of 'bthread(' occurrences or fallback to stories length.
    if stories_js.strip():
        try:
            n = stories_js.count("bthread(")
            if not n and isinstance(gold.get("stories"), list):
                n = len(gold["stories"])
        except Exception:
            n = 0
    else:
        n = 0

    header = HEADER.format(sut=sut, provider=provider, count=n, source=src)

    js_path = out_dir / "stories_hls.js"
    with js_path.open("w", encoding="utf-8") as f:
        f.write(header)
        if stories_js.strip():
            if not header.endswith("\n"):
                f.write("\n")
            f.write(stories_js)
            if not stories_js.endswith("\n"):
                f.write("\n")

    # Optional quick coverage summary (empty by design unless your GOLD carries per-entity data)
    # ----- Coverage / ops summary -----
    # Derive by-entity counts from GOLD (if stories array exists).
    by_entity = {}
    stories_arr = gold.get("stories")
    if isinstance(stories_arr, list):
        for it in stories_arr:
            if isinstance(it, dict):
                ent = it.get("entity")
                if ent:
                    by_entity[ent] = by_entity.get(ent, 0) + 1

    coverage = {
        "source": gold_path.as_posix(),
        "provider": provider,
        "sut": sut,
        "stories_total": n,
        "by_entity": by_entity,     # may be {} if GOLD lacks per-entity info
    }

    # Write one level above the readable/ folder
    cov_path = out_dir.parent / "hls_gold_ops.json"
    with cov_path.open("w", encoding="utf-8") as f:
        json.dump(coverage, f, ensure_ascii=False, indent=2)

    print(f"[INFO] Using GOLD: {gold_path.as_posix()}")
    print(f"[OK] wrote {js_path.as_posix()} ({n} stories)")
    print(f"[COVERAGE] by_entity={by_entity}")

if __name__ == "__main__":
    main()
