#!/usr/bin/env node
// emit_hls_readable.mjs
// Minimal, dependency-free emitter that turns a DSL map into stories_hls.js

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

function argOf(flag, fallback = undefined) {
  const idx = process.argv.indexOf(flag);
  return idx >= 0 && process.argv[idx + 1] ? process.argv[idx + 1] : fallback;
}

const graph = argOf("--graph");
const dslMapPath = argOf("--dsl_map");
const mode = (argOf("--mode", "det") || "det").toLowerCase(); // det | nondet
const profile = process.env.PROFILE || "rich";
const perEntityMax = Number(process.env.PER_ENTITY_MAX || "3");

if (!dslMapPath) {
  console.error("Missing --dsl_map <path>");
  process.exit(2);
}
if (!graph) {
  console.error("Missing --graph <path>");
  process.exit(2);
}

const dsl = JSON.parse(readFileSync(dslMapPath, "utf-8"));
const entities = Array.isArray(dsl.entities) ? dsl.entities : [];
const ops = Array.isArray(dsl.ops) ? dsl.ops : [];

function inferSuiteDirFromGraph(p) {
  const norm = p.replace(/\\/g, "/");
  const parts = norm.split("/");
  // artifacts/analysis/<suite_dir>/graph.json
  const idx = parts.indexOf("analysis");
  if (idx >= 0 && parts[idx - 1] === "artifacts" && parts[idx + 1]) {
    return parts.slice(idx + 1, parts.length - 1).join("/");
  }
  return "";
}

const suiteDir = inferSuiteDirFromGraph(graph);
const outRoot = mode === "det" ? "artifacts/hls_det" : "artifacts/hls_nondet";
const outDir = resolve(`${outRoot}/${suiteDir}/readable`);
mkdirSync(outDir, { recursive: true });

const stories = [];
const byEntity = new Map(entities.map(e => [e, 0]));

// Group ops by entity prefix (best-effort)
for (const op of ops) {
  const ent = entities.find(e => op.startsWith(e));
  if (!ent) continue;
  if (byEntity.get(ent) >= perEntityMax) continue;
  byEntity.set(ent, byEntity.get(ent) + 1);
  stories.push({
    title: `${ent} - ${op} (${mode})`,
    steps: [op],
  });
}

// Fallback: if nothing matched entities, emit one story per op (up to 100)
if (stories.length === 0 && ops.length) {
  for (const op of ops.slice(0, 100)) {
    stories.push({
      title: `${op} (${mode})`,
      steps: [op],
    });
  }
}

// Minimal HLS-readable JS
const fileText = `/* Auto-generated by emit_hls_readable.mjs */
/* PROFILE=${profile} MODE=${mode} PER_ENTITY_MAX=${perEntityMax} */
export const stories = ${JSON.stringify(stories, null, 2)};
`;

const outFile = resolve(outDir, "stories_hls.js");
writeFileSync(outFile, fileText, "utf-8");

console.log(`[OK] wrote ${outFile} (${stories.length} stories)`);
