#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
emit_hls_all_in_one.py
----------------------
Robust emitter for stories_hls.js from HLS GOLD.

Design goals:
- Works for both det/nondet. Uses GOLD's "stories" (each with {"name","js"}) or "stories_js".
- Makes DET look like NONDET by emitting the same header + concatenated JS blocks from GOLD.
- Writes a small coverage file "<sut_dir>/hls_gold_ops.json" (count, by_entity) for quick sanity checks.
- Accepts optional --dsl_map and --graph (logged for traceability only; not required if GOLD already has JS).
- Handles Windows/Unix paths and extra quotes gracefully.
"""

from __future__ import annotations
import argparse, json, os, re, sys
from pathlib import Path

def _norm(p: str | None) -> str | None:
    if not p:
        return None
    # Strip any surrounding quotes once, then normpath
    p = p.strip().strip('"').strip("'")
    return os.path.normpath(p)

def load_gold(gold_path: str) -> dict:
    with open(gold_path, "r", encoding="utf-8") as f:
        return json.load(f)

def concat_stories_js(gold: dict) -> tuple[str,int,dict]:
    """
    Returns: (full_js_text, n_stories, by_entity)
    """
    by_entity = {}
    if isinstance(gold.get("stories_js"), str) and gold["stories_js"].strip():
        # Prefer the pre-concatenated JS field when present
        js = gold["stories_js"]
        # Try to count by splitting per header markers if present
        names = []
        for m in re.finditer(r'//\s*-{2}\s*(.*?)\s*-{2}', js):
            names.append(m.group(1).strip())
        for nm in names:
            m2 = re.match(r'^crud:([^:]+):', nm)
            ent = m2.group(1) if m2 else "?"
            by_entity[ent] = by_entity.get(ent, 0) + 1
        return js, len(names) if names else 0, by_entity

    # Otherwise, build from stories[] list (each item has {"name","js"})
    stories = gold.get("stories") or []
    chunks = []
    for s in stories:
        name = s.get("name", "").strip()
        js = s.get("js", "").rstrip()
        if name and js:
            chunks.append(js if js.endswith("\n") else js + "\n")
            m = re.match(r'^crud:([^:]+):', name)
            ent = m.group(1) if m else "?"
            by_entity[ent] = by_entity.get(ent, 0) + 1
    return ("\n".join(chunks), len(stories), by_entity)

def banner(gold: dict, n: int) -> str:
    sut = gold.get("sut","?")
    provider = gold.get("provider","?")
    mode = gold.get("mode","?")
    src = gold.get("source",{})
    created_by = src.get("created_by","")
    return f"""// ============================================================================
// Auto-generated by emit_hls_all_in_one.py
// SUT={sut}  Provider={provider}  Mode={mode}  Stories={n}
// Source: {created_by}
// ============================================================================
"""

def write_ops(out_dir: Path, by_entity: dict, count: int) -> None:
    out = {
        "count_stories": count,
        "by_entity": by_entity,
    }
    out_path = out_dir / "hls_gold_ops.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gold", required=True, help="Path to hls_gold.json")
    ap.add_argument("--out_dir", required=True, help="Directory to write /readable/stories_hls.js into")
    ap.add_argument("--dsl_map", default=None, help="Optional DSL map (logged)")
    ap.add_argument("--graph", default=None, help="Optional graph.json (logged)")
    ap.add_argument("--max_stories", type=int, default=0, help="Limit number of stories (0 = all)")
    args = ap.parse_args()

    gold_path = _norm(args.gold)
    out_dir = Path(_norm(args.out_dir))
    dsl_map = _norm(args.dsl_map)
    graph = _norm(args.graph)

    if not gold_path or not os.path.isfile(gold_path):
        print(f"[ERR] GOLD not found: {args.gold}", file=sys.stderr)
        sys.exit(2)

    out_dir.mkdir(parents=True, exist_ok=True)
    if dsl_map:
        print(f'    using --dsl_map "{dsl_map}"')
    if graph:
        print(f'    using --graph "{graph}"')

    print(f"[INFO] Using GOLD: {gold_path.replace(os.sep, '/')}")
    gold = load_gold(gold_path)
    stories_js, n, by_entity = concat_stories_js(gold)

    if args.max_stories > 0:
        # naïve truncation by detecting per-story separators; robust when built from stories[]
        # When stories_js came as one block, we'll do a safe split on bthread openings.
        blocks = re.split(r'\n(?=bthread\()', stories_js, flags=re.MULTILINE)
        if len(blocks) > args.max_stories:
            stories_js = "\n".join(blocks[:args.max_stories])
            # recount roughly
            n = args.max_stories

    # Emit file
    js_path = out_dir / "stories_hls.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(banner(gold, n))
        f.write("\n")
        f.write(stories_js)
        if not stories_js.endswith("\n"):
            f.write("\n")

    write_ops(out_dir.parent, by_entity, n)
    print(f"[OK] wrote {js_path.as_posix()} ({n} stories)")
    print(f"[COVERAGE] by_entity={by_entity}")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[INTERRUPTED]")
        raise
